import type { SeedDatacenter, SeedBrand } from "./types";

// === AI-NATIVE + COLO + MEGACAMPUS ===
export const AI_NATIVE: SeedDatacenter[] = [
  // ========== (a) AI-NATIVE / NEOCLOUD OPERATORS ==========

  // --- CoreWeave footprint (skipping coreweave-plano which is already seeded) ---
  {
    slug: "coreweave-las-vegas-lv1",
    name: "CoreWeave Las Vegas LV1",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 36.1699,
    lng: -115.1398,
    city: "Las Vegas",
    region: "NV",
    country: "US",
    capacityMw: 36,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave GPU cloud region in Las Vegas; one of the operator's earliest dedicated H100/H200 cluster sites.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave Data Centers",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/coreweave-expands-with-new-data-centers-across-the-us/",
        title: "CoreWeave expands with new data centers across the US",
        type: "news",
      },
    ],
  },
  {
    slug: "coreweave-atlanta-at1",
    name: "CoreWeave Atlanta AT1",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 33.749,
    lng: -84.388,
    city: "Atlanta",
    region: "GA",
    country: "US",
    capacityMw: 24,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description: "CoreWeave Atlanta GPU cloud region serving the US Southeast.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-chicago-ch1",
    name: "CoreWeave Chicago CH1",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 41.8781,
    lng: -87.6298,
    city: "Chicago",
    region: "IL",
    country: "US",
    capacityMw: 32,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description: "CoreWeave Chicago AI cloud region.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-weehawken-nj1",
    name: "CoreWeave Weehawken NJ1",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 40.7691,
    lng: -74.0209,
    city: "Weehawken",
    region: "NJ",
    country: "US",
    capacityMw: 18,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave's original New Jersey GPU cloud node, in the NY metro area.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-chantilly-va1",
    name: "CoreWeave Chantilly VA1",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 38.8943,
    lng: -77.4311,
    city: "Chantilly",
    region: "VA",
    country: "US",
    capacityMw: 40,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave Northern Virginia GPU region in the Loudoun/Chantilly cluster.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-sunbury-pa",
    name: "CoreWeave Sunbury (Core Scientific lease)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 40.8632,
    lng: -76.7944,
    city: "Sunbury",
    region: "PA",
    country: "US",
    capacityMw: 100,
    capacityMwPlanned: 200,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Pennsylvania HPC site leased from Core Scientific under their multi-billion-dollar 2024 hosting contract.",
    sources: [
      {
        url: "https://corescientific.com/news/core-scientific-announces-expansion-of-coreweave-hpc-hosting-contracts",
        title: "Core Scientific expands CoreWeave HPC hosting",
        type: "pr",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/core-scientific-coreweave-expand-hpc-hosting-deal-to-12bn/",
        title: "Core Scientific & CoreWeave $12bn HPC hosting deal",
        type: "news",
      },
    ],
  },
  {
    slug: "coreweave-denton-tx",
    name: "CoreWeave Denton (Core Scientific lease)",
    operatorSlug: "coreweave",
    status: "under-construction",
    aiDedicated: true,
    lat: 33.2148,
    lng: -97.1331,
    city: "Denton",
    region: "TX",
    country: "US",
    capacityMwPlanned: 70,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Texas HPC build-out hosted by Core Scientific for CoreWeave under the expanded 2024 hosting contracts.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/core-scientific-coreweave-expand-hpc-hosting-deal-to-12bn/",
        title: "Core Scientific & CoreWeave $12bn HPC hosting deal",
        type: "news",
      },
    ],
  },
  {
    slug: "coreweave-stavanger-no",
    name: "CoreWeave Stavanger (Norway)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 58.969,
    lng: 5.7331,
    city: "Stavanger",
    country: "NO",
    capacityMw: 30,
    primaryPowerSource: "hydro",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave Norway GPU cloud presence, hosted in renewable-powered Nordic colocation.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave Data Centers",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/coreweave-launches-european-data-centers-in-norway/",
        title: "CoreWeave launches European data centers in Norway",
        type: "news",
      },
    ],
  },
  {
    slug: "coreweave-london-uk",
    name: "CoreWeave London (UK)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 51.5074,
    lng: -0.1278,
    city: "London",
    country: "GB",
    capacityMw: 20,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave first UK region; part of the operator's $3.5bn UK expansion announced 2024.",
    sources: [
      {
        url: "https://www.coreweave.com/blog/coreweave-uk-expansion",
        title: "CoreWeave UK Expansion",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/coreweave-to-invest-22bn-in-uk-data-centers/",
        title: "CoreWeave to invest in UK data centers",
        type: "news",
      },
    ],
  },

  // --- Crusoe ---
  {
    slug: "crusoe-reykjavik-is",
    name: "Crusoe Reykjavik (Iceland)",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 64.1466,
    lng: -21.9426,
    city: "Reykjavik",
    country: "IS",
    capacityMw: 40,
    primaryPowerSource: "geothermal",
    coolingType: "direct-to-chip",
    description:
      "Crusoe's Iceland AI cloud site running on geothermal/hydro power.",
    sources: [
      {
        url: "https://crusoe.ai/cloud/",
        title: "Crusoe Cloud",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/crusoe-energy-launches-iceland-ai-data-center/",
        title: "Crusoe launches Iceland AI data center",
        type: "news",
      },
    ],
  },
  {
    slug: "crusoe-permian-basin-tx",
    name: "Crusoe Permian Basin Flare-Gas Sites",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 31.8457,
    lng: -102.3676,
    city: "Midland",
    region: "TX",
    country: "US",
    capacityMw: 60,
    primaryPowerSource: "gas",
    coolingType: "air",
    description:
      "Crusoe's modular Digital Flare Mitigation datacenters across the Permian Basin oilfield, repurposed from Bitcoin to AI compute.",
    sources: [
      {
        url: "https://crusoe.ai/",
        title: "Crusoe Energy Systems",
        type: "operator",
      },
      {
        url: "https://www.datacenterfrontier.com/cloud/article/55027654/crusoe-energy-pivots-to-ai",
        title: "Crusoe Energy pivots to AI",
        type: "news",
      },
    ],
  },
  {
    slug: "crusoe-bakken-nd",
    name: "Crusoe Bakken (North Dakota)",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 47.7755,
    lng: -103.2412,
    city: "Williston",
    region: "ND",
    country: "US",
    capacityMw: 20,
    primaryPowerSource: "gas",
    coolingType: "air",
    description: "Crusoe Bakken-shale flare-gas powered modular datacenters.",
    sources: [
      {
        url: "https://crusoe.ai/",
        title: "Crusoe Energy Systems",
        type: "operator",
      },
    ],
  },
  {
    slug: "crusoe-wyoming",
    name: "Crusoe Wyoming Flare-Gas Site",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 43.076,
    lng: -107.2903,
    region: "WY",
    country: "US",
    capacityMw: 12,
    primaryPowerSource: "gas",
    coolingType: "air",
    description:
      "Crusoe modular flare-gas-powered compute installations in Wyoming.",
    sources: [
      {
        url: "https://crusoe.ai/",
        title: "Crusoe Energy Systems",
        type: "operator",
      },
    ],
  },

  // --- Lambda Labs ---
  {
    slug: "lambda-allen-tx",
    name: "Lambda Labs Allen TX (1-Click Cluster)",
    operatorSlug: "lambda-labs",
    status: "operational",
    aiDedicated: true,
    lat: 33.1032,
    lng: -96.6706,
    city: "Allen",
    region: "TX",
    country: "US",
    capacityMw: 24,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Lambda's Texas H100/H200 cluster site supporting their 1-Click Cluster product.",
    sources: [
      {
        url: "https://lambdalabs.com/blog/lambda-raises-480m-series-d",
        title: "Lambda Series D",
        type: "pr",
      },
      {
        url: "https://lambdalabs.com/service/gpu-cloud",
        title: "Lambda GPU Cloud",
        type: "operator",
      },
    ],
  },
  {
    slug: "lambda-san-francisco-bay",
    name: "Lambda Labs SF Bay Cluster",
    operatorSlug: "lambda-labs",
    status: "operational",
    aiDedicated: true,
    lat: 37.7749,
    lng: -122.4194,
    city: "San Francisco",
    region: "CA",
    country: "US",
    capacityMw: 10,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Lambda's Bay Area cluster (colo-hosted) for GPU cloud customers.",
    sources: [
      {
        url: "https://lambdalabs.com/service/gpu-cloud",
        title: "Lambda GPU Cloud",
        type: "operator",
      },
    ],
  },

  // --- Together AI ---
  {
    slug: "together-ai-reno-nv",
    name: "Together AI Reno Cluster",
    operatorSlug: "together-ai",
    status: "operational",
    aiDedicated: true,
    lat: 39.5296,
    lng: -119.8138,
    city: "Reno",
    region: "NV",
    country: "US",
    capacityMw: 15,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Together AI training cluster colocated in the Tahoe Reno region.",
    sources: [
      {
        url: "https://www.together.ai/blog/series-b",
        title: "Together AI Series B",
        type: "pr",
      },
    ],
  },

  // --- Cerebras ---
  {
    slug: "cerebras-condor-galaxy-1-santa-clara",
    name: "Cerebras Condor Galaxy 1 (Santa Clara)",
    operatorSlug: "cerebras",
    status: "operational",
    aiDedicated: true,
    lat: 37.3541,
    lng: -121.9552,
    city: "Santa Clara",
    region: "CA",
    country: "US",
    capacityMw: 8,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Cerebras / G42 Condor Galaxy 1 wafer-scale AI supercomputer hosted in Colovore Santa Clara.",
    sources: [
      {
        url: "https://www.cerebras.net/press-release/cerebras-g42-launch-worlds-largest-ai-supercomputer-condor-galaxy-1",
        title: "Condor Galaxy 1 launch",
        type: "pr",
      },
    ],
  },
  {
    slug: "cerebras-condor-galaxy-2-stockton",
    name: "Cerebras Condor Galaxy 2 (Stockton)",
    operatorSlug: "cerebras",
    status: "operational",
    aiDedicated: true,
    lat: 37.9577,
    lng: -121.2908,
    city: "Stockton",
    region: "CA",
    country: "US",
    capacityMw: 8,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Second of the Cerebras/G42 Condor Galaxy wafer-scale clusters.",
    sources: [
      {
        url: "https://www.cerebras.net/press-release/cerebras-g42-launch-worlds-largest-ai-supercomputer-condor-galaxy-1",
        title: "Condor Galaxy series",
        type: "pr",
      },
    ],
  },

  // --- Voltage Park ---
  {
    slug: "voltage-park-dallas",
    name: "Voltage Park Dallas H100 Cluster",
    operatorSlug: "voltage-park",
    status: "operational",
    aiDedicated: true,
    lat: 32.7767,
    lng: -96.797,
    city: "Dallas",
    region: "TX",
    country: "US",
    capacityMw: 18,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Voltage Park's 24,000+ H100 GPU cluster, one of several US sites for the nonprofit-backed AI cloud.",
    sources: [
      {
        url: "https://www.voltagepark.com/",
        title: "Voltage Park",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/voltage-park-launches-with-24000-nvidia-h100-gpus/",
        title: "Voltage Park launches with 24,000 H100s",
        type: "news",
      },
    ],
  },

  // --- Nebius ---
  {
    slug: "nebius-mantsala-fi",
    name: "Nebius Mäntsälä",
    operatorSlug: "nebius",
    status: "expanding",
    aiDedicated: true,
    lat: 60.6406,
    lng: 25.3197,
    city: "Mäntsälä",
    country: "FI",
    capacityMw: 75,
    capacityMwPlanned: 150,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Nebius's flagship European AI campus in Finland (formerly Yandex), expanded with NVIDIA H200/B200 capacity.",
    sources: [
      {
        url: "https://nebius.com/blog/posts/finland-data-center-expansion",
        title: "Nebius Finland expansion",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/nebius-to-invest-1bn-in-european-ai-infrastructure/",
        title: "Nebius to invest $1bn in European AI infrastructure",
        type: "news",
      },
    ],
  },
  {
    slug: "nebius-kansas-city-mo",
    name: "Nebius Kansas City",
    operatorSlug: "nebius",
    status: "under-construction",
    aiDedicated: true,
    lat: 39.0997,
    lng: -94.5786,
    city: "Kansas City",
    region: "MO",
    country: "US",
    capacityMwPlanned: 300,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Nebius's first US AI campus, announced 2024-2025 with up to 300MW of GPU capacity.",
    sources: [
      {
        url: "https://nebius.com/blog/posts/us-expansion-kansas-city",
        title: "Nebius Kansas City expansion",
        type: "operator",
      },
      {
        url: "https://www.reuters.com/technology/nebius-build-ai-data-center-kansas-city-2024-12-17/",
        title: "Nebius to build AI data center in Kansas City",
        type: "news",
      },
    ],
  },
  {
    slug: "nebius-israel",
    name: "Nebius Israel",
    operatorSlug: "nebius",
    status: "operational",
    aiDedicated: true,
    lat: 32.0853,
    lng: 34.7818,
    city: "Tel Aviv",
    country: "IL",
    capacityMw: 12,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Nebius Israel GPU cluster serving the regional AI startup ecosystem.",
    sources: [
      { url: "https://nebius.com/", title: "Nebius", type: "operator" },
    ],
  },

  // --- Applied Digital ---
  {
    slug: "applied-digital-ellendale-nd",
    name: "Applied Digital Ellendale HPC Campus",
    operatorSlug: "applied-digital",
    status: "operational",
    aiDedicated: true,
    lat: 46.0033,
    lng: -98.5234,
    city: "Ellendale",
    region: "ND",
    country: "US",
    capacityMw: 100,
    capacityMwPlanned: 400,
    primaryPowerSource: "wind",
    coolingType: "direct-to-chip",
    description:
      "Applied Digital's Ellendale, ND HPC campus, anchored by a 15-year CoreWeave lease for ~250MW of GPU capacity.",
    sources: [
      {
        url: "https://www.applieddigital.com/data-centers/",
        title: "Applied Digital Data Centers",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/coreweave-leases-applied-digital-ellendale-hpc-data-center/",
        title: "CoreWeave leases Applied Digital Ellendale",
        type: "news",
      },
    ],
  },
  {
    slug: "applied-digital-jamestown-nd",
    name: "Applied Digital Jamestown",
    operatorSlug: "applied-digital",
    status: "operational",
    aiDedicated: false,
    lat: 46.9105,
    lng: -98.7084,
    city: "Jamestown",
    region: "ND",
    country: "US",
    capacityMw: 106,
    primaryPowerSource: "wind",
    coolingType: "air",
    description:
      "Applied Digital Jamestown crypto-hosting site; some capacity being studied for AI conversion.",
    sources: [
      {
        url: "https://www.applieddigital.com/data-centers/",
        title: "Applied Digital Data Centers",
        type: "operator",
      },
    ],
  },

  // --- Iris Energy ---
  {
    slug: "iris-energy-childress-tx",
    name: "IREN Childress (AI HPC pivot)",
    operatorSlug: "iren",
    status: "expanding",
    aiDedicated: true,
    lat: 34.4267,
    lng: -100.2042,
    city: "Childress",
    region: "TX",
    country: "US",
    capacityMw: 350,
    capacityMwPlanned: 750,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "IREN (Iris Energy) Childress, TX site, with a portion of the campus being converted to liquid-cooled AI HPC.",
    sources: [
      { url: "https://iren.com/sites/", title: "IREN Sites", type: "operator" },
      {
        url: "https://www.datacenterdynamics.com/en/news/iren-iris-energy-launches-ai-cloud-services/",
        title: "IREN launches AI cloud services",
        type: "news",
      },
    ],
  },
  {
    slug: "iris-energy-prince-george-bc",
    name: "IREN Prince George (BC)",
    operatorSlug: "iren",
    status: "operational",
    aiDedicated: true,
    lat: 53.9171,
    lng: -122.7497,
    city: "Prince George",
    region: "BC",
    country: "CA",
    capacityMw: 50,
    primaryPowerSource: "hydro",
    coolingType: "air",
    description:
      "IREN's hydro-powered British Columbia site, hosting both miners and a growing AI compute footprint.",
    sources: [
      { url: "https://iren.com/sites/", title: "IREN Sites", type: "operator" },
    ],
  },

  // --- Hut 8 ---
  {
    slug: "hut8-medicine-hat-ab",
    name: "Hut 8 Medicine Hat",
    operatorSlug: "hut-8",
    status: "operational",
    aiDedicated: false,
    lat: 50.0405,
    lng: -110.6764,
    city: "Medicine Hat",
    region: "AB",
    country: "CA",
    capacityMw: 109,
    primaryPowerSource: "gas",
    coolingType: "air",
    description:
      "Hut 8 / US Bitcoin Corp Alberta site; part of the corporate footprint being assessed for HPC/AI deployments.",
    sources: [
      {
        url: "https://hut8.com/our-business/data-centers/",
        title: "Hut 8 Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "hut8-king-mountain-tx",
    name: "Hut 8 King Mountain",
    operatorSlug: "hut-8",
    status: "operational",
    aiDedicated: false,
    lat: 31.4015,
    lng: -102.0779,
    city: "Upton County",
    region: "TX",
    country: "US",
    capacityMw: 280,
    primaryPowerSource: "wind",
    coolingType: "air",
    description:
      "Hut 8's largest site, primarily mining but featuring in HPC/AI strategic options.",
    sources: [
      {
        url: "https://hut8.com/our-business/data-centers/",
        title: "Hut 8 Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "hut8-niagara-falls-ny",
    name: "Hut 8 Niagara Falls (HPC pivot)",
    operatorSlug: "hut-8",
    status: "operational",
    aiDedicated: true,
    lat: 43.0962,
    lng: -79.0377,
    city: "Niagara Falls",
    region: "NY",
    country: "US",
    capacityMw: 60,
    primaryPowerSource: "hydro",
    coolingType: "air",
    description:
      "Hut 8 Niagara Falls site with hydroelectric supply, repositioned to host HPC/AI workloads.",
    sources: [
      {
        url: "https://hut8.com/our-business/data-centers/",
        title: "Hut 8 Data Centers",
        type: "operator",
      },
    ],
  },

  // --- Galaxy Digital / Helios (former Core Scientific) ---
  {
    slug: "galaxy-helios-dickens-county-tx",
    name: "Galaxy Digital Helios Campus (Dickens County)",
    operatorSlug: "galaxy-digital",
    status: "expanding",
    aiDedicated: true,
    lat: 33.6234,
    lng: -100.8334,
    city: "Dickens County",
    region: "TX",
    country: "US",
    capacityMw: 200,
    capacityMwPlanned: 800,
    primaryPowerSource: "wind",
    coolingType: "direct-to-chip",
    description:
      "Galaxy's Helios campus (acquired from Argo Blockchain) in West Texas; signed a multi-hundred-MW lease with CoreWeave for AI HPC in 2024-2025.",
    sources: [
      {
        url: "https://www.galaxy.com/insights/research/galaxy-coreweave-helios-ai-data-center/",
        title: "Galaxy & CoreWeave Helios",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/galaxy-digital-coreweave-strike-data-center-deal-helios-texas/",
        title: "Galaxy Digital & CoreWeave Helios deal",
        type: "news",
      },
    ],
  },

  // --- Crypto-to-AI additions: TeraWulf, Riot, Bitfarms, Cipher ---
  {
    slug: "terawulf-nautilus-ny",
    name: "TeraWulf Nautilus Cryptomine (Nuclear-Powered)",
    operatorSlug: "terawulf",
    status: "operational",
    aiDedicated: true,
    lat: 41.3838,
    lng: -76.0011,
    city: "Salem Township",
    region: "PA",
    country: "US",
    capacityMw: 50,
    capacityMwPlanned: 200,
    primaryPowerSource: "nuclear",
    coolingType: "direct-to-chip",
    description:
      "TeraWulf's Nautilus site (co-located with Susquehanna nuclear plant); Lake Mariner sister site driving HPC/AI buildout.",
    sources: [
      {
        url: "https://www.terawulf.com/sites",
        title: "TeraWulf Sites",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/terawulf-launches-ai-hpc-business-unit/",
        title: "TeraWulf launches AI HPC unit",
        type: "news",
      },
    ],
  },
  {
    slug: "terawulf-lake-mariner-ny",
    name: "TeraWulf Lake Mariner (HPC pivot)",
    operatorSlug: "terawulf",
    status: "expanding",
    aiDedicated: true,
    lat: 43.2634,
    lng: -78.7186,
    city: "Barker",
    region: "NY",
    country: "US",
    capacityMw: 195,
    capacityMwPlanned: 750,
    primaryPowerSource: "hydro",
    coolingType: "direct-to-chip",
    description:
      "TeraWulf Lake Mariner; hydroelectric-powered HPC/AI campus expansion in upstate New York.",
    sources: [
      {
        url: "https://www.terawulf.com/sites",
        title: "TeraWulf Sites",
        type: "operator",
      },
    ],
  },
  {
    slug: "riot-rockdale-tx",
    name: "Riot Platforms Rockdale (HPC option)",
    operatorSlug: "riot-platforms",
    status: "operational",
    aiDedicated: false,
    lat: 30.6549,
    lng: -97.0011,
    city: "Rockdale",
    region: "TX",
    country: "US",
    capacityMw: 700,
    primaryPowerSource: "grid-mixed",
    coolingType: "immersion",
    description:
      "Riot's massive Rockdale campus on the former Alcoa site; strategic review underway for HPC/AI tenant deployment.",
    sources: [
      {
        url: "https://www.riotplatforms.com/operations",
        title: "Riot Operations",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/riot-platforms-explores-ai-data-center-pivot/",
        title: "Riot Platforms explores AI pivot",
        type: "news",
      },
    ],
  },
  {
    slug: "cipher-mining-black-pearl-tx",
    name: "Cipher Mining Black Pearl (TX)",
    operatorSlug: "cipher-mining",
    status: "under-construction",
    aiDedicated: true,
    lat: 31.45,
    lng: -100.42,
    region: "TX",
    country: "US",
    capacityMwPlanned: 300,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Cipher Mining's Black Pearl Texas site, designed with HPC/AI hosting capability alongside mining.",
    sources: [
      {
        url: "https://www.ciphermining.com/operations/",
        title: "Cipher Mining Operations",
        type: "operator",
      },
    ],
  },
  {
    slug: "bitfarms-pennsylvania-stronghold",
    name: "Bitfarms / Stronghold Pennsylvania",
    operatorSlug: "bitfarms",
    status: "operational",
    aiDedicated: false,
    lat: 40.7969,
    lng: -78.4053,
    city: "Nesquehoning",
    region: "PA",
    country: "US",
    capacityMw: 165,
    primaryPowerSource: "grid-mixed",
    coolingType: "air",
    description:
      "Bitfarms Pennsylvania assets (post Stronghold acquisition); identified for HPC/AI conversion review.",
    sources: [
      {
        url: "https://bitfarms.com/our-operations/",
        title: "Bitfarms Operations",
        type: "operator",
      },
    ],
  },

  // ========== (b) COLOCATION OPERATORS WITH AI/HPC ==========

  // --- Equinix ---
  {
    slug: "equinix-dc2-ashburn",
    name: "Equinix DC2 Ashburn",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 39.0184,
    lng: -77.4736,
    city: "Ashburn",
    region: "VA",
    country: "US",
    capacityMw: 30,
    primaryPowerSource: "grid-mixed",
    coolingType: "air",
    description:
      "Equinix DC2 - the original Ashburn campus building, anchor of Equinix Northern Virginia.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/washington-dc-data-centers",
        title: "Equinix DC data centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-dc15-ashburn",
    name: "Equinix DC15 Ashburn (xScale, AI-ready)",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: true,
    lat: 39.0156,
    lng: -77.4727,
    city: "Ashburn",
    region: "VA",
    country: "US",
    capacityMw: 32,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Equinix xScale Ashburn DC15 with liquid-cooled AI-ready halls.",
    sources: [
      {
        url: "https://www.equinix.com/newsroom/press-releases/2024/06/equinix-launches-private-ai",
        title: "Equinix Private AI launch",
        type: "pr",
      },
    ],
  },
  {
    slug: "equinix-sv1-silicon-valley",
    name: "Equinix SV1 San Jose",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 37.2358,
    lng: -121.7935,
    city: "San Jose",
    region: "CA",
    country: "US",
    capacityMw: 18,
    primaryPowerSource: "grid-mixed",
    coolingType: "air",
    description: "Equinix SV1, the anchor of the Silicon Valley campus.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/silicon-valley-data-centers",
        title: "Equinix Silicon Valley",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ny4-secaucus",
    name: "Equinix NY4 Secaucus",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 40.7895,
    lng: -74.0565,
    city: "Secaucus",
    region: "NJ",
    country: "US",
    capacityMw: 25,
    primaryPowerSource: "grid-mixed",
    coolingType: "air",
    description:
      "Equinix NY4 - flagship NY Metro carrier hotel and finance interconnection hub.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/new-york-data-centers/ny4",
        title: "Equinix NY4",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ty11-tokyo",
    name: "Equinix TY11 Tokyo",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: true,
    lat: 35.6586,
    lng: 139.7454,
    city: "Tokyo",
    country: "JP",
    capacityMw: 40,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Equinix TY11 - largest Japanese facility with NVIDIA DGX-ready AI halls.",
    sources: [
      {
        url: "https://www.equinix.com/newsroom/press-releases/2023/04/equinix-opens-new-ai-ready-data-center-ty11-japan",
        title: "Equinix TY11 launch",
        type: "pr",
      },
    ],
  },
  {
    slug: "equinix-sy5-sydney",
    name: "Equinix SY5 Sydney",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: -33.7654,
    lng: 151.0686,
    city: "Sydney",
    country: "AU",
    capacityMw: 20,
    primaryPowerSource: "grid-mixed",
    coolingType: "air",
    description: "Equinix SY5 Sydney xScale facility.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/asia-pacific-colocation/australia-colocation/sydney-data-centers",
        title: "Equinix Sydney",
        type: "operator",
      },
    ],
  },

  // --- Digital Realty ---
  {
    slug: "digitalrealty-icr2-ashburn",
    name: "Digital Realty ICR2 Ashburn",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: true,
    lat: 39.0252,
    lng: -77.4686,
    city: "Ashburn",
    region: "VA",
    country: "US",
    capacityMw: 35,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Digital Realty Building L (ICR2) at the Ashburn campus, with high-density AI-ready halls.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/americas/northern-virginia",
        title: "Digital Realty Northern Virginia",
        type: "operator",
      },
    ],
  },
  {
    slug: "digitalrealty-fra15-frankfurt",
    name: "Digital Realty FRA15 Frankfurt",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: true,
    lat: 50.1109,
    lng: 8.6821,
    city: "Frankfurt",
    country: "DE",
    capacityMw: 27,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Digital Realty FRA15 high-density facility with NVIDIA-certified AI hosting.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/emea/frankfurt",
        title: "Digital Realty Frankfurt",
        type: "operator",
      },
    ],
  },
  {
    slug: "digitalrealty-mrs3-marseille",
    name: "Digital Realty MRS3 Marseille",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: false,
    lat: 43.3078,
    lng: 5.367,
    city: "Marseille",
    country: "FR",
    capacityMw: 16,
    primaryPowerSource: "grid-mixed",
    coolingType: "open-loop",
    description:
      "Digital Realty MRS3 - sea-water cooled Mediterranean cable landing station.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/emea/marseille",
        title: "Digital Realty Marseille",
        type: "operator",
      },
    ],
  },
  {
    slug: "digitalrealty-sin12-singapore",
    name: "Digital Realty SIN12 Singapore",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: true,
    lat: 1.3258,
    lng: 103.7184,
    city: "Singapore",
    country: "SG",
    capacityMw: 50,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Digital Realty SIN12 - AI-ready Singapore facility under Digital Realty / Mitsubishi JV.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/apac/singapore",
        title: "Digital Realty Singapore",
        type: "operator",
      },
    ],
  },

  // --- QTS / Blackstone ---
  {
    slug: "qts-manassas-mn1",
    name: "QTS Manassas Mega Campus",
    operatorSlug: "qts",
    status: "expanding",
    aiDedicated: true,
    lat: 38.7509,
    lng: -77.4753,
    city: "Manassas",
    region: "VA",
    country: "US",
    capacityMw: 500,
    capacityMwPlanned: 1000,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "direct-to-chip",
    description:
      "QTS Manassas hyperscale/AI campus - one of the largest contiguous data center developments in PJM.",
    sources: [
      {
        url: "https://www.qtsdatacenters.com/data-centers/north-virginia",
        title: "QTS Northern Virginia",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/qts-blackstone-northern-virginia-expansion/",
        title: "QTS / Blackstone NoVA expansion",
        type: "news",
      },
    ],
  },
  {
    slug: "qts-irving-tx",
    name: "QTS Irving (DFW1)",
    operatorSlug: "qts",
    status: "operational",
    aiDedicated: true,
    lat: 32.8607,
    lng: -96.9709,
    city: "Irving",
    region: "TX",
    country: "US",
    capacityMw: 90,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description: "QTS Irving DFW1 facility hosting hyperscale AI tenants.",
    sources: [
      {
        url: "https://www.qtsdatacenters.com/data-centers/dallas",
        title: "QTS Dallas",
        type: "operator",
      },
    ],
  },
  {
    slug: "qts-hillsboro-or",
    name: "QTS Hillsboro",
    operatorSlug: "qts",
    status: "operational",
    aiDedicated: true,
    lat: 45.5229,
    lng: -122.989,
    city: "Hillsboro",
    region: "OR",
    country: "US",
    capacityMw: 120,
    primaryPowerSource: "hydro",
    coolingType: "direct-to-chip",
    description:
      "QTS Hillsboro - Pacific Northwest hyperscale AI hosting on hydro power.",
    sources: [
      {
        url: "https://www.qtsdatacenters.com/data-centers/hillsboro",
        title: "QTS Hillsboro",
        type: "operator",
      },
    ],
  },

  // --- Aligned ---
  {
    slug: "aligned-phx-01-phoenix",
    name: "Aligned PHX-01 Phoenix",
    operatorSlug: "aligned",
    status: "operational",
    aiDedicated: true,
    lat: 33.4484,
    lng: -112.074,
    city: "Phoenix",
    region: "AZ",
    country: "US",
    capacityMw: 60,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Aligned Phoenix campus with their Delta3 cooling supporting high-density AI deployments.",
    sources: [
      {
        url: "https://www.aligneddc.com/data-centers/phoenix",
        title: "Aligned Phoenix",
        type: "operator",
      },
    ],
  },
  {
    slug: "aligned-slc-01-salt-lake-city",
    name: "Aligned SLC-01 Salt Lake City",
    operatorSlug: "aligned",
    status: "operational",
    aiDedicated: true,
    lat: 40.7608,
    lng: -111.891,
    city: "West Jordan",
    region: "UT",
    country: "US",
    capacityMw: 36,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Aligned Salt Lake City facility designed for HPC/AI workloads.",
    sources: [
      {
        url: "https://www.aligneddc.com/data-centers/salt-lake-city",
        title: "Aligned SLC",
        type: "operator",
      },
    ],
  },
  {
    slug: "aligned-iad-02-ashburn",
    name: "Aligned IAD-02 Ashburn",
    operatorSlug: "aligned",
    status: "operational",
    aiDedicated: true,
    lat: 39.013,
    lng: -77.476,
    city: "Ashburn",
    region: "VA",
    country: "US",
    capacityMw: 96,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Aligned IAD-02 Ashburn campus - Macquarie-backed hyperscale AI hosting.",
    sources: [
      {
        url: "https://www.aligneddc.com/data-centers/ashburn",
        title: "Aligned Ashburn",
        type: "operator",
      },
    ],
  },

  // --- Switch ---
  {
    slug: "switch-citadel-tahoe-reno",
    name: "Switch Citadel Campus (Tahoe Reno)",
    operatorSlug: "switch",
    status: "expanding",
    aiDedicated: true,
    lat: 39.5848,
    lng: -119.4391,
    city: "Sparks",
    region: "NV",
    country: "US",
    capacityMw: 650,
    capacityMwPlanned: 7300,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Switch The Citadel - planned to be the largest data center campus in the world; hosts AI hyperscale tenants including Tesla and NVIDIA.",
    sources: [
      {
        url: "https://www.switch.com/the-citadel-campus/",
        title: "Switch The Citadel",
        type: "operator",
      },
    ],
  },
  {
    slug: "switch-pyramid-las-vegas",
    name: "Switch Las Vegas Pyramid Campus",
    operatorSlug: "switch",
    status: "operational",
    aiDedicated: false,
    lat: 36.0846,
    lng: -115.156,
    city: "Las Vegas",
    region: "NV",
    country: "US",
    capacityMw: 315,
    primaryPowerSource: "solar",
    coolingType: "air",
    description:
      "Switch Las Vegas Pyramid (LAS VEGAS 7,8,9,10,11,12) hyperscale colo campus.",
    sources: [
      {
        url: "https://www.switch.com/las-vegas-campus/",
        title: "Switch Las Vegas",
        type: "operator",
      },
    ],
  },
  {
    slug: "switch-keep-atlanta",
    name: "Switch The Keep Atlanta Campus",
    operatorSlug: "switch",
    status: "operational",
    aiDedicated: false,
    lat: 33.6342,
    lng: -84.4416,
    city: "Atlanta",
    region: "GA",
    country: "US",
    capacityMw: 130,
    primaryPowerSource: "grid-mixed",
    coolingType: "air",
    description: "Switch's Atlanta Keep campus serving Southeast US.",
    sources: [
      {
        url: "https://www.switch.com/the-keep-campus/",
        title: "Switch The Keep",
        type: "operator",
      },
    ],
  },

  // --- NextDC (Australia) ---
  {
    slug: "nextdc-s3-sydney",
    name: "NextDC S3 Sydney",
    operatorSlug: "nextdc",
    status: "operational",
    aiDedicated: true,
    lat: -33.8073,
    lng: 151.0186,
    city: "Sydney",
    country: "AU",
    capacityMw: 80,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "NextDC S3 Sydney - hyperscale AI hosting site in Macquarie Park.",
    sources: [
      {
        url: "https://www.nextdc.com/data-centres/s3-sydney-data-centre",
        title: "NextDC S3",
        type: "operator",
      },
    ],
  },
  {
    slug: "nextdc-m3-melbourne",
    name: "NextDC M3 Melbourne",
    operatorSlug: "nextdc",
    status: "under-construction",
    aiDedicated: true,
    lat: -37.7894,
    lng: 144.9576,
    city: "Melbourne",
    country: "AU",
    capacityMwPlanned: 150,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "NextDC M3 Melbourne - new flagship AI-ready hyperscale Australian site.",
    sources: [
      {
        url: "https://www.nextdc.com/data-centres/m3-melbourne-data-centre",
        title: "NextDC M3",
        type: "operator",
      },
    ],
  },

  // ========== (c) 2024-2026 MEGA-CAMPUSES ==========

  {
    slug: "stargate-uae-abu-dhabi",
    name: "Stargate UAE (G42 / Khazna Abu Dhabi)",
    operatorSlug: "g42",
    status: "under-construction",
    aiDedicated: true,
    lat: 24.4539,
    lng: 54.3773,
    city: "Abu Dhabi",
    country: "AE",
    capacityMwPlanned: 1000,
    primaryPowerSource: "hybrid",
    coolingType: "direct-to-chip",
    description:
      "Stargate UAE - 1GW first-phase AI campus by G42/Khazna in partnership with OpenAI, Oracle, NVIDIA, SoftBank, Cisco. Announced 2025.",
    sources: [
      {
        url: "https://openai.com/index/introducing-stargate-uae/",
        title: "Introducing Stargate UAE",
        type: "pr",
      },
      {
        url: "https://www.reuters.com/world/middle-east/openai-launch-data-center-uae-with-g42-2025-05-15/",
        title: "OpenAI launches data center in UAE with G42",
        type: "news",
      },
    ],
  },
  {
    slug: "meta-sarpy-county-ne",
    name: "Meta Sarpy County (Papillion)",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: true,
    lat: 41.1545,
    lng: -96.0418,
    city: "Papillion",
    region: "NE",
    country: "US",
    capacityMw: 600,
    capacityMwPlanned: 1000,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Meta's Sarpy County, Nebraska campus - expanded 2024-2025 with multiple new AI-ready buildings.",
    sources: [
      {
        url: "https://about.fb.com/news/2024/02/expanding-our-data-center-in-sarpy-county/",
        title: "Expanding our Sarpy County data center",
        type: "pr",
      },
    ],
  },
  {
    slug: "meta-kearney-ne",
    name: "Meta Kearney AI Campus",
    operatorSlug: "meta",
    status: "under-construction",
    aiDedicated: true,
    lat: 40.6991,
    lng: -99.0817,
    city: "Kearney",
    region: "NE",
    country: "US",
    capacityMwPlanned: 800,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description: "Meta's announced new Kearney, Nebraska AI campus.",
    sources: [
      {
        url: "https://about.fb.com/news/2024/04/kearney-data-center/",
        title: "Kearney data center announcement",
        type: "pr",
      },
    ],
  },
  {
    slug: "meta-temple-tx",
    name: "Meta Temple Texas",
    operatorSlug: "meta",
    status: "under-construction",
    aiDedicated: true,
    lat: 31.0982,
    lng: -97.3428,
    city: "Temple",
    region: "TX",
    country: "US",
    capacityMwPlanned: 700,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description: "Meta's Temple, Texas AI hyperscale campus, announced 2024.",
    sources: [
      {
        url: "https://about.fb.com/news/2024/03/temple-texas-data-center/",
        title: "Meta Temple announcement",
        type: "pr",
      },
    ],
  },
  {
    slug: "microsoft-cheyenne-wy",
    name: "Microsoft Cheyenne (AI expansion)",
    operatorSlug: "microsoft",
    status: "expanding",
    aiDedicated: true,
    lat: 41.1399,
    lng: -104.8202,
    city: "Cheyenne",
    region: "WY",
    country: "US",
    capacityMw: 250,
    capacityMwPlanned: 500,
    primaryPowerSource: "wind",
    coolingType: "direct-to-chip",
    description:
      "Microsoft's Cheyenne, Wyoming campus expanded with AI infrastructure phases.",
    sources: [
      {
        url: "https://news.microsoft.com/source/2024/05/22/microsoft-wyoming-investment/",
        title: "Microsoft Wyoming investment",
        type: "pr",
      },
    ],
  },
  {
    slug: "microsoft-quincy-wa",
    name: "Microsoft Quincy WA (AI expansion)",
    operatorSlug: "microsoft",
    status: "expanding",
    aiDedicated: true,
    lat: 47.2333,
    lng: -119.8526,
    city: "Quincy",
    region: "WA",
    country: "US",
    capacityMw: 600,
    capacityMwPlanned: 1200,
    primaryPowerSource: "hydro",
    coolingType: "direct-to-chip",
    description:
      "Microsoft Quincy, Washington campus, with continued AI capacity expansion.",
    sources: [
      {
        url: "https://news.microsoft.com/source/features/sustainability/quincy-data-center/",
        title: "Microsoft Quincy",
        type: "pr",
      },
    ],
  },
  {
    slug: "aws-anthropic-new-carlisle-in",
    name: "AWS Project Rainier - New Carlisle, IN",
    operatorSlug: "aws",
    status: "under-construction",
    aiDedicated: true,
    lat: 41.7042,
    lng: -86.5169,
    city: "New Carlisle",
    region: "IN",
    country: "US",
    capacityMwPlanned: 2200,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "aep-indiana-michigan-power",
    coolingType: "direct-to-chip",
    description:
      "Project Rainier - AWS / Anthropic Trainium2 mega-campus near New Carlisle, Indiana, with 30+ planned data centers.",
    sources: [
      {
        url: "https://www.aboutamazon.com/news/aws/aws-anthropic-project-rainier",
        title: "Project Rainier announcement",
        type: "pr",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/aws-anthropic-project-rainier-indiana/",
        title: "AWS Anthropic Project Rainier Indiana",
        type: "news",
      },
    ],
  },
  {
    slug: "aws-trainium-new-albany-oh",
    name: "AWS New Albany Trainium Campus",
    operatorSlug: "aws",
    status: "expanding",
    aiDedicated: true,
    lat: 40.0808,
    lng: -82.8088,
    city: "New Albany",
    region: "OH",
    country: "US",
    capacityMw: 400,
    capacityMwPlanned: 1000,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "AWS Ohio AI/Trainium hosting expansion - $10B+ committed under 2024-2025 expansion plans.",
    sources: [
      {
        url: "https://www.aboutamazon.com/news/aws/aws-ohio-data-center-investment",
        title: "AWS Ohio investment",
        type: "pr",
      },
    ],
  },
  {
    slug: "aws-trainium-boardman-or",
    name: "AWS Boardman / Umatilla Trainium Cluster",
    operatorSlug: "aws",
    status: "expanding",
    aiDedicated: true,
    lat: 45.8398,
    lng: -119.7006,
    city: "Boardman",
    region: "OR",
    country: "US",
    capacityMw: 550,
    capacityMwPlanned: 1000,
    primaryPowerSource: "hydro",
    coolingType: "direct-to-chip",
    description:
      "AWS Oregon (Umatilla/Morrow Counties) - large Trainium training footprint.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/sustainability/",
        title: "AWS Sustainability",
        type: "operator",
      },
    ],
  },
  {
    slug: "xai-colossus-2-memphis",
    name: "xAI Colossus 2 (Memphis Whitehaven)",
    operatorSlug: "xai",
    status: "under-construction",
    aiDedicated: true,
    lat: 35.0456,
    lng: -90.0364,
    city: "Memphis",
    region: "TN",
    country: "US",
    capacityMwPlanned: 1100,
    primaryPowerSource: "gas",
    coolingType: "direct-to-chip",
    description:
      "xAI Colossus 2 - second Memphis-area site (former Duke Energy industrial parcel) targeting 1+ million GPUs.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/xai-second-memphis-data-center/",
        title: "xAI second Memphis data center",
        type: "news",
      },
      { url: "https://x.ai/", title: "xAI", type: "operator" },
    ],
  },
  {
    slug: "humain-riyadh-sa",
    name: "HUMAIN Riyadh (PIF AI Campus)",
    operatorSlug: "humain",
    status: "under-construction",
    aiDedicated: true,
    lat: 24.7136,
    lng: 46.6753,
    city: "Riyadh",
    country: "SA",
    capacityMwPlanned: 1900,
    primaryPowerSource: "hybrid",
    coolingType: "direct-to-chip",
    description:
      "HUMAIN - Saudi PIF-backed AI national champion launched 2025; multi-GW campus plans with NVIDIA and AMD GPUs.",
    sources: [
      { url: "https://www.humain.ai/", title: "HUMAIN", type: "operator" },
      {
        url: "https://www.reuters.com/technology/artificial-intelligence/saudi-arabia-launches-humain-ai-company-2025-05-12/",
        title: "Saudi Arabia launches HUMAIN",
        type: "news",
      },
    ],
  },
  {
    slug: "humain-dammam-sa",
    name: "HUMAIN Dammam Campus",
    operatorSlug: "humain",
    status: "announced",
    aiDedicated: true,
    lat: 26.4207,
    lng: 50.0888,
    city: "Dammam",
    country: "SA",
    capacityMwPlanned: 500,
    primaryPowerSource: "hybrid",
    coolingType: "direct-to-chip",
    description:
      "HUMAIN's Eastern Province AI campus, in conjunction with NVIDIA and AMD partnerships announced 2025.",
    sources: [
      { url: "https://www.humain.ai/", title: "HUMAIN", type: "operator" },
    ],
  },
  {
    slug: "tract-storey-county-nv",
    name: "Tract Storey County NV Megasite",
    operatorSlug: "tract",
    status: "under-construction",
    aiDedicated: true,
    lat: 39.5371,
    lng: -119.4513,
    city: "Storey County",
    region: "NV",
    country: "US",
    capacityMwPlanned: 1500,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Tract's massive land bank development at TRI Center for AI hyperscale tenants.",
    sources: [
      { url: "https://www.tract.com/", title: "Tract", type: "operator" },
      {
        url: "https://www.datacenterdynamics.com/en/news/tract-tri-center-storey-county-data-center/",
        title: "Tract TRI Center Storey County",
        type: "news",
      },
    ],
  },
  {
    slug: "tract-buckeye-az",
    name: "Tract Buckeye AZ Megasite",
    operatorSlug: "tract",
    status: "announced",
    aiDedicated: true,
    lat: 33.3703,
    lng: -112.5838,
    city: "Buckeye",
    region: "AZ",
    country: "US",
    capacityMwPlanned: 1800,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Tract's Buckeye, Arizona land development for hyperscale AI tenants.",
    sources: [
      { url: "https://www.tract.com/", title: "Tract", type: "operator" },
    ],
  },
  {
    slug: "datavolt-neom-sa",
    name: "DataVolt NEOM Oxagon",
    operatorSlug: "datavolt",
    status: "under-construction",
    aiDedicated: true,
    lat: 28.0866,
    lng: 35.2167,
    city: "NEOM",
    country: "SA",
    capacityMwPlanned: 1500,
    primaryPowerSource: "solar",
    coolingType: "direct-to-chip",
    description:
      "DataVolt's net-zero AI campus inside Oxagon, NEOM - announced as 1.5GW renewable-powered AI infrastructure.",
    sources: [
      { url: "https://www.datavolt.com/", title: "DataVolt", type: "operator" },
      {
        url: "https://www.datacenterdynamics.com/en/news/datavolt-1-5gw-neom-oxagon-data-center/",
        title: "DataVolt NEOM data center",
        type: "news",
      },
    ],
  },
  {
    slug: "apollo-blackrock-mgx-ai-fund-site-1",
    name: "AI Infrastructure Partnership Site 1 (Apollo/MGX/BlackRock/Microsoft)",
    operatorSlug: "ai-infrastructure-partnership",
    status: "announced",
    aiDedicated: true,
    lat: 32.7767,
    lng: -96.797,
    region: "TX",
    country: "US",
    capacityMwPlanned: 1000,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Global AI Infrastructure Partnership ($30B+) initial Texas-region target for hyperscale AI buildout.",
    sources: [
      {
        url: "https://www.blackrock.com/corporate/newsroom/press-releases/article/corporate-one/press-releases/microsoft-blackrock-mgx-launch-ai-infrastructure",
        title: "BlackRock/MGX/Microsoft AI Infrastructure Partnership",
        type: "pr",
      },
    ],
  },
  {
    slug: "brookfield-france-ai-campus",
    name: "Brookfield France AI Campus",
    operatorSlug: "brookfield",
    status: "announced",
    aiDedicated: true,
    lat: 45.764,
    lng: 4.8357,
    city: "Cassis / Lyon Region",
    country: "FR",
    capacityMwPlanned: 1000,
    primaryPowerSource: "nuclear",
    coolingType: "direct-to-chip",
    description:
      "Brookfield's announced 20bn EUR France AI infrastructure pledge (2025), targeting nuclear-adjacent gigawatt campuses.",
    sources: [
      {
        url: "https://www.brookfield.com/news-insights/news/brookfield-invest-france-ai",
        title: "Brookfield France AI investment",
        type: "pr",
      },
      {
        url: "https://www.reuters.com/technology/brookfield-invest-20-billion-euros-france-ai-2025-02-10/",
        title: "Brookfield to invest 20bn EUR in France AI",
        type: "news",
      },
    ],
  },
  {
    slug: "kkr-energy-capital-ai-campus-tx",
    name: "KKR / Energy Capital Partners AI Campus",
    operatorSlug: "kkr-ecp",
    status: "announced",
    aiDedicated: true,
    lat: 32.5,
    lng: -97.0,
    region: "TX",
    country: "US",
    capacityMwPlanned: 1500,
    primaryPowerSource: "gas",
    coolingType: "direct-to-chip",
    description:
      "KKR / Energy Capital Partners $50B JV (announced 2025) targeting AI-ready power and data centers in PJM/ERCOT.",
    sources: [
      {
        url: "https://www.kkr.com/news/kkr-ecp-launch-50bn-data-center-power-partnership",
        title: "KKR/ECP $50bn data center power partnership",
        type: "pr",
      },
    ],
  },
  {
    slug: "stargate-abilene-phase3-tx",
    name: "Stargate Abilene Phase 3 (Lancium/Oracle expansion)",
    operatorSlug: "oracle",
    status: "announced",
    aiDedicated: true,
    lat: 32.4487,
    lng: -99.7331,
    city: "Abilene",
    region: "TX",
    country: "US",
    capacityMwPlanned: 1200,
    primaryPowerSource: "hybrid",
    coolingType: "direct-to-chip",
    description:
      "Stargate Abilene Phase 3 (additional buildings beyond initial Crusoe-built campus, supporting OpenAI/Oracle expansion to ~5GW).",
    sources: [
      {
        url: "https://openai.com/index/announcing-the-stargate-project/",
        title: "Stargate Project announcement",
        type: "pr",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/stargate-abilene-expansion-5gw/",
        title: "Stargate Abilene 5GW expansion",
        type: "news",
      },
    ],
  },
  {
    slug: "vantage-ashburn-va2",
    name: "Vantage Ashburn VA2 AI Campus",
    operatorSlug: "vantage",
    status: "expanding",
    aiDedicated: true,
    lat: 39.0098,
    lng: -77.4854,
    city: "Ashburn",
    region: "VA",
    country: "US",
    capacityMw: 192,
    capacityMwPlanned: 384,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Vantage Northern Virginia VA2 campus - DigitalBridge-backed AI hyperscale colo.",
    sources: [
      {
        url: "https://vantage-dc.com/data_center_locations/north-america/ashburn/",
        title: "Vantage Ashburn",
        type: "operator",
      },
    ],
  },
  {
    slug: "stack-infrastructure-new-albany-oh",
    name: "Stack Infrastructure New Albany OH AI Campus",
    operatorSlug: "stack-infrastructure",
    status: "under-construction",
    aiDedicated: true,
    lat: 40.0808,
    lng: -82.8088,
    city: "New Albany",
    region: "OH",
    country: "US",
    capacityMwPlanned: 240,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "Stack Infrastructure (IPI Partners) Ohio AI hosting campus - announced 2024.",
    sources: [
      {
        url: "https://www.stackinfra.com/data-centers/columbus/",
        title: "Stack Infrastructure Columbus",
        type: "operator",
      },
    ],
  },
];

// === NEW BRANDS NEEDED ===
export const AI_NATIVE_BRANDS: SeedBrand[] = [
  {
    slug: "coreweave",
    canonicalName: "CoreWeave",
    website: "https://www.coreweave.com",
  },
  { slug: "crusoe", canonicalName: "Crusoe", website: "https://crusoe.ai" },
  {
    slug: "lambda-labs",
    canonicalName: "Lambda Labs",
    website: "https://lambdalabs.com",
  },
  {
    slug: "together-ai",
    canonicalName: "Together AI",
    website: "https://www.together.ai",
  },
  {
    slug: "cerebras",
    canonicalName: "Cerebras Systems",
    website: "https://www.cerebras.net",
  },
  {
    slug: "voltage-park",
    canonicalName: "Voltage Park",
    website: "https://www.voltagepark.com",
  },
  { slug: "nebius", canonicalName: "Nebius", website: "https://nebius.com" },
  {
    slug: "applied-digital",
    canonicalName: "Applied Digital",
    website: "https://www.applieddigital.com",
  },
  {
    slug: "iren",
    canonicalName: "IREN (Iris Energy)",
    website: "https://iren.com",
  },
  { slug: "hut-8", canonicalName: "Hut 8", website: "https://hut8.com" },
  {
    slug: "galaxy-digital",
    canonicalName: "Galaxy Digital",
    website: "https://www.galaxy.com",
  },
  {
    slug: "terawulf",
    canonicalName: "TeraWulf",
    website: "https://www.terawulf.com",
  },
  {
    slug: "riot-platforms",
    canonicalName: "Riot Platforms",
    website: "https://www.riotplatforms.com",
  },
  {
    slug: "cipher-mining",
    canonicalName: "Cipher Mining",
    website: "https://www.ciphermining.com",
  },
  {
    slug: "bitfarms",
    canonicalName: "Bitfarms",
    website: "https://bitfarms.com",
  },
  {
    slug: "equinix",
    canonicalName: "Equinix",
    website: "https://www.equinix.com",
  },
  {
    slug: "digital-realty",
    canonicalName: "Digital Realty",
    website: "https://www.digitalrealty.com",
  },
  {
    slug: "qts",
    canonicalName: "QTS Data Centers",
    website: "https://www.qtsdatacenters.com",
  },
  {
    slug: "aligned",
    canonicalName: "Aligned Data Centers",
    website: "https://www.aligneddc.com",
  },
  {
    slug: "switch",
    canonicalName: "Switch",
    website: "https://www.switch.com",
  },
  {
    slug: "nextdc",
    canonicalName: "NextDC",
    website: "https://www.nextdc.com",
  },
  { slug: "g42", canonicalName: "G42", website: "https://www.g42.ai" },
  { slug: "humain", canonicalName: "HUMAIN", website: "https://www.humain.ai" },
  { slug: "tract", canonicalName: "Tract", website: "https://www.tract.com" },
  {
    slug: "datavolt",
    canonicalName: "DataVolt",
    website: "https://www.datavolt.com",
  },
  {
    slug: "ai-infrastructure-partnership",
    canonicalName: "AI Infrastructure Partnership",
    website: "https://www.blackrock.com",
  },
  {
    slug: "brookfield",
    canonicalName: "Brookfield",
    website: "https://www.brookfield.com",
  },
  {
    slug: "kkr-ecp",
    canonicalName: "KKR / Energy Capital Partners",
    website: "https://www.kkr.com",
  },
  {
    slug: "vantage",
    canonicalName: "Vantage Data Centers",
    website: "https://vantage-dc.com",
  },
  {
    slug: "stack-infrastructure",
    canonicalName: "Stack Infrastructure",
    website: "https://www.stackinfra.com",
  },
  { slug: "meta", canonicalName: "Meta", website: "https://about.meta.com" },
  {
    slug: "microsoft",
    canonicalName: "Microsoft",
    website: "https://www.microsoft.com",
  },
  {
    slug: "aws",
    canonicalName: "Amazon Web Services",
    website: "https://aws.amazon.com",
  },
  { slug: "xai", canonicalName: "xAI", website: "https://x.ai" },
  {
    slug: "oracle",
    canonicalName: "Oracle",
    website: "https://www.oracle.com",
  },
];
