import type { SeedDatacenter, SeedBrand } from "./types";

// === APAC + ME + AFRICA + LATAM ===
export const APAC_ME_AF_LATAM: SeedDatacenter[] = [
  // ===== SINGAPORE =====
  {
    slug: "aws-ap-southeast-1-singapore",
    name: "AWS Asia Pacific (Singapore) - ap-southeast-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 1.3521,
    lng: 103.8198,
    city: "Singapore",
    country: "SG",
    coolingType: "air",
    description:
      "AWS Singapore region (ap-southeast-1), one of AWS's earliest APAC regions, launched in 2010.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure Regions & AZs",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-southeast-asia-singapore",
    name: "Microsoft Azure Southeast Asia (Singapore)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 1.3521,
    lng: 103.8198,
    city: "Singapore",
    country: "SG",
    description:
      "Microsoft Azure Southeast Asia region based in Singapore, launched 2010.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        title: "Azure regions list",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-singapore-jurong-west",
    name: "Google Cloud Singapore (Jurong West)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 1.3404,
    lng: 103.709,
    city: "Singapore",
    region: "Jurong West",
    country: "SG",
    description:
      "Google's Jurong West data center campus, part of Google Cloud asia-southeast1 region.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/",
        title: "Google Data Center Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-sg1-singapore",
    name: "Equinix SG1 Singapore",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 1.33,
    lng: 103.7436,
    city: "Singapore",
    country: "SG",
    description:
      "Equinix's flagship Singapore IBX, part of the SG1-SG5 campus serving as a major SE Asia interconnection hub.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/asia-pacific-colocation/singapore-colocation/singapore-data-centers",
        title: "Equinix Singapore Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "stt-singapore-defu",
    name: "ST Telemedia Defu 1 (Singapore)",
    operatorSlug: "stt-gdc",
    status: "operational",
    aiDedicated: false,
    lat: 1.3651,
    lng: 103.8849,
    city: "Singapore",
    region: "Defu",
    country: "SG",
    capacityMw: 33,
    description:
      "ST Telemedia Global Data Centres Defu 1 facility in Singapore.",
    sources: [
      {
        url: "https://www.sttelemediagdc.com/our-data-centres/singapore",
        title: "STT GDC Singapore",
        type: "operator",
      },
    ],
  },
  // ===== JAPAN =====
  {
    slug: "aws-ap-northeast-1-tokyo",
    name: "AWS Asia Pacific (Tokyo) - ap-northeast-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 35.6762,
    lng: 139.6503,
    city: "Tokyo",
    country: "JP",
    description: "AWS Tokyo region launched 2011, AWS's first Japan region.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-ap-northeast-3-osaka",
    name: "AWS Asia Pacific (Osaka) - ap-northeast-3",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 34.6937,
    lng: 135.5023,
    city: "Osaka",
    country: "JP",
    description:
      "AWS Osaka region (ap-northeast-3), upgraded to a full region in 2021.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-japan-east-tokyo",
    name: "Microsoft Azure Japan East (Tokyo)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 35.6762,
    lng: 139.6503,
    city: "Tokyo",
    country: "JP",
    description:
      "Azure Japan East region in Tokyo area. Microsoft announced a $2.9B Japan expansion in 2024 focused on AI capacity.",
    sources: [
      {
        url: "https://news.microsoft.com/apac/2024/04/09/microsoft-announces-2-9-billion-investment-in-hyperscale-cloud-computing-and-ai-infrastructure-in-japan/",
        type: "pr",
      },
    ],
  },
  {
    slug: "azure-japan-west-osaka",
    name: "Microsoft Azure Japan West (Osaka)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 34.6937,
    lng: 135.5023,
    city: "Osaka",
    country: "JP",
    description:
      "Azure Japan West region in Osaka, providing in-country pair to Japan East.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-asia-northeast1-tokyo",
    name: "Google Cloud Tokyo (asia-northeast1)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 35.6762,
    lng: 139.6503,
    city: "Tokyo",
    country: "JP",
    description: "Google Cloud asia-northeast1 region in Tokyo.",
    sources: [
      {
        url: "https://cloud.google.com/about/locations",
        title: "Google Cloud Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ty11-tokyo",
    name: "Equinix TY11 Tokyo",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 35.6762,
    lng: 139.6503,
    city: "Tokyo",
    country: "JP",
    description:
      "Equinix TY11 IBX in Tokyo, part of Equinix's 14+ Japan facility footprint.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/asia-pacific-colocation/japan-colocation/tokyo-data-centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "ntt-tokyo-1",
    name: "NTT Tokyo 1 Data Center",
    operatorSlug: "ntt",
    status: "operational",
    aiDedicated: false,
    lat: 35.6762,
    lng: 139.6503,
    city: "Tokyo",
    country: "JP",
    description:
      "NTT Global Data Centers Tokyo 1, part of NTT's flagship Japan campus.",
    sources: [
      {
        url: "https://services.global.ntt/en-us/services-and-products/data-centers/japan",
        title: "NTT Japan Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "softbank-keihanna-ai",
    name: "SoftBank Keihanna AI Data Center",
    operatorSlug: "softbank",
    status: "under-construction",
    aiDedicated: true,
    lat: 34.7384,
    lng: 135.774,
    city: "Keihanna",
    region: "Kyoto",
    country: "JP",
    capacityMwPlanned: 150,
    description:
      "SoftBank's AI-dedicated data center in Keihanna Science City. Planned for NVIDIA GPU clusters.",
    sources: [
      {
        url: "https://group.softbank/en/news/press/20240918",
        title: "SoftBank AI infrastructure announcement",
        type: "pr",
      },
    ],
  },
  {
    slug: "kddi-telehouse-tokyo-tk2",
    name: "KDDI Telehouse Tokyo TK2",
    operatorSlug: "kddi",
    status: "operational",
    aiDedicated: false,
    lat: 35.6762,
    lng: 139.7553,
    city: "Tokyo",
    country: "JP",
    description:
      "KDDI's Telehouse Tokyo TK2 data center, part of the global Telehouse network.",
    sources: [
      {
        url: "https://www.telehouse.net/data-centres/asia/japan/tokyo/",
        title: "Telehouse Tokyo",
        type: "operator",
      },
    ],
  },
  // ===== KOREA =====
  {
    slug: "aws-ap-northeast-2-seoul",
    name: "AWS Asia Pacific (Seoul) - ap-northeast-2",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 37.5665,
    lng: 126.978,
    city: "Seoul",
    country: "KR",
    description:
      "AWS Seoul region launched 2016. AWS announced $5.88B Korea infrastructure investment through 2027.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-korea-central-seoul",
    name: "Microsoft Azure Korea Central (Seoul)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 37.5665,
    lng: 126.978,
    city: "Seoul",
    country: "KR",
    description: "Azure Korea Central region in Seoul, launched 2017.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "naver-sejong-gak",
    name: "Naver Data Center GAK Sejong",
    operatorSlug: "naver",
    status: "operational",
    aiDedicated: true,
    lat: 36.48,
    lng: 127.289,
    city: "Sejong",
    country: "KR",
    capacityMw: 270,
    description:
      "Naver's GAK Sejong, opened November 2023. Korea's largest hyperscale data center, designed to host hundreds of thousands of servers including AI workloads for HyperCLOVA X.",
    sources: [
      {
        url: "https://www.navercorp.com/en/promotion/datacentersGakSejong",
        title: "Naver GAK Sejong",
        type: "operator",
      },
    ],
  },
  // ===== INDIA =====
  {
    slug: "aws-ap-south-1-mumbai",
    name: "AWS Asia Pacific (Mumbai) - ap-south-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 19.076,
    lng: 72.8777,
    city: "Mumbai",
    country: "IN",
    description: "AWS Mumbai region launched 2016.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-ap-south-2-hyderabad",
    name: "AWS Asia Pacific (Hyderabad) - ap-south-2",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 17.385,
    lng: 78.4867,
    city: "Hyderabad",
    country: "IN",
    description: "AWS Hyderabad region (ap-south-2) launched 2022.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-india-central-pune",
    name: "Microsoft Azure Central India (Pune)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 18.5204,
    lng: 73.8567,
    city: "Pune",
    country: "IN",
    description: "Azure Central India region in Pune, launched 2015.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-india-south-chennai",
    name: "Microsoft Azure South India (Chennai)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 13.0827,
    lng: 80.2707,
    city: "Chennai",
    country: "IN",
    description: "Azure South India region in Chennai.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "yotta-shakti-hyderabad",
    name: "Yotta Shakti Hyderabad NM1",
    operatorSlug: "yotta",
    status: "operational",
    aiDedicated: true,
    lat: 17.4239,
    lng: 78.4738,
    city: "Hyderabad",
    country: "IN",
    capacityMwPlanned: 300,
    description:
      "Yotta Data Services' Shakti AI cloud infrastructure with 16,000+ NVIDIA H100 GPUs.",
    sources: [
      {
        url: "https://www.yotta.com/data-center/hyderabad/",
        title: "Yotta Hyderabad",
        type: "operator",
      },
    ],
  },
  {
    slug: "ctrls-hyderabad-dc1",
    name: "CtrlS Hyderabad DC1",
    operatorSlug: "ctrls",
    status: "operational",
    aiDedicated: false,
    lat: 17.4516,
    lng: 78.3849,
    city: "Hyderabad",
    country: "IN",
    description:
      "CtrlS Datacenters Hyderabad campus, India's largest domestic Tier-IV data center operator.",
    sources: [
      {
        url: "https://www.ctrls.in/data-centers/hyderabad/",
        title: "CtrlS Hyderabad",
        type: "operator",
      },
    ],
  },
  {
    slug: "reliance-jio-jamnagar-ai",
    name: "Reliance Jio AI Data Center Jamnagar",
    operatorSlug: "reliance-jio",
    status: "announced",
    aiDedicated: true,
    lat: 22.4707,
    lng: 70.0577,
    city: "Jamnagar",
    region: "Gujarat",
    country: "IN",
    capacityMwPlanned: 1000,
    primaryPowerSource: "hybrid",
    description:
      "Reliance Jio's planned 1 GW AI data center in Jamnagar, Gujarat, partnered with NVIDIA.",
    sources: [
      {
        url: "https://www.reuters.com/technology/artificial-intelligence/india-reliance-build-ai-infrastructure-with-nvidia-2024-10-29/",
        type: "news",
      },
    ],
  },
  {
    slug: "adaniconnex-mumbai-mu1",
    name: "AdaniConneX Mumbai MU1",
    operatorSlug: "adaniconnex",
    status: "operational",
    aiDedicated: false,
    lat: 19.076,
    lng: 72.8777,
    city: "Mumbai",
    country: "IN",
    description: "AdaniConneX (Adani-EdgeConneX JV) Mumbai data center campus.",
    sources: [
      {
        url: "https://www.adaniconnex.com/",
        title: "AdaniConneX",
        type: "operator",
      },
    ],
  },
  // ===== AUSTRALIA =====
  {
    slug: "aws-ap-southeast-2-sydney",
    name: "AWS Asia Pacific (Sydney) - ap-southeast-2",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: -33.8688,
    lng: 151.2093,
    city: "Sydney",
    country: "AU",
    description: "AWS Sydney region launched 2012.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-ap-southeast-4-melbourne",
    name: "AWS Asia Pacific (Melbourne) - ap-southeast-4",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: -37.8136,
    lng: 144.9631,
    city: "Melbourne",
    country: "AU",
    description: "AWS Melbourne region (ap-southeast-4) launched 2023.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-australia-east-sydney",
    name: "Microsoft Azure Australia East (Sydney)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: -33.8688,
    lng: 151.2093,
    city: "Sydney",
    country: "AU",
    description: "Azure Australia East region in Sydney.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "nextdc-s3-sydney",
    name: "NextDC S3 Sydney",
    operatorSlug: "nextdc",
    status: "operational",
    aiDedicated: false,
    lat: -33.7486,
    lng: 150.9181,
    city: "Sydney",
    region: "Western Sydney",
    country: "AU",
    capacityMwPlanned: 80,
    description:
      "NextDC S3 hyperscale facility in Western Sydney, designed for AI/ML workloads.",
    sources: [
      {
        url: "https://www.nextdc.com/data-centres/s3-sydney-data-centre",
        title: "NextDC S3",
        type: "operator",
      },
    ],
  },
  {
    slug: "nextdc-m2-melbourne",
    name: "NextDC M2 Melbourne",
    operatorSlug: "nextdc",
    status: "operational",
    aiDedicated: false,
    lat: -37.8136,
    lng: 144.9631,
    city: "Melbourne",
    country: "AU",
    description: "NextDC M2 Tullamarine, Melbourne.",
    sources: [
      {
        url: "https://www.nextdc.com/data-centres/m2-melbourne-data-centre",
        title: "NextDC M2",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-sy5-sydney",
    name: "Equinix SY5 Sydney",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: -33.8688,
    lng: 151.2093,
    city: "Sydney",
    country: "AU",
    description: "Equinix SY5 IBX in Sydney.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/asia-pacific-colocation/australia-colocation/sydney-data-centers",
        type: "operator",
      },
    ],
  },
  // ===== GREATER CHINA =====
  {
    slug: "alibaba-hangzhou-feitian",
    name: "Alibaba Cloud Hangzhou Feitian",
    operatorSlug: "alibaba-cloud",
    status: "operational",
    aiDedicated: false,
    lat: 30.2741,
    lng: 120.1551,
    city: "Hangzhou",
    region: "Zhejiang",
    country: "CN",
    description:
      "Alibaba Cloud's flagship Hangzhou data center running the Apsara/Feitian distributed OS.",
    sources: [
      {
        url: "https://www.alibabacloud.com/global-locations",
        title: "Alibaba Cloud Global Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "tencent-shenzhen-cloud",
    name: "Tencent Cloud Shenzhen",
    operatorSlug: "tencent-cloud",
    status: "operational",
    aiDedicated: false,
    lat: 22.5431,
    lng: 114.0579,
    city: "Shenzhen",
    region: "Guangdong",
    country: "CN",
    description: "Tencent Cloud's Shenzhen region.",
    sources: [
      {
        url: "https://www.tencentcloud.com/about/regions",
        title: "Tencent Cloud Regions",
        type: "operator",
      },
    ],
  },
  {
    slug: "baidu-yangquan",
    name: "Baidu Cloud Yangquan",
    operatorSlug: "baidu-cloud",
    status: "operational",
    aiDedicated: true,
    lat: 37.8576,
    lng: 113.5763,
    city: "Yangquan",
    region: "Shanxi",
    country: "CN",
    description:
      "Baidu's Yangquan AI cloud computing center, hosting Baidu's ERNIE LLM training infrastructure.",
    sources: [
      {
        url: "https://cloud.baidu.com/",
        title: "Baidu Cloud",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-china-north-2-21vianet",
    name: "Azure China North 2 (Beijing) - 21Vianet",
    operatorSlug: "21vianet",
    status: "operational",
    aiDedicated: false,
    lat: 39.9042,
    lng: 116.4074,
    city: "Beijing",
    country: "CN",
    description:
      "Microsoft Azure China region North 2, operated by 21Vianet under Chinese regulations.",
    sources: [
      {
        url: "https://docs.azure.cn/en-us/articles/azure-operations-china",
        title: "Azure China operated by 21Vianet",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-cn-northwest-1-ningxia",
    name: "AWS China (Ningxia) - cn-northwest-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 38.4872,
    lng: 106.2309,
    city: "Yinchuan",
    region: "Ningxia",
    country: "CN",
    description: "AWS China Ningxia region, operated by NWCD partner.",
    sources: [
      {
        url: "https://www.amazonaws.cn/en/about-aws/china/",
        title: "AWS China",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-hk1-hong-kong",
    name: "Equinix HK1 Hong Kong",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 22.3193,
    lng: 114.1694,
    city: "Hong Kong",
    country: "HK",
    description: "Equinix HK1 IBX in Hong Kong.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/asia-pacific-colocation/hong-kong-colocation/hong-kong-data-centers",
        type: "operator",
      },
    ],
  },
  // ===== SOUTHEAST ASIA =====
  {
    slug: "aws-ap-southeast-3-jakarta",
    name: "AWS Asia Pacific (Jakarta) - ap-southeast-3",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: -6.2088,
    lng: 106.8456,
    city: "Jakarta",
    country: "ID",
    description: "AWS Jakarta region launched 2021.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-indonesia-central-jakarta",
    name: "Microsoft Azure Indonesia Central (Jakarta)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: -6.2088,
    lng: 106.8456,
    city: "Jakarta",
    country: "ID",
    description:
      "Azure Indonesia Central region opened 2024. Microsoft announced $1.7B Indonesia AI/cloud investment.",
    sources: [
      {
        url: "https://news.microsoft.com/source/asia/2024/04/30/microsoft-announces-us1-7-billion-investment-to-advance-indonesias-cloud-and-ai-ambitions/",
        type: "pr",
      },
    ],
  },
  {
    slug: "aws-ap-southeast-5-malaysia",
    name: "AWS Asia Pacific (Malaysia) - ap-southeast-5",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 3.139,
    lng: 101.6869,
    city: "Kuala Lumpur",
    country: "MY",
    description:
      "AWS Malaysia region launched August 2024. AWS plans $6.2B Malaysia investment by 2038.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "bridge-data-centres-mr1-johor",
    name: "Bridge Data Centres MY06 Johor",
    operatorSlug: "bridge-data-centres",
    status: "under-construction",
    aiDedicated: true,
    lat: 1.4927,
    lng: 103.7414,
    city: "Johor Bahru",
    region: "Johor",
    country: "MY",
    capacityMwPlanned: 200,
    description:
      "Bridge Data Centres campus in Sedenak Tech Park, Johor. Part of the Johor hyperscale cluster driven by AI demand.",
    sources: [
      {
        url: "https://www.bridgedatacentres.com/locations/malaysia/",
        title: "Bridge Data Centres Malaysia",
        type: "operator",
      },
    ],
  },
  {
    slug: "ytl-yondr-johor-kulai",
    name: "YTL Green Data Center Park Kulai",
    operatorSlug: "ytl",
    status: "under-construction",
    aiDedicated: true,
    lat: 1.6601,
    lng: 103.6056,
    city: "Kulai",
    region: "Johor",
    country: "MY",
    capacityMwPlanned: 500,
    primaryPowerSource: "solar",
    description:
      "YTL's 500 MW green data center park in Kulai, Johor, partnered with NVIDIA for sovereign AI cloud.",
    sources: [
      {
        url: "https://nvidianews.nvidia.com/news/nvidia-and-ytl-power-international-to-build-malaysias-largest-ai-supercomputer",
        type: "pr",
      },
    ],
  },
  // ===== MIDDLE EAST =====
  {
    slug: "g42-stargate-uae-abu-dhabi",
    name: "G42 / OpenAI Stargate UAE Abu Dhabi",
    operatorSlug: "g42",
    status: "announced",
    aiDedicated: true,
    lat: 24.4539,
    lng: 54.3773,
    city: "Abu Dhabi",
    country: "AE",
    capacityMwPlanned: 1000,
    primaryPowerSource: "hybrid",
    description:
      "Stargate UAE - 1 GW AI data center campus announced May 2025 between G42, OpenAI, Oracle, NVIDIA, Cisco, and SoftBank.",
    sources: [
      {
        url: "https://openai.com/index/introducing-stargate-uae/",
        title: "Introducing Stargate UAE",
        type: "pr",
      },
    ],
  },
  {
    slug: "khazna-abu-dhabi-ad1",
    name: "Khazna Abu Dhabi AD1",
    operatorSlug: "khazna",
    status: "operational",
    aiDedicated: false,
    lat: 24.4539,
    lng: 54.3773,
    city: "Abu Dhabi",
    country: "AE",
    description:
      "Khazna Data Centers AD1, UAE's largest wholesale operator and key Stargate UAE partner via G42.",
    sources: [
      {
        url: "https://www.khazna.ae/",
        title: "Khazna Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-me-south-1-bahrain",
    name: "AWS Middle East (Bahrain) - me-south-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 26.0667,
    lng: 50.5577,
    city: "Manama",
    country: "BH",
    description:
      "AWS Bahrain region launched 2019, AWS's first Middle East region.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-uae-north-dubai",
    name: "Microsoft Azure UAE North (Dubai)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 25.2048,
    lng: 55.2708,
    city: "Dubai",
    country: "AE",
    description:
      "Azure UAE North region in Dubai. Microsoft invested $1.5B in G42 in 2024 for AI/cloud collaboration.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "humain-saudi-riyadh",
    name: "HUMAIN AI Data Center Riyadh",
    operatorSlug: "humain",
    status: "announced",
    aiDedicated: true,
    lat: 24.7136,
    lng: 46.6753,
    city: "Riyadh",
    country: "SA",
    capacityMwPlanned: 1900,
    description:
      "HUMAIN, Saudi Arabia's PIF-backed AI champion. Plans up to 1.9 GW of AI data center capacity by 2030.",
    sources: [
      { url: "https://www.humain.ai/", title: "HUMAIN", type: "operator" },
    ],
  },
  {
    slug: "oracle-me-jeddah",
    name: "Oracle Cloud Saudi Arabia (Jeddah)",
    operatorSlug: "oracle",
    status: "operational",
    aiDedicated: false,
    lat: 21.4858,
    lng: 39.1925,
    city: "Jeddah",
    country: "SA",
    description: "Oracle Cloud Infrastructure region in Jeddah.",
    sources: [
      {
        url: "https://www.oracle.com/cloud/public-cloud-regions/",
        title: "OCI Public Cloud Regions",
        type: "operator",
      },
    ],
  },
  // ===== LATAM =====
  {
    slug: "aws-sa-east-1-sao-paulo",
    name: "AWS South America (São Paulo) - sa-east-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: -23.5505,
    lng: -46.6333,
    city: "São Paulo",
    country: "BR",
    description:
      "AWS São Paulo region (sa-east-1), AWS's primary LATAM region launched 2011.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-brazil-south-sao-paulo",
    name: "Microsoft Azure Brazil South (São Paulo)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: -23.5505,
    lng: -46.6333,
    city: "São Paulo",
    country: "BR",
    description: "Azure Brazil South region in São Paulo.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-mexico-central-queretaro",
    name: "Microsoft Azure Mexico Central (Querétaro)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 20.5888,
    lng: -100.3899,
    city: "Querétaro",
    country: "MX",
    description: "Azure Mexico Central region in Querétaro launched 2024.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "ascenty-sao-paulo-spo1",
    name: "Ascenty São Paulo SP1",
    operatorSlug: "ascenty",
    status: "operational",
    aiDedicated: false,
    lat: -23.4608,
    lng: -46.5328,
    city: "São Paulo",
    country: "BR",
    description:
      "Ascenty (Digital Realty/Brookfield JV) São Paulo SP1, LATAM's largest data center operator.",
    sources: [
      {
        url: "https://www.ascenty.com/en/data-centers/",
        title: "Ascenty Data Centers",
        type: "operator",
      },
    ],
  },
  // ===== AFRICA =====
  {
    slug: "aws-af-south-1-cape-town",
    name: "AWS Africa (Cape Town) - af-south-1",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: -33.9249,
    lng: 18.4241,
    city: "Cape Town",
    country: "ZA",
    description:
      "AWS Cape Town region launched 2020, AWS's first Africa region.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-south-africa-north-johannesburg",
    name: "Microsoft Azure South Africa North (Johannesburg)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: -26.2041,
    lng: 28.0473,
    city: "Johannesburg",
    country: "ZA",
    description:
      "Azure South Africa North region in Johannesburg, launched 2019.",
    sources: [
      {
        url: "https://learn.microsoft.com/en-us/azure/reliability/regions-list",
        type: "operator",
      },
    ],
  },
  {
    slug: "teraco-jb1-johannesburg",
    name: "Teraco JB1 Johannesburg",
    operatorSlug: "teraco",
    status: "operational",
    aiDedicated: false,
    lat: -26.1077,
    lng: 28.0567,
    city: "Johannesburg",
    region: "Isando",
    country: "ZA",
    description:
      "Teraco JB1 in Isando, Johannesburg - Africa's largest carrier-neutral interconnection facility.",
    sources: [
      {
        url: "https://www.teraco.co.za/data-centres/johannesburg/",
        title: "Teraco Johannesburg",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-lg1-lagos",
    name: "Equinix LG1 Lagos",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 6.4541,
    lng: 3.3947,
    city: "Lagos",
    country: "NG",
    description:
      "Equinix LG1 Lagos (formerly MainOne), West Africa's premier interconnection hub.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/nigeria-colocation/lagos-data-centers",
        title: "Equinix Lagos",
        type: "operator",
      },
    ],
  },
];

export const APAC_BRANDS: SeedBrand[] = [
  {
    slug: "stt-gdc",
    canonicalName: "ST Telemedia Global Data Centres",
    website: "https://www.sttelemediagdc.com",
  },
  {
    slug: "softbank",
    canonicalName: "SoftBank",
    website: "https://group.softbank",
  },
  {
    slug: "kddi",
    canonicalName: "KDDI / Telehouse",
    website: "https://www.telehouse.net",
  },
  {
    slug: "naver",
    canonicalName: "Naver",
    website: "https://www.navercorp.com",
  },
  {
    slug: "yotta",
    canonicalName: "Yotta Data Services",
    website: "https://www.yotta.com",
  },
  {
    slug: "ctrls",
    canonicalName: "CtrlS Datacenters",
    website: "https://www.ctrls.in",
  },
  {
    slug: "reliance-jio",
    canonicalName: "Reliance Jio",
    website: "https://www.jio.com",
  },
  {
    slug: "adaniconnex",
    canonicalName: "AdaniConneX",
    website: "https://www.adaniconnex.com",
  },
  {
    slug: "nextdc",
    canonicalName: "NextDC",
    website: "https://www.nextdc.com",
  },
  {
    slug: "alibaba-cloud",
    canonicalName: "Alibaba Cloud",
    website: "https://www.alibabacloud.com",
  },
  {
    slug: "tencent-cloud",
    canonicalName: "Tencent Cloud",
    website: "https://www.tencentcloud.com",
  },
  {
    slug: "baidu-cloud",
    canonicalName: "Baidu Cloud",
    website: "https://cloud.baidu.com",
  },
  {
    slug: "21vianet",
    canonicalName: "21Vianet",
    website: "https://www.21vianet.com",
  },
  {
    slug: "bridge-data-centres",
    canonicalName: "Bridge Data Centres",
    website: "https://www.bridgedatacentres.com",
  },
  {
    slug: "ytl",
    canonicalName: "YTL Corporation",
    website: "https://www.ytl.com",
  },
  { slug: "g42", canonicalName: "G42", website: "https://www.g42.ai" },
  {
    slug: "khazna",
    canonicalName: "Khazna Data Centers",
    website: "https://www.khazna.ae",
  },
  { slug: "humain", canonicalName: "HUMAIN", website: "https://www.humain.ai" },
  {
    slug: "ascenty",
    canonicalName: "Ascenty",
    website: "https://www.ascenty.com",
  },
  {
    slug: "teraco",
    canonicalName: "Teraco Data Environments",
    website: "https://www.teraco.co.za",
  },
];
