import type { SeedDatacenter, SeedBrand } from "./types";

// === EUROPE ===
export const EUROPE: SeedDatacenter[] = [
  // ===== DUBLIN / IRELAND CLUSTER =====
  {
    slug: "aws-dub1-dublin",
    name: "AWS DUB1 Dublin",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 53.3498,
    lng: -6.2603,
    city: "Dublin",
    country: "IE",
    description: "AWS eu-west-1 region availability zone in Dublin metro.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
      {
        url: "https://en.wikipedia.org/wiki/List_of_Amazon_Web_Services_data_centers",
        title: "List of AWS data centers",
        type: "other",
      },
    ],
  },
  {
    slug: "aws-dub2-dublin",
    name: "AWS DUB2 Dublin",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 53.4239,
    lng: -6.4082,
    city: "Dublin",
    country: "IE",
    description: "Second AWS eu-west-1 availability zone facility in Dublin.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-grange-castle-dublin",
    name: "Microsoft Azure Grange Castle (Dublin)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 53.3197,
    lng: -6.4419,
    city: "Clondalkin",
    region: "Dublin",
    country: "IE",
    capacityMw: 170,
    primaryPowerSource: "grid-mixed",
    coolingType: "closed-loop",
    description:
      "Microsoft North Europe region campus at Grange Castle Business Park.",
    sources: [
      {
        url: "https://news.microsoft.com/source/emea/features/microsoft-completes-major-grange-castle-campus-expansion/",
        title: "Microsoft Grange Castle expansion",
        type: "pr",
      },
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-clonshaugh-dublin",
    name: "Microsoft Azure Clonshaugh (DUB10)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 53.3939,
    lng: -6.2048,
    city: "Clonshaugh",
    region: "Dublin",
    country: "IE",
    capacityMw: 72,
    primaryPowerSource: "grid-mixed",
    description:
      "Microsoft Azure North Europe data center at Clonshaugh Industrial Estate.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/microsoft-acquires-29-acre-site-in-dublin-for-data-center-development/",
        title: "Microsoft Clonshaugh expansion",
        type: "news",
      },
    ],
  },
  {
    slug: "google-dublin-grange-castle",
    name: "Google Dublin (Grange Castle)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 53.3203,
    lng: -6.4361,
    city: "Clondalkin",
    region: "Dublin",
    country: "IE",
    capacityMw: 72,
    primaryPowerSource: "grid-mixed",
    description:
      "Google Cloud europe-west1 region datacenter campus in Profile Park / Grange Castle.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/dublin/",
        title: "Google Dublin",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-clonee",
    name: "Meta Clonee Data Center",
    operatorSlug: "meta",
    status: "operational",
    aiDedicated: false,
    lat: 53.4084,
    lng: -6.4264,
    city: "Clonee",
    region: "Meath",
    country: "IE",
    capacityMw: 114,
    primaryPowerSource: "wind",
    coolingType: "air",
    description:
      "Meta's hyperscale data center in Clonee, powered by 100% renewable energy.",
    sources: [
      {
        url: "https://datacenters.atmeta.com/clonee/",
        title: "Meta Clonee Data Center",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-db1-dublin",
    name: "Equinix DB1 Dublin",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 53.3431,
    lng: -6.2489,
    city: "Dublin",
    country: "IE",
    description: "Equinix carrier-neutral colocation in Citywest, Dublin.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/ireland-colocation/dublin-data-centers/db1",
        title: "Equinix DB1",
        type: "operator",
      },
    ],
  },
  {
    slug: "digital-realty-profile-park-dub11",
    name: "Digital Realty Profile Park (DUB11)",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: false,
    lat: 53.3206,
    lng: -6.4339,
    city: "Clondalkin",
    region: "Dublin",
    country: "IE",
    capacityMw: 24,
    description: "Digital Realty hyperscale campus in Profile Park, Dublin.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/emea/dublin",
        title: "Digital Realty Dublin",
        type: "operator",
      },
    ],
  },
  // ===== FRANKFURT CLUSTER =====
  {
    slug: "aws-fra-frankfurt",
    name: "AWS Frankfurt (eu-central-1)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 50.1109,
    lng: 8.6821,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    primaryPowerSource: "grid-mixed",
    description:
      "AWS eu-central-1 region with multiple availability zones across Frankfurt metro.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-germany-west-central-frankfurt",
    name: "Microsoft Azure Germany West Central (Frankfurt)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 50.0937,
    lng: 8.6438,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    primaryPowerSource: "grid-mixed",
    description: "Microsoft Azure Germany West Central region in Frankfurt.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-frankfurt",
    name: "Google Cloud Frankfurt (europe-west3)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 50.1213,
    lng: 8.6365,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    description: "Google Cloud europe-west3 region in Frankfurt.",
    sources: [
      {
        url: "https://cloud.google.com/about/locations",
        title: "Google Cloud Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-fr2-frankfurt",
    name: "Equinix FR2 Frankfurt",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 50.0884,
    lng: 8.6741,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    description: "Equinix Frankfurt FR2 campus, key DE-CIX peering hub.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/germany-colocation/frankfurt-data-centers/fr2",
        title: "Equinix FR2",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-fr5-frankfurt",
    name: "Equinix FR5 Frankfurt",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 50.0916,
    lng: 8.6772,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    description: "Equinix FR5 colocation facility in Frankfurt.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/germany-colocation/frankfurt-data-centers/fr5",
        title: "Equinix FR5",
        type: "operator",
      },
    ],
  },
  {
    slug: "digital-realty-fra1-frankfurt",
    name: "Digital Realty FRA1 (Interxion)",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: false,
    lat: 50.1052,
    lng: 8.6921,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    description:
      "Digital Realty / Interxion Frankfurt campus, FRA1-FRA17 cluster.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/emea/frankfurt",
        title: "Digital Realty Frankfurt",
        type: "operator",
      },
    ],
  },
  {
    slug: "ntt-frankfurt-1",
    name: "NTT Frankfurt 1 Data Center",
    operatorSlug: "ntt",
    status: "operational",
    aiDedicated: false,
    lat: 50.0892,
    lng: 8.6634,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    capacityMw: 30,
    description: "NTT GDC Frankfurt 1 facility on Hanauer Landstrasse.",
    sources: [
      {
        url: "https://services.global.ntt/en-us/services-and-products/data-centers/emea/frankfurt-1-data-center",
        title: "NTT Frankfurt 1",
        type: "operator",
      },
    ],
  },
  {
    slug: "telehouse-frankfurt",
    name: "Telehouse Frankfurt",
    operatorSlug: "telehouse",
    status: "operational",
    aiDedicated: false,
    lat: 50.0974,
    lng: 8.6892,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    description: "KDDI / Telehouse Frankfurt data center.",
    sources: [
      {
        url: "https://www.telehouse.net/data-centres/emea/germany/frankfurt/",
        title: "Telehouse Frankfurt",
        type: "operator",
      },
    ],
  },
  {
    slug: "cyrusone-frankfurt-i",
    name: "CyrusOne Frankfurt I",
    operatorSlug: "cyrusone",
    status: "operational",
    aiDedicated: false,
    lat: 50.1376,
    lng: 8.7401,
    city: "Frankfurt",
    region: "Hesse",
    country: "DE",
    capacityMw: 36,
    description: "CyrusOne Frankfurt I hyperscale data center in Heddernheim.",
    sources: [
      {
        url: "https://cyrusone.com/data-center-locations/europe/frankfurt-data-centers/",
        title: "CyrusOne Frankfurt",
        type: "operator",
      },
    ],
  },
  // ===== AMSTERDAM =====
  {
    slug: "aws-amsterdam",
    name: "AWS Amsterdam (eu-west region edge)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 52.3702,
    lng: 4.8952,
    city: "Amsterdam",
    region: "North Holland",
    country: "NL",
    description: "AWS edge and direct connect facility in Amsterdam metro.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-netherlands-middenmeer",
    name: "Microsoft Azure West Europe (Middenmeer)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 52.8053,
    lng: 4.9963,
    city: "Middenmeer",
    region: "North Holland",
    country: "NL",
    capacityMw: 95,
    primaryPowerSource: "wind",
    coolingType: "closed-loop",
    description: "Microsoft Azure West Europe region campus at Agriport A7.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-eemshaven",
    name: "Google Eemshaven Data Center",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 53.4453,
    lng: 6.8377,
    city: "Eemshaven",
    region: "Groningen",
    country: "NL",
    capacityMw: 76,
    primaryPowerSource: "wind",
    coolingType: "closed-loop",
    description:
      "Google's europe-west4 datacenter near Eemshaven, powered by Dutch wind energy.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/eemshaven/",
        title: "Google Eemshaven",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-zeewolde",
    name: "Meta Zeewolde Data Center (cancelled)",
    operatorSlug: "meta",
    status: "cancelled",
    aiDedicated: false,
    lat: 52.3192,
    lng: 5.5394,
    city: "Zeewolde",
    region: "Flevoland",
    country: "NL",
    description:
      "Meta hyperscale campus cancelled in 2022 after political opposition over land/water use.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/meta-cancels-1bn-zeewolde-data-center-project-in-netherlands/",
        title: "Meta cancels Zeewolde",
        type: "news",
      },
    ],
  },
  {
    slug: "equinix-am3-amsterdam",
    name: "Equinix AM3 Amsterdam",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 52.3007,
    lng: 4.9419,
    city: "Amsterdam",
    region: "North Holland",
    country: "NL",
    description: "Equinix AM3 in Amsterdam Science Park, AMS-IX core hub.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/netherlands-colocation/amsterdam-data-centers/am3",
        title: "Equinix AM3",
        type: "operator",
      },
    ],
  },
  {
    slug: "digital-realty-ams1-amsterdam",
    name: "Digital Realty AMS1 (Interxion)",
    operatorSlug: "digital-realty",
    status: "operational",
    aiDedicated: false,
    lat: 52.3084,
    lng: 4.9442,
    city: "Amsterdam",
    region: "North Holland",
    country: "NL",
    description:
      "Digital Realty / Interxion AMS1 in Schiphol-Rijk Science Park campus.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/emea/amsterdam",
        title: "Digital Realty Amsterdam",
        type: "operator",
      },
    ],
  },
  // ===== LONDON / UK =====
  {
    slug: "aws-london-eu-west-2",
    name: "AWS London (eu-west-2)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 51.5074,
    lng: -0.1278,
    city: "London",
    country: "GB",
    description:
      "AWS eu-west-2 region in London metro with multiple availability zones.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-uk-south-london",
    name: "Microsoft Azure UK South (London)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 51.5074,
    lng: -0.1278,
    city: "London",
    country: "GB",
    description:
      "Microsoft Azure UK South region serving the United Kingdom from London metro.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-uk-west-cardiff",
    name: "Microsoft Azure UK West (Cardiff)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 51.4816,
    lng: -3.1791,
    city: "Cardiff",
    region: "Wales",
    country: "GB",
    description: "Microsoft Azure UK West region in Cardiff.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-london-europe-west2",
    name: "Google Cloud London (europe-west2)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 51.5074,
    lng: -0.1278,
    city: "London",
    country: "GB",
    description: "Google Cloud europe-west2 region in the London area.",
    sources: [
      {
        url: "https://cloud.google.com/about/locations",
        title: "Google Cloud Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ld4-slough",
    name: "Equinix LD4 Slough",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 51.5081,
    lng: -0.6286,
    city: "Slough",
    region: "Berkshire",
    country: "GB",
    description: "Equinix LD4 Slough, premier UK financial peering point.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/united-kingdom-colocation/london-data-centers/ld4",
        title: "Equinix LD4",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ld6-slough",
    name: "Equinix LD6 Slough",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 51.5099,
    lng: -0.6294,
    city: "Slough",
    region: "Berkshire",
    country: "GB",
    description: "Equinix LD6 Slough campus, expansion adjacent to LD4/LD5.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/united-kingdom-colocation/london-data-centers/ld6",
        title: "Equinix LD6",
        type: "operator",
      },
    ],
  },
  {
    slug: "virtus-stockley-park-london4",
    name: "Virtus LONDON4 Stockley Park",
    operatorSlug: "virtus",
    status: "operational",
    aiDedicated: false,
    lat: 51.5161,
    lng: -0.4612,
    city: "Hayes",
    region: "London",
    country: "GB",
    capacityMw: 18,
    coolingType: "closed-loop",
    description: "Virtus LONDON4 hyperscale data center at Stockley Park.",
    sources: [
      {
        url: "https://www.virtusdatacentres.com/our-data-centres/london4",
        title: "Virtus LONDON4",
        type: "operator",
      },
    ],
  },
  // ===== PARIS / FRANCE =====
  {
    slug: "aws-paris-eu-west-3",
    name: "AWS Paris (eu-west-3)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 48.8566,
    lng: 2.3522,
    city: "Paris",
    region: "Ile-de-France",
    country: "FR",
    description: "AWS eu-west-3 region in the Paris metropolitan area.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-france-central-marne-la-vallee",
    name: "Microsoft Azure France Central (Marne-la-Vallée)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 48.8407,
    lng: 2.6517,
    city: "Marne-la-Vallée",
    region: "Ile-de-France",
    country: "FR",
    description: "Microsoft Azure France Central region near Paris.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "ovhcloud-roubaix",
    name: "OVHcloud Roubaix Campus",
    operatorSlug: "ovhcloud",
    status: "operational",
    aiDedicated: false,
    lat: 50.6927,
    lng: 3.1746,
    city: "Roubaix",
    region: "Hauts-de-France",
    country: "FR",
    capacityMw: 60,
    primaryPowerSource: "grid-mixed",
    coolingType: "direct-to-chip",
    description:
      "OVHcloud's flagship Roubaix campus (RBX1-RBX8); pioneered watercooling.",
    sources: [
      {
        url: "https://www.ovhcloud.com/en/about-us/data-centers/",
        title: "OVHcloud Data Centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-pa2-paris",
    name: "Equinix PA2 Paris",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 48.9266,
    lng: 2.3056,
    city: "Saint-Denis",
    region: "Ile-de-France",
    country: "FR",
    description:
      "Equinix PA2 carrier-dense facility in the Paris metropolitan area.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/france-colocation/paris-data-centers/pa2",
        title: "Equinix PA2",
        type: "operator",
      },
    ],
  },
  {
    slug: "data4-paris-saclay",
    name: "Data4 Paris-Saclay Campus",
    operatorSlug: "data4",
    status: "operational",
    aiDedicated: false,
    lat: 48.6873,
    lng: 2.1769,
    city: "Marcoussis",
    region: "Ile-de-France",
    country: "FR",
    capacityMw: 200,
    description:
      "Data4 hyperscale campus at Paris-Saclay, multi-building deployment.",
    sources: [
      {
        url: "https://www.data4group.com/en/data-center-locations/france-paris-saclay/",
        title: "Data4 Paris-Saclay",
        type: "operator",
      },
    ],
  },
  // ===== NORDICS =====
  {
    slug: "aws-stockholm-eu-north-1",
    name: "AWS Stockholm (eu-north-1)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 59.3293,
    lng: 18.0686,
    city: "Stockholm",
    country: "SE",
    primaryPowerSource: "hydro",
    description:
      "AWS eu-north-1 region in Stockholm metro, marketed as 100% renewable.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-sweden-central-gavle",
    name: "Microsoft Azure Sweden Central (Gävle)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 60.6749,
    lng: 17.1413,
    city: "Gävle",
    country: "SE",
    primaryPowerSource: "hydro",
    coolingType: "closed-loop",
    description: "Microsoft Azure Sweden Central region datacenter in Gävle.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-sweden-sandviken",
    name: "Microsoft Azure Sweden (Sandviken)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 60.6175,
    lng: 16.7755,
    city: "Sandviken",
    country: "SE",
    primaryPowerSource: "hydro",
    description: "Microsoft Azure Sweden Central region facility in Sandviken.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-sweden-staffanstorp",
    name: "Microsoft Azure Sweden (Staffanstorp)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 55.6394,
    lng: 13.2089,
    city: "Staffanstorp",
    region: "Skåne",
    country: "SE",
    primaryPowerSource: "wind",
    description: "Microsoft Azure datacenter in Staffanstorp, southern Sweden.",
    sources: [
      {
        url: "https://news.microsoft.com/europe/2020/06/15/microsoft-builds-sustainable-datacenter-region-in-sweden/",
        title: "Microsoft Sweden",
        type: "pr",
      },
    ],
  },
  {
    slug: "meta-lulea",
    name: "Meta Luleå Data Center",
    operatorSlug: "meta",
    status: "operational",
    aiDedicated: false,
    lat: 65.5848,
    lng: 22.1547,
    city: "Luleå",
    region: "Norrbotten",
    country: "SE",
    capacityMw: 120,
    primaryPowerSource: "hydro",
    coolingType: "air",
    description:
      "Meta's first European data center, uses outside-air cooling and hydropower.",
    sources: [
      {
        url: "https://datacenters.atmeta.com/lulea/",
        title: "Meta Luleå",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-hamina",
    name: "Google Hamina Data Center",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 60.5608,
    lng: 27.1972,
    city: "Hamina",
    region: "Kymenlaakso",
    country: "FI",
    capacityMw: 200,
    primaryPowerSource: "wind",
    coolingType: "open-loop",
    description:
      "Google's europe-north1 data center, uses Gulf of Finland seawater cooling.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/hamina/",
        title: "Google Hamina",
        type: "operator",
      },
    ],
  },
  {
    slug: "nebius-mantsala",
    name: "Nebius Mäntsälä Data Center",
    operatorSlug: "nebius",
    status: "operational",
    aiDedicated: true,
    lat: 60.6336,
    lng: 25.3133,
    city: "Mäntsälä",
    region: "Uusimaa",
    country: "FI",
    capacityMw: 75,
    capacityMwPlanned: 150,
    primaryPowerSource: "grid-mixed",
    coolingType: "closed-loop",
    description:
      "Nebius (former Yandex) AI-focused GPU cluster in Mäntsälä; heat-recovery district heating.",
    sources: [
      {
        url: "https://nebius.com/about",
        title: "Nebius About",
        type: "operator",
      },
    ],
  },
  {
    slug: "atnorth-ice02-keflavik",
    name: "atNorth ICE02 Keflavík",
    operatorSlug: "atnorth",
    status: "operational",
    aiDedicated: true,
    lat: 63.985,
    lng: -22.6056,
    city: "Reykjanesbær",
    region: "Suðurnes",
    country: "IS",
    capacityMw: 80,
    primaryPowerSource: "geothermal",
    coolingType: "air",
    description:
      "atNorth (ex-Advania) HPC/AI campus near Keflavík; geothermal & hydro power.",
    sources: [
      {
        url: "https://www.atnorth.com/data-centers/iceland-ice02",
        title: "atNorth ICE02",
        type: "operator",
      },
    ],
  },
  {
    slug: "atnorth-ice03-akureyri",
    name: "atNorth ICE03 Akureyri",
    operatorSlug: "atnorth",
    status: "under-construction",
    aiDedicated: true,
    lat: 65.6835,
    lng: -18.1262,
    city: "Akureyri",
    country: "IS",
    capacityMwPlanned: 80,
    primaryPowerSource: "hydro",
    coolingType: "air",
    description:
      "atNorth's third Icelandic site in Akureyri, designed for AI workloads.",
    sources: [
      {
        url: "https://www.atnorth.com/news/atnorth-announces-new-ice03-site-in-akureyri-iceland",
        title: "atNorth ICE03 Akureyri",
        type: "pr",
      },
    ],
  },
  {
    slug: "verne-global-keflavik",
    name: "Verne Keflavík Campus",
    operatorSlug: "verne",
    status: "operational",
    aiDedicated: true,
    lat: 63.9728,
    lng: -22.6307,
    city: "Reykjanesbær",
    region: "Suðurnes",
    country: "IS",
    capacityMw: 100,
    primaryPowerSource: "geothermal",
    coolingType: "air",
    description:
      "Verne (formerly Verne Global) HPC/AI campus on a former NATO base; 100% renewable.",
    sources: [
      { url: "https://verneglobal.com/", title: "Verne", type: "operator" },
    ],
  },
  {
    slug: "hydro66-boden",
    name: "Hydro66 Boden Data Center",
    operatorSlug: "hydro66",
    status: "operational",
    aiDedicated: true,
    lat: 65.8252,
    lng: 21.6886,
    city: "Boden",
    region: "Norrbotten",
    country: "SE",
    capacityMw: 22,
    primaryPowerSource: "hydro",
    coolingType: "air",
    description:
      "Hydro66 modular HPC/AI data center in Boden, 100% hydro powered.",
    sources: [
      { url: "https://www.hydro66.com/", title: "Hydro66", type: "operator" },
    ],
  },
  {
    slug: "crusoe-iceland",
    name: "Crusoe Iceland Data Center",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 64.0337,
    lng: -22.1077,
    city: "Hafnarfjörður",
    country: "IS",
    capacityMw: 30,
    primaryPowerSource: "geothermal",
    coolingType: "air",
    description:
      "Crusoe Energy GPU cloud facility in Iceland leveraging geothermal/hydro.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/crusoe-acquires-iceland-data-center-from-gompute/",
        title: "Crusoe Iceland",
        type: "news",
      },
    ],
  },
  // ===== OTHER EUROPEAN HUBS =====
  {
    slug: "azure-spain-central-madrid",
    name: "Microsoft Azure Spain Central (Madrid)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 40.4937,
    lng: -3.5676,
    city: "San Sebastián de los Reyes",
    region: "Madrid",
    country: "ES",
    description: "Microsoft Azure Spain Central region in greater Madrid.",
    sources: [
      {
        url: "https://news.microsoft.com/es-es/2024/02/26/microsoft-region-cloud-spain/",
        title: "Microsoft Spain Cloud",
        type: "pr",
      },
    ],
  },
  {
    slug: "google-madrid-europe-southwest1",
    name: "Google Cloud Madrid (europe-southwest1)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 40.4168,
    lng: -3.7038,
    city: "Madrid",
    country: "ES",
    description: "Google Cloud europe-southwest1 region in Madrid.",
    sources: [
      {
        url: "https://cloud.google.com/about/locations",
        title: "Google Cloud Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-italy-north-milan",
    name: "Microsoft Azure Italy North (Milan)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 45.4642,
    lng: 9.19,
    city: "Milan",
    region: "Lombardy",
    country: "IT",
    description:
      "Microsoft Azure Italy North region in Milan metropolitan area.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-milan-eu-south-1",
    name: "AWS Milan (eu-south-1)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 45.4642,
    lng: 9.19,
    city: "Milan",
    region: "Lombardy",
    country: "IT",
    description: "AWS eu-south-1 region in Milan metropolitan area.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "apple-athenry-cancelled",
    name: "Apple Athenry Data Center (cancelled)",
    operatorSlug: "apple",
    status: "cancelled",
    aiDedicated: false,
    lat: 53.2986,
    lng: -8.7457,
    city: "Athenry",
    region: "Galway",
    country: "IE",
    description:
      "Planned Apple data center cancelled in 2018 after planning delays.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/apple-cancels-its-irish-data-center-plans/",
        title: "Apple cancels Athenry",
        type: "news",
      },
    ],
  },
  {
    slug: "equinix-zh4-zurich",
    name: "Equinix ZH4 Zurich",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 47.3769,
    lng: 8.5417,
    city: "Zurich",
    country: "CH",
    description:
      "Equinix ZH4 colocation facility in the Zurich metropolitan area.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/switzerland-colocation/zurich-data-centers/zh4",
        title: "Equinix ZH4",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-switzerland-north-zurich",
    name: "Microsoft Azure Switzerland North (Zurich)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 47.3769,
    lng: 8.5417,
    city: "Zurich",
    country: "CH",
    description: "Microsoft Azure Switzerland North region in Zurich metro.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft Datacenter Map",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-wa1-warsaw",
    name: "Equinix WA1 Warsaw",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 52.2097,
    lng: 20.9806,
    city: "Warsaw",
    region: "Mazovia",
    country: "PL",
    description:
      "Equinix WA1 (former Bezeq Polska) carrier-neutral facility in Warsaw.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/poland-colocation/warsaw-data-centers/wa1",
        title: "Equinix WA1",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-he6-helsinki",
    name: "Equinix HE6 Helsinki",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 60.2055,
    lng: 24.6559,
    city: "Espoo",
    region: "Uusimaa",
    country: "FI",
    description:
      "Equinix HE6 facility (former Telia) in Helsinki metropolitan area.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/europe-colocation/finland-colocation/helsinki-data-centers",
        title: "Equinix Helsinki",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-saint-ghislain",
    name: "Google Saint-Ghislain Data Center",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 50.4555,
    lng: 3.8158,
    city: "Saint-Ghislain",
    region: "Hainaut",
    country: "BE",
    capacityMw: 280,
    primaryPowerSource: "grid-mixed",
    coolingType: "open-loop",
    description:
      "Google's europe-west1 data center; first Google site to operate fully chiller-less.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/st-ghislain/",
        title: "Google Saint-Ghislain",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-fredericia",
    name: "Google Fredericia Data Center",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 55.5657,
    lng: 9.7528,
    city: "Fredericia",
    region: "Southern Denmark",
    country: "DK",
    capacityMw: 130,
    primaryPowerSource: "wind",
    coolingType: "closed-loop",
    description:
      "Google europe-north2 data center, fully renewable-matched and seawater-cooled.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/fredericia/",
        title: "Google Fredericia",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-odense",
    name: "Meta Odense Data Center",
    operatorSlug: "meta",
    status: "operational",
    aiDedicated: false,
    lat: 55.376,
    lng: 10.4419,
    city: "Odense",
    region: "Funen",
    country: "DK",
    capacityMw: 175,
    primaryPowerSource: "wind",
    coolingType: "air",
    description:
      "Meta's Odense data center supplies waste heat to Fjernvarme Fyn district heating.",
    sources: [
      {
        url: "https://datacenters.atmeta.com/odense/",
        title: "Meta Odense",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-skien",
    name: "Google Skien (Gromstul) Data Center",
    operatorSlug: "google",
    status: "under-construction",
    aiDedicated: false,
    lat: 59.2096,
    lng: 9.6094,
    city: "Skien",
    region: "Telemark",
    country: "NO",
    capacityMwPlanned: 240,
    primaryPowerSource: "hydro",
    description: "Google's planned Norwegian data center campus at Gromstul.",
    sources: [
      {
        url: "https://www.datacenterdynamics.com/en/news/google-acquires-2000-acre-site-in-norway-for-data-center-campus/",
        title: "Google Skien",
        type: "news",
      },
    ],
  },
  {
    slug: "green-mountain-dc1-stavanger",
    name: "Green Mountain DC1-Stavanger (Rennesøy)",
    operatorSlug: "green-mountain",
    status: "operational",
    aiDedicated: true,
    lat: 59.0978,
    lng: 5.7461,
    city: "Rennesøy",
    region: "Rogaland",
    country: "NO",
    capacityMw: 35,
    primaryPowerSource: "hydro",
    coolingType: "open-loop",
    description:
      "Green Mountain DC1 in former NATO ammunition store; deep fjord-water cooling, 100% hydro.",
    sources: [
      {
        url: "https://greenmountain.no/sites/dc1-stavanger/",
        title: "Green Mountain DC1",
        type: "operator",
      },
    ],
  },
  {
    slug: "lefdal-mine-datacenter",
    name: "Lefdal Mine Data Center",
    operatorSlug: "lefdal-mine",
    status: "operational",
    aiDedicated: true,
    lat: 61.7986,
    lng: 5.6661,
    city: "Måløy",
    region: "Vestland",
    country: "NO",
    capacityMw: 60,
    capacityMwPlanned: 200,
    primaryPowerSource: "hydro",
    coolingType: "open-loop",
    description:
      "Underground mine data center using fjord water cooling; hosts AI/HPC tenants.",
    sources: [
      {
        url: "https://lefdalmine.com/",
        title: "Lefdal Mine Datacenter",
        type: "operator",
      },
    ],
  },
  {
    slug: "stack-emea-osl01-oslo",
    name: "Stack EMEA OSL01 Oslo",
    operatorSlug: "stack-infrastructure",
    status: "operational",
    aiDedicated: false,
    lat: 59.913,
    lng: 10.7522,
    city: "Oslo",
    country: "NO",
    capacityMw: 32,
    primaryPowerSource: "hydro",
    description: "Stack Infrastructure OSL01 hyperscale facility outside Oslo.",
    sources: [
      {
        url: "https://www.stackinfra.com/locations/europe/",
        title: "Stack EMEA Locations",
        type: "operator",
      },
    ],
  },
  {
    slug: "ecodatacenter-falun",
    name: "EcoDataCenter Falun",
    operatorSlug: "ecodatacenter",
    status: "operational",
    aiDedicated: true,
    lat: 60.6107,
    lng: 15.6321,
    city: "Falun",
    region: "Dalarna",
    country: "SE",
    capacityMw: 26,
    primaryPowerSource: "hydro",
    coolingType: "closed-loop",
    description:
      "EcoDataCenter timber-built campus in Falun, climate-positive design for HPC/AI.",
    sources: [
      {
        url: "https://ecodatacenter.tech/data-centers/ecodc-falun/",
        title: "EcoDataCenter Falun",
        type: "operator",
      },
    ],
  },
  {
    slug: "azure-poland-central-warsaw",
    name: "Microsoft Azure Poland Central (Warsaw)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 52.2297,
    lng: 21.0122,
    city: "Warsaw",
    region: "Mazovia",
    country: "PL",
    description:
      "Microsoft Azure Poland Central region serving the Polish market.",
    sources: [
      {
        url: "https://news.microsoft.com/europe/2023/04/05/microsoft-launches-cloud-region-in-poland/",
        title: "Microsoft Poland",
        type: "pr",
      },
    ],
  },
  {
    slug: "scaleway-dc5-paris",
    name: "Scaleway DC5 Paris",
    operatorSlug: "scaleway",
    status: "operational",
    aiDedicated: true,
    lat: 48.728,
    lng: 2.5822,
    city: "Lisses",
    region: "Ile-de-France",
    country: "FR",
    capacityMw: 16,
    coolingType: "direct-to-chip",
    description:
      "Scaleway DC5 is fully adiabatic, hosts company's AI GPU clusters.",
    sources: [
      {
        url: "https://www.scaleway.com/en/dedibox/datacenter/",
        title: "Scaleway Datacenters",
        type: "operator",
      },
    ],
  },
  {
    slug: "telefonica-alcala-madrid",
    name: "Telefónica Alcalá Data Center",
    operatorSlug: "telefonica",
    status: "operational",
    aiDedicated: false,
    lat: 40.4825,
    lng: -3.3636,
    city: "Alcalá de Henares",
    region: "Madrid",
    country: "ES",
    capacityMw: 22,
    description:
      "Telefónica's flagship Spanish data center in Alcalá de Henares.",
    sources: [
      {
        url: "https://www.telefonicatech.com/en/cloud",
        title: "Telefónica Tech Cloud",
        type: "operator",
      },
    ],
  },
];

export const EU_BRANDS: SeedBrand[] = [
  {
    slug: "ovhcloud",
    canonicalName: "OVHcloud",
    website: "https://www.ovhcloud.com",
  },
  {
    slug: "data4",
    canonicalName: "Data4",
    website: "https://www.data4group.com",
  },
  {
    slug: "ntt",
    canonicalName: "NTT Global Data Centers",
    website: "https://services.global.ntt",
  },
  {
    slug: "telehouse",
    canonicalName: "Telehouse (KDDI)",
    website: "https://www.telehouse.net",
  },
  {
    slug: "cyrusone",
    canonicalName: "CyrusOne",
    website: "https://cyrusone.com",
  },
  {
    slug: "virtus",
    canonicalName: "Virtus Data Centres",
    website: "https://www.virtusdatacentres.com",
  },
  {
    slug: "atnorth",
    canonicalName: "atNorth",
    website: "https://www.atnorth.com",
  },
  { slug: "verne", canonicalName: "Verne", website: "https://verneglobal.com" },
  {
    slug: "hydro66",
    canonicalName: "Hydro66",
    website: "https://www.hydro66.com",
  },
  { slug: "nebius", canonicalName: "Nebius", website: "https://nebius.com" },
  {
    slug: "green-mountain",
    canonicalName: "Green Mountain",
    website: "https://greenmountain.no",
  },
  {
    slug: "lefdal-mine",
    canonicalName: "Lefdal Mine Datacenter",
    website: "https://lefdalmine.com",
  },
  {
    slug: "stack-infrastructure",
    canonicalName: "Stack Infrastructure",
    website: "https://www.stackinfra.com",
  },
  {
    slug: "ecodatacenter",
    canonicalName: "EcoDataCenter",
    website: "https://ecodatacenter.tech",
  },
  {
    slug: "scaleway",
    canonicalName: "Scaleway",
    website: "https://www.scaleway.com",
  },
  {
    slug: "telefonica",
    canonicalName: "Telefónica Tech",
    website: "https://www.telefonicatech.com",
  },
  { slug: "apple", canonicalName: "Apple", website: "https://www.apple.com" },
  {
    slug: "equinix",
    canonicalName: "Equinix",
    website: "https://www.equinix.com",
  },
  {
    slug: "digital-realty",
    canonicalName: "Digital Realty",
    website: "https://www.digitalrealty.com",
  },
];
