import type { SeedDatacenter, SeedBrand } from "./types";

// === NORTH AMERICA ===
export const NORTH_AMERICA: SeedDatacenter[] = [
  // --- AWS hyperscaler regions ---
  {
    slug: "aws-us-east-1-ashburn-main",
    name: "AWS US-East-1 Ashburn Campus",
    operatorSlug: "aws",
    status: "expanding",
    aiDedicated: false,
    lat: 39.0438,
    lng: -77.4874,
    city: "Ashburn",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "Original AWS US-East-1 region, the densest cluster of AWS availability zones in the world, anchoring Loudoun County's Data Center Alley.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
      {
        url: "https://en.wikipedia.org/wiki/List_of_Amazon_Web_Services_data_centers",
        title: "List of AWS data centers",
        type: "other",
      },
    ],
  },
  {
    slug: "aws-us-west-2-boardman",
    name: "AWS US-West-2 (Boardman OR)",
    operatorSlug: "aws",
    status: "expanding",
    aiDedicated: false,
    lat: 45.8393,
    lng: -119.7006,
    city: "Boardman",
    region: "OR",
    country: "US",
    primaryPowerSource: "hydro",
    utilitySlug: "umatilla-electric",
    coolingType: "closed-loop",
    description:
      "AWS US-West-2 region anchored by a multi-building campus along the Columbia River in Morrow and Umatilla counties, leveraging Pacific Northwest hydro power.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/aws-expands-in-oregon/",
        title: "AWS Oregon expansion",
        type: "news",
      },
    ],
  },
  {
    slug: "aws-us-east-2-new-albany",
    name: "AWS US-East-2 (Central Ohio)",
    operatorSlug: "aws",
    status: "expanding",
    aiDedicated: false,
    lat: 40.0809,
    lng: -82.8088,
    city: "New Albany",
    region: "OH",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "aep-ohio",
    coolingType: "closed-loop",
    description:
      "AWS US-East-2 Ohio region with major campuses in New Albany, Hilliard, and Dublin; subject of a $7.8B expansion announcement in 2024.",
    sources: [
      {
        url: "https://www.aboutamazon.com/news/aws/aws-investing-in-central-ohio",
        title: "AWS Central Ohio investment",
        type: "pr",
      },
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-ca-central-1-montreal",
    name: "AWS CA-Central-1 (Montréal)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 45.5017,
    lng: -73.5673,
    city: "Montréal",
    region: "QC",
    country: "CA",
    primaryPowerSource: "hydro",
    utilitySlug: "hydro-quebec",
    coolingType: "closed-loop",
    description:
      "AWS Canada (Central) region serving Canadian workloads from leased facilities in the greater Montréal area on Hydro-Québec hydro power.",
    sources: [
      {
        url: "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
        title: "AWS Global Infrastructure",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-ca-west-1-calgary",
    name: "AWS CA-West-1 (Calgary)",
    operatorSlug: "aws",
    status: "operational",
    aiDedicated: false,
    lat: 51.0447,
    lng: -114.0719,
    city: "Calgary",
    region: "AB",
    country: "CA",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "enmax",
    coolingType: "air",
    description:
      "AWS Canada West (Calgary) region launched in late 2023 to serve western-Canadian latency and data-residency workloads.",
    sources: [
      {
        url: "https://aws.amazon.com/blogs/aws/aws-canada-west-calgary-region/",
        title: "AWS Canada West (Calgary) launch",
        type: "operator",
      },
    ],
  },
  {
    slug: "aws-mexico-central-queretaro",
    name: "AWS Mexico (Central) Querétaro",
    operatorSlug: "aws",
    status: "under-construction",
    aiDedicated: false,
    lat: 20.5888,
    lng: -100.3899,
    city: "Querétaro",
    region: "QUE",
    country: "MX",
    capacityMwPlanned: 100,
    primaryPowerSource: "grid-mixed",
    coolingType: "closed-loop",
    description:
      "AWS announced a Mexico (Central) region with a $5B investment over 15 years, anchored in the Querétaro datacenter cluster.",
    sources: [
      {
        url: "https://aws.amazon.com/blogs/aws/in-the-works-aws-mexico-central-region/",
        title: "AWS Mexico Central announcement",
        type: "pr",
      },
    ],
  },

  // --- Microsoft Azure ---
  {
    slug: "microsoft-quincy-columbia",
    name: "Microsoft Quincy WA Campus",
    operatorSlug: "microsoft",
    status: "expanding",
    aiDedicated: false,
    lat: 47.2336,
    lng: -119.8526,
    city: "Quincy",
    region: "WA",
    country: "US",
    capacityMwPlanned: 600,
    primaryPowerSource: "hydro",
    utilitySlug: "grant-county-pud",
    coolingType: "closed-loop",
    description:
      "Microsoft's flagship Pacific Northwest campus built around the Columbia Basin's hydropower grid; long-running multi-building Azure footprint.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft datacenters globe",
        type: "operator",
      },
      {
        url: "https://en.wikipedia.org/wiki/List_of_Microsoft_data_centers",
        title: "List of Microsoft data centers",
        type: "other",
      },
    ],
  },
  {
    slug: "microsoft-san-antonio",
    name: "Microsoft San Antonio Campus",
    operatorSlug: "microsoft",
    status: "expanding",
    aiDedicated: false,
    lat: 29.4241,
    lng: -98.4936,
    city: "San Antonio",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "cps-energy",
    coolingType: "closed-loop",
    description:
      "Microsoft's first dedicated Texas campus, originally opened in 2008 and aggressively expanded through 2024 with adjacent build-outs.",
    sources: [
      {
        url: "https://news.microsoft.com/2007/04/17/microsoft-to-build-data-center-in-san-antonio/",
        title: "Microsoft San Antonio announcement",
        type: "pr",
      },
      {
        url: "https://www.bizjournals.com/sanantonio/news/2023/04/03/microsoft-data-center-westover-hills.html",
        title: "Microsoft San Antonio expansion",
        type: "news",
      },
    ],
  },
  {
    slug: "microsoft-cheyenne",
    name: "Microsoft Cheyenne WY Campus",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 41.1399,
    lng: -104.7676,
    city: "Cheyenne",
    region: "WY",
    country: "US",
    primaryPowerSource: "wind",
    utilitySlug: "black-hills-energy",
    coolingType: "air",
    description:
      "Microsoft Cheyenne campus pioneered adiabatic outside-air cooling and is partly powered by wind under a long-term Black Hills Energy PPA.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft datacenters globe",
        type: "operator",
      },
      {
        url: "https://www.datacenterknowledge.com/microsoft/microsoft-cheyenne-data-center",
        title: "Microsoft Cheyenne overview",
        type: "news",
      },
    ],
  },
  {
    slug: "microsoft-boydton",
    name: "Microsoft Boydton VA Campus",
    operatorSlug: "microsoft",
    status: "expanding",
    aiDedicated: false,
    lat: 36.6677,
    lng: -78.3889,
    city: "Boydton",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "Microsoft's southern Virginia (East US 2) campus in Mecklenburg County; one of Azure's largest US East regions outside Loudoun.",
    sources: [
      {
        url: "https://datacenters.microsoft.com/globe/explore/",
        title: "Microsoft datacenters globe",
        type: "operator",
      },
    ],
  },
  {
    slug: "microsoft-east-atlanta-region",
    name: "Microsoft East US 3 (Atlanta)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 33.749,
    lng: -84.388,
    city: "Atlanta",
    region: "GA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "georgia-power",
    coolingType: "closed-loop",
    description:
      "Microsoft's East US 3 cloud region anchored by campuses in Douglas, Fulton, and Palmetto serving the southeastern US.",
    sources: [
      {
        url: "https://news.microsoft.com/source/2022/03/15/microsoft-announces-new-datacenter-region-coming-to-georgia/",
        title: "Microsoft Georgia datacenter region",
        type: "pr",
      },
    ],
  },
  {
    slug: "microsoft-querétaro",
    name: "Microsoft Mexico Central (Querétaro)",
    operatorSlug: "microsoft",
    status: "operational",
    aiDedicated: false,
    lat: 20.5931,
    lng: -100.392,
    city: "Querétaro",
    region: "QUE",
    country: "MX",
    primaryPowerSource: "grid-mixed",
    coolingType: "closed-loop",
    description:
      "Microsoft's first Latin-America datacenter region in Querétaro, launched in 2024 as part of a $1.1B Mexico investment.",
    sources: [
      {
        url: "https://news.microsoft.com/es-xl/microsoft-anuncia-region-de-datacenters-en-mexico/",
        title: "Microsoft Mexico region announcement",
        type: "pr",
      },
    ],
  },

  // --- Google Cloud ---
  {
    slug: "google-council-bluffs",
    name: "Google Council Bluffs IA Campus",
    operatorSlug: "google",
    status: "expanding",
    aiDedicated: false,
    lat: 41.2169,
    lng: -95.8488,
    city: "Council Bluffs",
    region: "IA",
    country: "US",
    capacityMwPlanned: 600,
    primaryPowerSource: "wind",
    utilitySlug: "mid-american-energy",
    coolingType: "closed-loop",
    description:
      "Google's largest US campus by footprint, with multiple buildings and TPU pods deployed; primary anchor of the us-central1 region.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/council-bluffs/",
        title: "Google Council Bluffs",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-mayes-county",
    name: "Google Mayes County OK (Pryor)",
    operatorSlug: "google",
    status: "expanding",
    aiDedicated: false,
    lat: 36.293,
    lng: -95.319,
    city: "Pryor",
    region: "OK",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "grand-river-dam-authority",
    coolingType: "closed-loop",
    description:
      "Google's Pryor MidAmerica Industrial Park campus in Mayes County is a multi-building site that received multiple billion-dollar expansion announcements 2022-2024.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/mayes-county/",
        title: "Google Mayes County",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-lenoir",
    name: "Google Lenoir NC Campus",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 35.9143,
    lng: -81.5389,
    city: "Lenoir",
    region: "NC",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "duke-energy",
    coolingType: "closed-loop",
    description:
      "Google's Caldwell County campus, originally opened 2008, anchoring the company's southeastern footprint.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/lenoir/",
        title: "Google Lenoir",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-berkeley-county",
    name: "Google Berkeley County SC (Moncks Corner)",
    operatorSlug: "google",
    status: "expanding",
    aiDedicated: false,
    lat: 33.1959,
    lng: -80.0148,
    city: "Moncks Corner",
    region: "SC",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "santee-cooper",
    coolingType: "closed-loop",
    description:
      "Google's South Carolina Goose Creek/Moncks Corner campus, one of the company's earliest US sites; subject of a $3.3B expansion announcement in 2024.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/berkeley-county/",
        title: "Google Berkeley County",
        type: "operator",
      },
      {
        url: "https://blog.google/inside-google/company-announcements/google-3-billion-data-center-investment/",
        title: "Google 2024 SC investment",
        type: "pr",
      },
    ],
  },
  {
    slug: "google-henderson-nv",
    name: "Google Henderson NV Campus",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 35.9858,
    lng: -115.0975,
    city: "Henderson",
    region: "NV",
    country: "US",
    primaryPowerSource: "solar",
    utilitySlug: "nv-energy",
    coolingType: "air",
    description:
      "Google's Henderson, Nevada campus in the Las Vegas metro, adjacent to a 350 MW solar PPA serving Google's regional load.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/henderson/",
        title: "Google Henderson",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-storey-nv-reno",
    name: "Google Storey County NV (Reno)",
    operatorSlug: "google",
    status: "operational",
    aiDedicated: false,
    lat: 39.5468,
    lng: -119.4474,
    city: "McCarran",
    region: "NV",
    country: "US",
    primaryPowerSource: "geothermal",
    utilitySlug: "nv-energy",
    coolingType: "closed-loop",
    description:
      "Google's Tahoe Reno Industrial Center campus uses dry-cooling and is matched with geothermal generation in northern Nevada.",
    sources: [
      {
        url: "https://www.google.com/about/datacenters/locations/reno/",
        title: "Google Reno",
        type: "operator",
      },
    ],
  },
  {
    slug: "google-loudoun-leesburg",
    name: "Google Loudoun County VA (Leesburg)",
    operatorSlug: "google",
    status: "expanding",
    aiDedicated: false,
    lat: 39.1157,
    lng: -77.5636,
    city: "Leesburg",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "Google's Loudoun County campus near Leesburg/Sterling supports the us-east4 region and is part of multi-billion-dollar Virginia expansions.",
    sources: [
      {
        url: "https://blog.google/inside-google/company-announcements/google-virginia-data-center/",
        title: "Google Virginia investment",
        type: "pr",
      },
    ],
  },
  {
    slug: "google-montreal-beauharnois",
    name: "Google Montréal (Beauharnois) QC",
    operatorSlug: "google",
    status: "under-construction",
    aiDedicated: false,
    lat: 45.3157,
    lng: -73.873,
    city: "Beauharnois",
    region: "QC",
    country: "CA",
    primaryPowerSource: "hydro",
    utilitySlug: "hydro-quebec",
    coolingType: "closed-loop",
    description:
      "Google announced a $735M datacenter campus in Beauharnois near Montréal supporting its Canadian cloud region with Hydro-Québec power.",
    sources: [
      {
        url: "https://blog.google/intl/en-ca/company-news/outreach-initiatives/google-quebec-data-center/",
        title: "Google Beauharnois announcement",
        type: "pr",
      },
    ],
  },

  // --- Meta ---
  {
    slug: "meta-prineville",
    name: "Meta Prineville OR Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 44.3,
    lng: -120.834,
    city: "Prineville",
    region: "OR",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "pacific-power",
    coolingType: "air",
    description:
      "Meta's first owned datacenter, opened 2011, with multiple buildings using Open Compute outside-air evaporative cooling.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/prineville/",
        title: "Meta Prineville",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-forest-city",
    name: "Meta Forest City NC Campus",
    operatorSlug: "meta",
    status: "operational",
    aiDedicated: false,
    lat: 35.3343,
    lng: -81.8651,
    city: "Forest City",
    region: "NC",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "duke-energy",
    coolingType: "air",
    description:
      "Meta's Rutherford County, NC campus, opened 2012 as the company's second datacenter.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/forest-city/",
        title: "Meta Forest City",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-altoona",
    name: "Meta Altoona IA Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 41.6452,
    lng: -93.4269,
    city: "Altoona",
    region: "IA",
    country: "US",
    primaryPowerSource: "wind",
    utilitySlug: "mid-american-energy",
    coolingType: "air",
    description:
      "Meta's Iowa campus, opened 2014, was the company's first 100% wind-matched datacenter.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/altoona/",
        title: "Meta Altoona",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-fort-worth",
    name: "Meta Fort Worth TX Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 32.9876,
    lng: -97.4198,
    city: "Fort Worth",
    region: "TX",
    country: "US",
    capacityMwPlanned: 250,
    primaryPowerSource: "wind",
    utilitySlug: "oncor",
    coolingType: "air",
    description:
      "Meta's Fort Worth campus is a multi-building cluster matched by Texas wind PPAs, supporting compute for ranking and AI workloads.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/fort-worth/",
        title: "Meta Fort Worth",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-los-lunas",
    name: "Meta Los Lunas NM Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 34.8048,
    lng: -106.7335,
    city: "Los Lunas",
    region: "NM",
    country: "US",
    primaryPowerSource: "solar",
    utilitySlug: "pnm",
    coolingType: "air",
    description:
      "Meta's Valencia County, NM campus is matched by solar PPAs in New Mexico's high-desert grid.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/los-lunas/",
        title: "Meta Los Lunas",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-eagle-mountain",
    name: "Meta Eagle Mountain UT Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 40.3,
    lng: -112.005,
    city: "Eagle Mountain",
    region: "UT",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "rocky-mountain-power",
    coolingType: "air",
    description:
      "Meta's Utah campus, opened 2021, supported by dedicated solar generation under a Rocky Mountain Power green-tariff arrangement.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/eagle-mountain/",
        title: "Meta Eagle Mountain",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-sarpy-papillion",
    name: "Meta Sarpy County NE (Papillion)",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 41.1544,
    lng: -96.0422,
    city: "Papillion",
    region: "NE",
    country: "US",
    primaryPowerSource: "wind",
    utilitySlug: "omaha-public-power",
    coolingType: "air",
    description:
      "Meta's Sarpy County, NE campus near Omaha, opened 2020, matched by Nebraska wind farms via OPPD.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/sarpy-county/",
        title: "Meta Sarpy County",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-henrico",
    name: "Meta Henrico VA (White Oak) Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 37.5762,
    lng: -77.286,
    city: "Sandston",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "air",
    description:
      "Meta's Richmond-area campus at White Oak Technology Park, opened 2019, supports east-coast Facebook/Instagram traffic.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/henrico/",
        title: "Meta Henrico",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-dekalb",
    name: "Meta DeKalb IL Campus",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 41.93,
    lng: -88.78,
    city: "DeKalb",
    region: "IL",
    country: "US",
    primaryPowerSource: "wind",
    utilitySlug: "commonwealth-edison",
    coolingType: "air",
    description:
      "Meta's Illinois campus opened 2023, matched by Midwestern wind generation.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/dekalb/",
        title: "Meta DeKalb",
        type: "operator",
      },
    ],
  },
  // CORRECTED 2026-07-29. This site was previously seeded twice — here and as
  // "meta-temple-tx" in ai-native.ts — with contradictory, unsourced figures
  // (240MW vs 700MW planned, air vs direct-to-chip, aiDedicated false vs true).
  // The duplicate has been removed. Both original source URLs are dead (404),
  // and Meta publishes NO megawatt figure for Temple, so neither capacity was
  // ever evidenced. Values below come from Meta's own one-pager except capacityMw,
  // which is local reporting and is flagged as such in the description.
  {
    slug: "meta-temple",
    name: "Meta Temple TX Campus",
    operatorSlug: "meta",
    status: "operational",
    aiDedicated: true,
    lat: 31.0982,
    lng: -97.3428,
    city: "Temple",
    region: "TX",
    country: "US",
    capacityMw: 198,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "oncor",
    coolingType: "closed-loop",
    description:
      "Meta's Temple, Texas campus — two buildings, 760,000+ sq ft — which went live in July 2026 as the first facility to open with Meta's AI-optimised datacenter design. Meta states $1.2bn invested, groundbreaking in 2022 and ~100 operations roles, but publishes no capacity figure; the ~198MW here comes from local reporting, not from Meta. Power is supplied by Oncor on the ERCOT grid and matched 100% with renewables.",
    sources: [
      {
        url: "https://datacenters.atmeta.com/asset/temple-data-center-one-pager/",
        title: "Meta Temple Data Center (one-pager)",
        type: "operator",
      },
      {
        url: "https://www.kwtx.com/2026/07/22/meta-goes-live-temple-with-12-billion-ai-data-center/",
        title: "Meta goes live in Temple with $1.2 billion AI data center",
        type: "news",
        publishedAt: "2026-07-22",
      },
    ],
  },
  {
    slug: "meta-kansas-city",
    name: "Meta Kansas City MO Campus",
    operatorSlug: "meta",
    status: "under-construction",
    aiDedicated: false,
    lat: 39.1873,
    lng: -94.5493,
    city: "Kansas City",
    region: "MO",
    country: "US",
    capacityMwPlanned: 200,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "evergy",
    coolingType: "air",
    description:
      "Meta's $800M Kansas City campus announced in 2022 in the Northland area; matched with renewables under Evergy's green tariff.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/kansas-city/",
        title: "Meta Kansas City",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-cheyenne-wy",
    name: "Meta Cheyenne WY Campus",
    operatorSlug: "meta",
    status: "under-construction",
    aiDedicated: false,
    lat: 41.16,
    lng: -104.82,
    city: "Cheyenne",
    region: "WY",
    country: "US",
    capacityMwPlanned: 360,
    primaryPowerSource: "wind",
    utilitySlug: "black-hills-energy",
    coolingType: "air",
    description:
      "Meta announced an $800M Cheyenne campus in 2022, expanding Wyoming's hyperscaler footprint adjacent to Microsoft's existing site.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/cheyenne/",
        title: "Meta Cheyenne",
        type: "operator",
      },
    ],
  },
  {
    slug: "meta-newton-county",
    name: "Meta Newton County GA (Social Circle)",
    operatorSlug: "meta",
    status: "expanding",
    aiDedicated: false,
    lat: 33.6557,
    lng: -83.7196,
    city: "Social Circle",
    region: "GA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "georgia-power",
    coolingType: "air",
    description:
      "Meta's Stanton Springs/Newton County campus southeast of Atlanta, anchored on Walton EMC's Silicon Ranch solar PPAs.",
    sources: [
      {
        url: "https://www.meta.com/data-centers/newton-county/",
        title: "Meta Newton County",
        type: "operator",
      },
    ],
  },

  // --- AI-native / neoclouds ---
  {
    slug: "coreweave-las-vegas-lv1",
    name: "CoreWeave Las Vegas (LV1)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 36.0938,
    lng: -115.1839,
    city: "Las Vegas",
    region: "NV",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "nv-energy",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave's Las Vegas region hosts NVIDIA H100/H200 clusters in leased Switch capacity dedicated to AI training and inference.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave data centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-atlanta-at1",
    name: "CoreWeave Atlanta (AT1)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 33.749,
    lng: -84.388,
    city: "Atlanta",
    region: "GA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "georgia-power",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave's Atlanta-region GPU cloud presence using leased colocation capacity from Core Scientific / DataBank in metro Atlanta.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave data centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-chicago-ch1",
    name: "CoreWeave Chicago (CH1)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 41.8781,
    lng: -87.6298,
    city: "Chicago",
    region: "IL",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "commonwealth-edison",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave Chicago region GPU cloud in leased Midwest colocation supporting NVIDIA H100/H200 training fleets.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave data centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "coreweave-weehawken-nj",
    name: "CoreWeave Weehawken NJ (NY1)",
    operatorSlug: "coreweave",
    status: "operational",
    aiDedicated: true,
    lat: 40.7707,
    lng: -74.0246,
    city: "Weehawken",
    region: "NJ",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "pseg",
    coolingType: "direct-to-chip",
    description:
      "CoreWeave's New York-metro GPU region serving low-latency inference, originally housed in legacy New Jersey colocation.",
    sources: [
      {
        url: "https://www.coreweave.com/data-centers",
        title: "CoreWeave data centers",
        type: "operator",
      },
    ],
  },
  {
    slug: "crusoe-iceland-tx-permian",
    name: "Crusoe Iceland (Permian Basin) TX",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 31.85,
    lng: -102.36,
    city: "Midland",
    region: "TX",
    country: "US",
    primaryPowerSource: "gas",
    coolingType: "direct-to-chip",
    description:
      "Crusoe operates modular AI training datacenters in the Permian Basin, powering GPUs from otherwise-flared associated natural gas.",
    sources: [
      {
        url: "https://www.crusoe.ai/data-centers",
        title: "Crusoe data centers",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/crusoe-data-center-permian-basin/",
        title: "Crusoe Permian Basin coverage",
        type: "news",
      },
    ],
  },
  {
    slug: "crusoe-north-dakota",
    name: "Crusoe North Dakota Bakken Sites",
    operatorSlug: "crusoe",
    status: "operational",
    aiDedicated: true,
    lat: 47.7,
    lng: -103.3,
    city: "Watford City",
    region: "ND",
    country: "US",
    primaryPowerSource: "gas",
    coolingType: "air",
    description:
      "Crusoe's original modular flared-gas powered AI compute deployments in the Bakken oilfield of North Dakota.",
    sources: [
      {
        url: "https://www.crusoe.ai/",
        title: "Crusoe Energy",
        type: "operator",
      },
    ],
  },
  {
    slug: "lambda-allen-tx",
    name: "Lambda Labs 1-Click Cluster (Allen TX)",
    operatorSlug: "lambda",
    status: "operational",
    aiDedicated: true,
    lat: 33.103,
    lng: -96.671,
    city: "Allen",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "oncor",
    coolingType: "direct-to-chip",
    description:
      "Lambda's Texas GPU cloud anchor site hosting H100 and H200 1-Click Clusters in leased Compass / Cologix capacity.",
    sources: [
      {
        url: "https://lambdalabs.com/blog/introducing-1-click-clusters",
        title: "Lambda 1-Click Clusters",
        type: "operator",
      },
    ],
  },
  {
    slug: "voltage-park-dallas",
    name: "Voltage Park Dallas",
    operatorSlug: "voltage-park",
    status: "operational",
    aiDedicated: true,
    lat: 32.7767,
    lng: -96.797,
    city: "Dallas",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "oncor",
    coolingType: "direct-to-chip",
    description:
      "Voltage Park's H100 GPU cloud is anchored across multiple leased facilities including Dallas, providing 24,000+ GPU capacity to AI labs.",
    sources: [
      {
        url: "https://www.voltagepark.com/",
        title: "Voltage Park",
        type: "operator",
      },
      {
        url: "https://www.datacenterdynamics.com/en/news/voltage-park-launches-with-24000-h100-gpus/",
        title: "Voltage Park launch",
        type: "news",
      },
    ],
  },
  {
    slug: "nebius-kansas-city",
    name: "Nebius Kansas City MO",
    operatorSlug: "nebius",
    status: "operational",
    aiDedicated: true,
    lat: 39.0997,
    lng: -94.5786,
    city: "Kansas City",
    region: "MO",
    country: "US",
    capacityMw: 40,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "evergy",
    coolingType: "direct-to-chip",
    description:
      "Nebius (formerly Yandex N.V.) opened a Kansas City AI cloud cluster in 2024 with NVIDIA H200 GPUs in leased Patmos capacity.",
    sources: [
      {
        url: "https://nebius.com/blog/posts/nebius-launches-kansas-city-cluster",
        title: "Nebius Kansas City announcement",
        type: "pr",
      },
    ],
  },
  {
    slug: "cerebras-santa-clara-condor",
    name: "Cerebras Condor Galaxy (Santa Clara)",
    operatorSlug: "cerebras",
    status: "operational",
    aiDedicated: true,
    lat: 37.3541,
    lng: -121.9552,
    city: "Santa Clara",
    region: "CA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "silicon-valley-power",
    coolingType: "direct-to-chip",
    description:
      "Cerebras and G42 operate Condor Galaxy AI supercomputer nodes hosted in Colovore Santa Clara, training large language models on CS-3 wafer-scale systems.",
    sources: [
      {
        url: "https://www.cerebras.net/blog/condor-galaxy",
        title: "Cerebras Condor Galaxy",
        type: "operator",
      },
    ],
  },
  {
    slug: "together-ai-pittsburgh",
    name: "Together AI Pittsburgh Cluster",
    operatorSlug: "together-ai",
    status: "operational",
    aiDedicated: true,
    lat: 40.4406,
    lng: -79.9959,
    city: "Pittsburgh",
    region: "PA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "duquesne-light",
    coolingType: "direct-to-chip",
    description:
      "Together AI hosts H100/H200 training capacity in leased Pittsburgh-area capacity supporting open-source model fine-tuning workloads.",
    sources: [
      {
        url: "https://www.together.ai/blog",
        title: "Together AI blog",
        type: "operator",
      },
    ],
  },
  {
    slug: "hut8-medicine-hat-ab",
    name: "Hut 8 Medicine Hat (AB)",
    operatorSlug: "hut8",
    status: "operational",
    aiDedicated: true,
    lat: 50.0405,
    lng: -110.6764,
    city: "Medicine Hat",
    region: "AB",
    country: "CA",
    capacityMw: 109,
    primaryPowerSource: "gas",
    utilitySlug: "atco-electric",
    coolingType: "air",
    description:
      "Hut 8's Medicine Hat campus, originally bitcoin mining, is being converted to high-performance compute and AI workloads under the company's HPC strategy.",
    sources: [
      { url: "https://hut8.io/sites/", title: "Hut 8 sites", type: "operator" },
    ],
  },

  // --- Major colos with AI deployments ---
  {
    slug: "equinix-dc2-ashburn",
    name: "Equinix DC2 Ashburn",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 39.0157,
    lng: -77.4561,
    city: "Ashburn",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "Equinix's flagship Ashburn DC2 IBX is a top global interconnection hub anchoring carrier-dense connectivity in Data Center Alley.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/washington-dc-data-centers/dc2",
        title: "Equinix DC2",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-dc10-ashburn",
    name: "Equinix DC10 Ashburn",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 39.018,
    lng: -77.457,
    city: "Ashburn",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "Equinix DC10 IBX in Ashburn is a high-density colocation hub adjacent to DC2/DC11, hosting cloud on-ramps for AWS, Azure, and Google.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/washington-dc-data-centers/dc10",
        title: "Equinix DC10",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-sv1-san-jose",
    name: "Equinix SV1 San Jose",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 37.2436,
    lng: -121.7836,
    city: "San Jose",
    region: "CA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "pge",
    coolingType: "closed-loop",
    description:
      "Equinix SV1 in San Jose is the original Silicon Valley interconnection hub, central to West-Coast peering.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/silicon-valley-data-centers/sv1",
        title: "Equinix SV1",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ny4-secaucus",
    name: "Equinix NY4 Secaucus",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 40.7867,
    lng: -74.0541,
    city: "Secaucus",
    region: "NJ",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "pseg",
    coolingType: "closed-loop",
    description:
      "Equinix NY4 in Secaucus is the largest carrier-dense IBX in the New York metro and a top global financial-services interconnection hub.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/new-york-data-centers/ny4",
        title: "Equinix NY4",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-ch2-chicago",
    name: "Equinix CH2 Chicago",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 41.8841,
    lng: -87.6428,
    city: "Chicago",
    region: "IL",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "commonwealth-edison",
    coolingType: "closed-loop",
    description:
      "Equinix CH2 at 350 East Cermak is one of the largest carrier hotels in the US and the financial-trading hub for Chicago derivative exchanges.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/chicago-data-centers/ch2",
        title: "Equinix CH2",
        type: "operator",
      },
    ],
  },
  {
    slug: "equinix-tr2-toronto",
    name: "Equinix TR2 Toronto",
    operatorSlug: "equinix",
    status: "operational",
    aiDedicated: false,
    lat: 43.6532,
    lng: -79.3832,
    city: "Toronto",
    region: "ON",
    country: "CA",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "toronto-hydro",
    coolingType: "closed-loop",
    description:
      "Equinix TR2 is Toronto's premier carrier-dense IBX and a major Canadian peering and cloud on-ramp facility.",
    sources: [
      {
        url: "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr2",
        title: "Equinix TR2",
        type: "operator",
      },
    ],
  },
  {
    slug: "digital-realty-iad-ashburn",
    name: "Digital Realty IAD Campus (Ashburn)",
    operatorSlug: "digital-realty",
    status: "expanding",
    aiDedicated: false,
    lat: 39.0247,
    lng: -77.481,
    city: "Ashburn",
    region: "VA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "Digital Realty's Ashburn campus is one of the largest hyperscale-leased footprints in Loudoun County's Data Center Alley.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/americas/northern-virginia",
        title: "Digital Realty Northern Virginia",
        type: "operator",
      },
    ],
  },
  {
    slug: "digital-realty-douglasville",
    name: "Digital Realty Douglasville GA",
    operatorSlug: "digital-realty",
    status: "expanding",
    aiDedicated: false,
    lat: 33.7515,
    lng: -84.7477,
    city: "Douglasville",
    region: "GA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "georgia-power",
    coolingType: "closed-loop",
    description:
      "Digital Realty's Atlanta-Douglasville campus is a 300+ MW hyperscale-leased site forming part of Atlanta's largest datacenter cluster.",
    sources: [
      {
        url: "https://www.digitalrealty.com/data-centers/americas/atlanta",
        title: "Digital Realty Atlanta",
        type: "operator",
      },
    ],
  },
  {
    slug: "qts-manassas",
    name: "QTS Manassas Mega Campus",
    operatorSlug: "qts",
    status: "expanding",
    aiDedicated: false,
    lat: 38.755,
    lng: -77.4753,
    city: "Manassas",
    region: "VA",
    country: "US",
    capacityMwPlanned: 750,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "dominion-energy",
    coolingType: "closed-loop",
    description:
      "QTS' Prince William County, VA mega-campus is one of the largest hyperscale-leased projects under construction in PJM, anchored by Microsoft.",
    sources: [
      {
        url: "https://www.qtsdatacenters.com/data-centers/manassas",
        title: "QTS Manassas",
        type: "operator",
      },
    ],
  },
  {
    slug: "qts-suwanee-atlanta",
    name: "QTS Atlanta-Suwanee",
    operatorSlug: "qts",
    status: "operational",
    aiDedicated: false,
    lat: 34.0515,
    lng: -84.0713,
    city: "Suwanee",
    region: "GA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "georgia-power",
    coolingType: "closed-loop",
    description:
      "QTS' Atlanta-Suwanee mega-campus is a key southeast hyperscale-leased deployment with multiple buildings on a 250-acre site.",
    sources: [
      {
        url: "https://www.qtsdatacenters.com/data-centers/atlanta-suwanee",
        title: "QTS Atlanta-Suwanee",
        type: "operator",
      },
    ],
  },
  {
    slug: "qts-irving-tx",
    name: "QTS Irving TX (Dallas)",
    operatorSlug: "qts",
    status: "operational",
    aiDedicated: false,
    lat: 32.8573,
    lng: -96.97,
    city: "Irving",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "oncor",
    coolingType: "closed-loop",
    description:
      "QTS' Irving, TX campus is a multi-tenant hyperscale-leased site near the DFW carrier hotels.",
    sources: [
      {
        url: "https://www.qtsdatacenters.com/data-centers/irving",
        title: "QTS Irving",
        type: "operator",
      },
    ],
  },
  {
    slug: "cyrusone-houston-west",
    name: "CyrusOne Houston West Campus",
    operatorSlug: "cyrusone",
    status: "operational",
    aiDedicated: false,
    lat: 29.787,
    lng: -95.731,
    city: "Houston",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "centerpoint-energy",
    coolingType: "closed-loop",
    description:
      "CyrusOne's Houston West (Galleria) campus is a large multi-tenant colocation site supporting energy-sector and cloud workloads.",
    sources: [
      {
        url: "https://cyrusone.com/data-center-locations/north-america/houston-tx/",
        title: "CyrusOne Houston",
        type: "operator",
      },
    ],
  },
  {
    slug: "cyrusone-dallas-carrollton",
    name: "CyrusOne Dallas-Carrollton",
    operatorSlug: "cyrusone",
    status: "operational",
    aiDedicated: false,
    lat: 32.989,
    lng: -96.89,
    city: "Carrollton",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "oncor",
    coolingType: "closed-loop",
    description:
      "CyrusOne's Carrollton campus is a major DFW colocation hub, leased by hyperscalers and enterprises across multiple buildings.",
    sources: [
      {
        url: "https://cyrusone.com/data-center-locations/north-america/carrollton-tx/",
        title: "CyrusOne Carrollton",
        type: "operator",
      },
    ],
  },
  {
    slug: "iron-mountain-boyers-pa",
    name: "Iron Mountain Boyers PA (WPA-1)",
    operatorSlug: "iron-mountain",
    status: "operational",
    aiDedicated: false,
    lat: 41.0734,
    lng: -79.9131,
    city: "Boyers",
    region: "PA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "fes-penn-power",
    coolingType: "closed-loop",
    description:
      "Iron Mountain's underground WPA-1 limestone mine facility in Butler County, PA hosts federal and enterprise data with naturally cool ambient conditions.",
    sources: [
      {
        url: "https://www.ironmountain.com/data-centers/data-center-locations/wpa-1",
        title: "Iron Mountain WPA-1",
        type: "operator",
      },
    ],
  },
  {
    slug: "ntt-sacramento-sv1",
    name: "NTT Sacramento SV1",
    operatorSlug: "ntt",
    status: "operational",
    aiDedicated: false,
    lat: 38.5816,
    lng: -121.4944,
    city: "Sacramento",
    region: "CA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "smud",
    coolingType: "closed-loop",
    description:
      "NTT's Sacramento SV1 datacenter (formerly RagingWire CA3) provides hyperscale wholesale capacity in northern California outside fault zones.",
    sources: [
      {
        url: "https://services.global.ntt/en-us/services-and-products/data-centers/americas/sacramento",
        title: "NTT Sacramento",
        type: "operator",
      },
    ],
  },

  // --- Emerging / regional ---
  {
    slug: "vantage-quincy-wa",
    name: "Vantage Quincy WA Campus",
    operatorSlug: "vantage",
    status: "expanding",
    aiDedicated: false,
    lat: 47.2336,
    lng: -119.9,
    city: "Quincy",
    region: "WA",
    country: "US",
    capacityMwPlanned: 192,
    primaryPowerSource: "hydro",
    utilitySlug: "grant-county-pud",
    coolingType: "closed-loop",
    description:
      "Vantage's Quincy WA campus is a wholesale hyperscale site adjacent to Microsoft's campus, leveraging Grant PUD hydro power.",
    sources: [
      {
        url: "https://vantage-dc.com/data-centers/north-america/quincy/",
        title: "Vantage Quincy",
        type: "operator",
      },
    ],
  },
  {
    slug: "vantage-santa-clara-v6",
    name: "Vantage Santa Clara V6",
    operatorSlug: "vantage",
    status: "operational",
    aiDedicated: false,
    lat: 37.3801,
    lng: -121.972,
    city: "Santa Clara",
    region: "CA",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "silicon-valley-power",
    coolingType: "closed-loop",
    description:
      "Vantage's V6 campus in Santa Clara serves Bay Area hyperscalers with a multi-building wholesale footprint on Silicon Valley Power.",
    sources: [
      {
        url: "https://vantage-dc.com/data-centers/north-america/santa-clara/",
        title: "Vantage Santa Clara",
        type: "operator",
      },
    ],
  },
  {
    slug: "aligned-phoenix-phx-02",
    name: "Aligned Phoenix PHX-02",
    operatorSlug: "aligned",
    status: "expanding",
    aiDedicated: false,
    lat: 33.4942,
    lng: -111.9261,
    city: "Phoenix",
    region: "AZ",
    country: "US",
    capacityMwPlanned: 174,
    primaryPowerSource: "grid-mixed",
    utilitySlug: "salt-river-project",
    coolingType: "closed-loop",
    description:
      "Aligned's PHX-02 mega-campus in metro Phoenix uses the Delta3 cooling array and serves AI/HPC tenants on SRP power.",
    sources: [
      {
        url: "https://www.aligneddc.com/data-centers/phoenix-phx-02",
        title: "Aligned PHX-02",
        type: "operator",
      },
    ],
  },
  {
    slug: "aligned-salt-lake-city",
    name: "Aligned Salt Lake City SLC-01",
    operatorSlug: "aligned",
    status: "operational",
    aiDedicated: false,
    lat: 40.7608,
    lng: -111.891,
    city: "West Jordan",
    region: "UT",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "rocky-mountain-power",
    coolingType: "closed-loop",
    description:
      "Aligned SLC-01 in West Jordan is one of the largest wholesale datacenters in Utah's Wasatch Front, serving cloud and AI tenants.",
    sources: [
      {
        url: "https://www.aligneddc.com/data-centers/salt-lake-city-slc-01",
        title: "Aligned SLC-01",
        type: "operator",
      },
    ],
  },
  {
    slug: "aligned-dallas-dfw-02",
    name: "Aligned Dallas DFW-02",
    operatorSlug: "aligned",
    status: "expanding",
    aiDedicated: false,
    lat: 32.6527,
    lng: -96.8519,
    city: "Dallas",
    region: "TX",
    country: "US",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "oncor",
    coolingType: "closed-loop",
    description:
      "Aligned's DFW-02 is a multi-building wholesale campus in southern Dallas serving large hyperscale and AI deployments on the ERCOT grid.",
    sources: [
      {
        url: "https://www.aligneddc.com/data-centers/dallas-dfw-02",
        title: "Aligned DFW-02",
        type: "operator",
      },
    ],
  },
  {
    slug: "switch-citadel-tahoe-reno",
    name: "Switch Citadel Campus (Tahoe Reno)",
    operatorSlug: "switch",
    status: "expanding",
    aiDedicated: false,
    lat: 39.5468,
    lng: -119.4341,
    city: "McCarran",
    region: "NV",
    country: "US",
    capacityMwPlanned: 650,
    primaryPowerSource: "solar",
    utilitySlug: "nv-energy",
    coolingType: "closed-loop",
    description:
      "Switch's Citadel campus at Tahoe Reno Industrial Center is planned as one of the largest datacenters in the world, matched with onsite solar.",
    sources: [
      {
        url: "https://www.switch.com/the-citadel/",
        title: "Switch Citadel",
        type: "operator",
      },
    ],
  },
  // ADDED 2026-07-29. Permit and subsidy records already referenced
  // "apple-maiden-nc", but no datacenter record existed, so those findings were
  // silently dropped at seed time. Apple publishes no capacity figure for the
  // campus; MW is therefore omitted rather than estimated. Coordinates are the
  // Maiden town centroid, not a surveyed parcel.
  {
    slug: "apple-maiden-nc",
    name: "Apple Maiden NC (iDataCenter)",
    operatorSlug: "apple",
    status: "operational",
    aiDedicated: false,
    lat: 35.5757,
    lng: -81.2112,
    city: "Maiden",
    region: "NC",
    country: "US",
    primaryPowerSource: "hybrid",
    utilitySlug: "duke-energy",
    description:
      "Apple's first large owned datacenter campus, opened in 2010 on 183 acres in Maiden, North Carolina, and now over 1 million sq ft across multiple buildings serving iCloud and Apple services. Grid power comes from Duke Energy, supplemented on site by three 20MW solar farms and a 10MW biogas fuel cell installation generating a reported 244 million kWh of renewable energy per year. Apple has invested roughly $3bn in the campus and committed a further $448m in April 2021. No IT load figure is published.",
    sources: [
      {
        url: "https://baxtel.com/data-center/apple-maiden-north-carolina",
        title: "Apple Maiden North Carolina Data Center",
        type: "other",
      },
      {
        url: "https://www.datacenterknowledge.com/build-design/a-look-inside-apple-s-idatacenter-in-north-carolina",
        title: "A Look Inside Apple's iDataCenter in North Carolina",
        type: "news",
      },
    ],
  },
  {
    slug: "switch-pyramid-grand-rapids",
    name: "Switch Pyramid Campus (Grand Rapids MI)",
    operatorSlug: "switch",
    status: "operational",
    aiDedicated: false,
    lat: 42.8806,
    lng: -85.5228,
    city: "Gaines Township",
    region: "MI",
    country: "US",
    primaryPowerSource: "solar",
    utilitySlug: "consumers-energy",
    coolingType: "closed-loop",
    description:
      "Switch's Pyramid campus in Michigan is the company's flagship Midwest datacenter, matched 100% by solar generation under Consumers Energy.",
    sources: [
      {
        url: "https://www.switch.com/the-pyramid/",
        title: "Switch Pyramid",
        type: "operator",
      },
    ],
  },
  {
    slug: "switch-the-core-las-vegas",
    name: "Switch The Core Campus (Las Vegas)",
    operatorSlug: "switch",
    status: "operational",
    aiDedicated: false,
    lat: 36.082,
    lng: -115.099,
    city: "Las Vegas",
    region: "NV",
    country: "US",
    primaryPowerSource: "solar",
    utilitySlug: "nv-energy",
    coolingType: "closed-loop",
    description:
      "Switch's The Core Campus in Las Vegas is a flagship Tier-IV-design colocation site hosting AI tenants including CoreWeave and major cloud operators.",
    sources: [
      {
        url: "https://www.switch.com/the-core/",
        title: "Switch The Core",
        type: "operator",
      },
    ],
  },
  {
    slug: "cologix-mtl-3-montreal",
    name: "Cologix MTL-3 Montréal",
    operatorSlug: "cologix",
    status: "operational",
    aiDedicated: false,
    lat: 45.4972,
    lng: -73.5728,
    city: "Montréal",
    region: "QC",
    country: "CA",
    primaryPowerSource: "hydro",
    utilitySlug: "hydro-quebec",
    coolingType: "closed-loop",
    description:
      "Cologix MTL-3 is a flagship Montréal interconnection hub leveraging Hydro-Québec's renewable hydro generation.",
    sources: [
      {
        url: "https://cologix.com/data-centers/montreal/mtl3/",
        title: "Cologix MTL-3",
        type: "operator",
      },
    ],
  },
  {
    slug: "cologix-tor-1-toronto",
    name: "Cologix TOR-1 Toronto",
    operatorSlug: "cologix",
    status: "operational",
    aiDedicated: false,
    lat: 43.6452,
    lng: -79.381,
    city: "Toronto",
    region: "ON",
    country: "CA",
    primaryPowerSource: "grid-mixed",
    utilitySlug: "toronto-hydro",
    coolingType: "closed-loop",
    description:
      "Cologix TOR-1 at 151 Front Street is Canada's most densely-interconnected carrier hotel and a major peering hub.",
    sources: [
      {
        url: "https://cologix.com/data-centers/toronto/tor1/",
        title: "Cologix TOR-1",
        type: "operator",
      },
    ],
  },
  {
    slug: "kio-queretaro-qro1",
    name: "KIO Networks Querétaro QRO1",
    operatorSlug: "kio-networks",
    status: "operational",
    aiDedicated: false,
    lat: 20.7012,
    lng: -100.4456,
    city: "Querétaro",
    region: "QUE",
    country: "MX",
    primaryPowerSource: "grid-mixed",
    coolingType: "closed-loop",
    description:
      "KIO's Querétaro QRO1 is one of Latin America's largest carrier-neutral colocation campuses, anchoring Mexico's hyperscaler cluster.",
    sources: [
      { url: "https://www.kio.com/", title: "KIO Networks", type: "operator" },
    ],
  },
  {
    slug: "ascenty-queretaro",
    name: "Ascenty Querétaro QRO1",
    operatorSlug: "ascenty",
    status: "operational",
    aiDedicated: false,
    lat: 20.6,
    lng: -100.4,
    city: "Querétaro",
    region: "QUE",
    country: "MX",
    primaryPowerSource: "grid-mixed",
    coolingType: "closed-loop",
    description:
      "Ascenty (Digital Realty / Brookfield JV) operates a Querétaro hyperscale campus serving AWS, Microsoft and Google in Mexico Central.",
    sources: [
      {
        url: "https://www.ascenty.com/en/data-center/queretaro/",
        title: "Ascenty Querétaro",
        type: "operator",
      },
    ],
  },
];

// === NEW BRANDS NEEDED (add these to BRANDS array) ===
export const NA_BRANDS: SeedBrand[] = [
  // Operators
  {
    slug: "aws",
    canonicalName: "Amazon Web Services",
    website: "https://aws.amazon.com",
  },
  {
    slug: "microsoft",
    canonicalName: "Microsoft",
    website: "https://www.microsoft.com",
  },
  {
    slug: "google",
    canonicalName: "Google",
    website: "https://cloud.google.com",
  },
  { slug: "meta", canonicalName: "Meta", website: "https://www.meta.com" },
  {
    slug: "coreweave",
    canonicalName: "CoreWeave",
    website: "https://www.coreweave.com",
  },
  {
    slug: "crusoe",
    canonicalName: "Crusoe Energy",
    website: "https://www.crusoe.ai",
  },
  {
    slug: "lambda",
    canonicalName: "Lambda Labs",
    website: "https://lambdalabs.com",
  },
  {
    slug: "voltage-park",
    canonicalName: "Voltage Park",
    website: "https://www.voltagepark.com",
  },
  { slug: "nebius", canonicalName: "Nebius", website: "https://nebius.com" },
  {
    slug: "cerebras",
    canonicalName: "Cerebras Systems",
    website: "https://www.cerebras.net",
  },
  {
    slug: "together-ai",
    canonicalName: "Together AI",
    website: "https://www.together.ai",
  },
  { slug: "hut8", canonicalName: "Hut 8", website: "https://hut8.io" },
  {
    slug: "equinix",
    canonicalName: "Equinix",
    website: "https://www.equinix.com",
  },
  {
    slug: "digital-realty",
    canonicalName: "Digital Realty",
    website: "https://www.digitalrealty.com",
  },
  {
    slug: "qts",
    canonicalName: "QTS Data Centers",
    website: "https://www.qtsdatacenters.com",
  },
  {
    slug: "cyrusone",
    canonicalName: "CyrusOne",
    website: "https://cyrusone.com",
  },
  {
    slug: "iron-mountain",
    canonicalName: "Iron Mountain",
    website: "https://www.ironmountain.com",
  },
  {
    slug: "ntt",
    canonicalName: "NTT Global Data Centers",
    website: "https://services.global.ntt",
  },
  {
    slug: "vantage",
    canonicalName: "Vantage Data Centers",
    website: "https://vantage-dc.com",
  },
  {
    slug: "aligned",
    canonicalName: "Aligned Data Centers",
    website: "https://www.aligneddc.com",
  },
  {
    slug: "switch",
    canonicalName: "Switch",
    website: "https://www.switch.com",
  },
  { slug: "cologix", canonicalName: "Cologix", website: "https://cologix.com" },
  {
    slug: "kio-networks",
    canonicalName: "KIO Networks",
    website: "https://www.kio.com",
  },
  {
    slug: "ascenty",
    canonicalName: "Ascenty",
    website: "https://www.ascenty.com",
  },

  // Utilities
  {
    slug: "dominion-energy",
    canonicalName: "Dominion Energy",
    website: "https://www.dominionenergy.com",
  },
  {
    slug: "umatilla-electric",
    canonicalName: "Umatilla Electric Cooperative",
    website: "https://www.umatillaelectric.com",
  },
  {
    slug: "aep-ohio",
    canonicalName: "AEP Ohio",
    website: "https://www.aepohio.com",
  },
  {
    slug: "hydro-quebec",
    canonicalName: "Hydro-Québec",
    website: "https://www.hydroquebec.com",
  },
  { slug: "enmax", canonicalName: "ENMAX", website: "https://www.enmax.com" },
  {
    slug: "grant-county-pud",
    canonicalName: "Grant County PUD",
    website: "https://www.grantpud.org",
  },
  {
    slug: "cps-energy",
    canonicalName: "CPS Energy",
    website: "https://www.cpsenergy.com",
  },
  {
    slug: "black-hills-energy",
    canonicalName: "Black Hills Energy",
    website: "https://www.blackhillsenergy.com",
  },
  {
    slug: "georgia-power",
    canonicalName: "Georgia Power",
    website: "https://www.georgiapower.com",
  },
  {
    slug: "mid-american-energy",
    canonicalName: "MidAmerican Energy",
    website: "https://www.midamericanenergy.com",
  },
  // Added 2026-07-29. Referenced as a utilitySlug by aws-anthropic-new-carlisle-in
  // but never declared, so that site seeded with a null utility. A distinct AEP
  // operating company from aep-ohio, serving Indiana and Michigan.
  {
    slug: "aep-indiana-michigan-power",
    canonicalName: "AEP Indiana Michigan Power",
    website: "https://www.indianamichiganpower.com",
  },
  {
    slug: "grand-river-dam-authority",
    canonicalName: "Grand River Dam Authority",
    website: "https://www.grda.com",
  },
  {
    slug: "duke-energy",
    canonicalName: "Duke Energy",
    website: "https://www.duke-energy.com",
  },
  {
    slug: "santee-cooper",
    canonicalName: "Santee Cooper",
    website: "https://www.santeecooper.com",
  },
  {
    slug: "nv-energy",
    canonicalName: "NV Energy",
    website: "https://www.nvenergy.com",
  },
  {
    slug: "pacific-power",
    canonicalName: "Pacific Power",
    website: "https://www.pacificpower.net",
  },
  {
    slug: "oncor",
    canonicalName: "Oncor Electric Delivery",
    website: "https://www.oncor.com",
  },
  {
    slug: "pnm",
    canonicalName: "PNM Resources",
    website: "https://www.pnm.com",
  },
  {
    slug: "rocky-mountain-power",
    canonicalName: "Rocky Mountain Power",
    website: "https://www.rockymountainpower.net",
  },
  {
    slug: "omaha-public-power",
    canonicalName: "Omaha Public Power District",
    website: "https://www.oppd.com",
  },
  {
    slug: "commonwealth-edison",
    canonicalName: "Commonwealth Edison",
    website: "https://www.comed.com",
  },
  {
    slug: "evergy",
    canonicalName: "Evergy",
    website: "https://www.evergy.com",
  },
  { slug: "pseg", canonicalName: "PSEG", website: "https://www.pseg.com" },
  {
    slug: "duquesne-light",
    canonicalName: "Duquesne Light",
    website: "https://www.duquesnelight.com",
  },
  {
    slug: "atco-electric",
    canonicalName: "ATCO Electric",
    website: "https://electric.atco.com",
  },
  {
    slug: "pge",
    canonicalName: "Pacific Gas and Electric",
    website: "https://www.pge.com",
  },
  {
    slug: "silicon-valley-power",
    canonicalName: "Silicon Valley Power",
    website: "https://www.siliconvalleypower.com",
  },
  {
    slug: "toronto-hydro",
    canonicalName: "Toronto Hydro",
    website: "https://www.torontohydro.com",
  },
  {
    slug: "centerpoint-energy",
    canonicalName: "CenterPoint Energy",
    website: "https://www.centerpointenergy.com",
  },
  {
    slug: "fes-penn-power",
    canonicalName: "Penn Power (FirstEnergy)",
    website: "https://www.firstenergycorp.com/penn_power.html",
  },
  {
    slug: "smud",
    canonicalName: "Sacramento Municipal Utility District",
    website: "https://www.smud.org",
  },
  {
    slug: "salt-river-project",
    canonicalName: "Salt River Project",
    website: "https://www.srpnet.com",
  },
  {
    slug: "consumers-energy",
    canonicalName: "Consumers Energy",
    website: "https://www.consumersenergy.com",
  },
];
