import type { DatacenterSource } from "@/server/db/schema";

export type SeedPermit = {
  datacenterSlug: string;
  kind:
    | "zoning"
    | "environmental"
    | "water"
    | "grid-interconnect"
    | "building"
    | "other";
  issuingBody: string;
  appliedDate?: string;
  issuedDate?: string;
  status: "pending" | "granted" | "denied" | "withdrawn";
  sources: DatacenterSource[];
};

export const PERMITS: SeedPermit[] = [
  { datacenterSlug: "microsoft-mt-pleasant", kind: "zoning", issuingBody: "Mount Pleasant Plan Commission", appliedDate: "2023-03-15", issuedDate: "2023-04-17", status: "granted", sources: [{ url: "https://www.jsonline.com/story/news/local/2023/04/17/", title: "Mount Pleasant approves Microsoft data center", type: "news" }] },
  { datacenterSlug: "microsoft-mt-pleasant", kind: "zoning", issuingBody: "Mount Pleasant Village Board", appliedDate: "2024-02-01", issuedDate: "2024-03-04", status: "granted", sources: [{ url: "https://wisconsinexaminer.com/2024/03/05/", title: "Mt Pleasant approves second MS expansion", type: "news" }] },
  { datacenterSlug: "microsoft-mt-pleasant", kind: "environmental", issuingBody: "Wisconsin DNR", issuedDate: "2023-08-22", status: "granted", sources: [{ url: "https://dnr.wisconsin.gov/topic/AirPermits", title: "WI DNR air permit lookup", type: "permit" }] },
  { datacenterSlug: "microsoft-mt-pleasant", kind: "water", issuingBody: "Racine Water Utility / Lake Michigan diversion", issuedDate: "2023-11-10", status: "granted", sources: [{ url: "https://www.jsonline.com/story/news/2023/11/10/", title: "Lake Michigan water tap approved", type: "news" }] },
  { datacenterSlug: "meta-hyperion-richland", kind: "environmental", issuingBody: "Louisiana DEQ", appliedDate: "2025-02-04", status: "pending", sources: [{ url: "https://edms.deq.louisiana.gov/app/doc/querydef.aspx", title: "LDEQ EDMS public records", type: "filing" }] },
  { datacenterSlug: "meta-hyperion-richland", kind: "zoning", issuingBody: "Richland Parish Police Jury", issuedDate: "2024-12-12", status: "granted", sources: [{ url: "https://www.theadvocate.com/baton_rouge/", title: "Richland Parish OKs zoning for Meta", type: "news" }] },
  { datacenterSlug: "meta-hyperion-richland", kind: "water", issuingBody: "Louisiana DEQ - Water Quality", appliedDate: "2025-03-20", status: "pending", sources: [{ url: "https://www.nola.com/news/environment/", title: "Meta files LDEQ water discharge application", type: "news" }] },
  { datacenterSlug: "meta-hyperion-richland", kind: "grid-interconnect", issuingBody: "Entergy Louisiana / MISO", appliedDate: "2024-10-01", status: "pending", sources: [{ url: "https://www.misoenergy.org/planning/generator-interconnection/", title: "MISO interconnection queue", type: "filing" }] },
  { datacenterSlug: "meta-eagle-mountain", kind: "zoning", issuingBody: "Eagle Mountain City Council", issuedDate: "2018-06-19", status: "granted", sources: [{ url: "https://www.deseret.com/2018/6/20/", title: "Eagle Mountain approves Facebook data center", type: "news" }] },
  { datacenterSlug: "meta-eagle-mountain", kind: "environmental", issuingBody: "Utah Division of Air Quality", issuedDate: "2018-08-30", status: "granted", sources: [{ url: "https://deq.utah.gov/air-quality/approval-orders", title: "Utah DAQ Approval Orders", type: "permit" }] },
  { datacenterSlug: "meta-eagle-mountain", kind: "water", issuingBody: "Utah Division of Water Rights", issuedDate: "2019-04-10", status: "granted", sources: [{ url: "https://www.sltrib.com/news/environment/2019/04/15/", title: "Eagle Mountain Facebook campus secures groundwater", type: "news" }] },
  { datacenterSlug: "meta-sarpy-county", kind: "zoning", issuingBody: "Sarpy County Planning Commission", issuedDate: "2019-04-09", status: "granted", sources: [{ url: "https://omaha.com/business/local/", title: "Sarpy County approves Facebook rezoning", type: "news" }] },
  { datacenterSlug: "meta-newton-county", kind: "zoning", issuingBody: "Newton County Board of Commissioners", issuedDate: "2018-03-06", status: "granted", sources: [{ url: "https://www.ajc.com/business/", title: "Newton County approves Facebook Stanton Springs", type: "news" }] },
  { datacenterSlug: "meta-newton-county", kind: "environmental", issuingBody: "Georgia EPD", issuedDate: "2018-09-14", status: "granted", sources: [{ url: "https://epd.georgia.gov/air-protection-branch/permits", title: "Georgia EPD Air Protection", type: "permit" }] },
  { datacenterSlug: "google-the-dalles", kind: "water", issuingBody: "City of The Dalles", appliedDate: "2021-01-25", issuedDate: "2022-04-25", status: "granted", sources: [{ url: "https://www.opb.org/article/2022/04/25/", title: "Google water deal approved by The Dalles after lawsuit", type: "news" }, { url: "https://apnews.com/article/google-data-center-water-the-dalles-oregon", title: "AP: Google's secret water use settled", type: "news" }] },
  { datacenterSlug: "google-the-dalles", kind: "zoning", issuingBody: "Wasco County / The Dalles Planning", issuedDate: "2022-06-13", status: "granted", sources: [{ url: "https://www.thedalleschronicle.com/news/", title: "The Dalles approves third Google site", type: "news" }] },
  { datacenterSlug: "aws-northern-virginia-pjm", kind: "zoning", issuingBody: "Loudoun County Board of Supervisors", appliedDate: "2022-05-01", issuedDate: "2023-12-12", status: "granted", sources: [{ url: "https://www.loudounnow.com/news/", title: "Loudoun supervisors approve AWS rezoning", type: "news" }] },
  { datacenterSlug: "aws-northern-virginia-pjm", kind: "zoning", issuingBody: "Loudoun County Board of Supervisors", appliedDate: "2023-04-10", status: "denied", sources: [{ url: "https://www.loudounnow.com/news/", title: "Loudoun denies AWS rezoning along Goose Creek", type: "news" }] },
  { datacenterSlug: "aws-northern-virginia-pjm", kind: "environmental", issuingBody: "Virginia DEQ", issuedDate: "2024-03-15", status: "granted", sources: [{ url: "https://www.deq.virginia.gov/permits-regulations/permits/air", title: "VA DEQ air permit database", type: "permit" }] },
  { datacenterSlug: "aws-northern-virginia-pjm", kind: "grid-interconnect", issuingBody: "PJM Interconnection", appliedDate: "2022-02-01", status: "pending", sources: [{ url: "https://www.pjm.com/planning/services-requests/interconnection-queues", title: "PJM interconnection queue", type: "filing" }] },
  { datacenterSlug: "aws-us-east-2-new-albany", kind: "zoning", issuingBody: "City of New Albany", issuedDate: "2022-06-28", status: "granted", sources: [{ url: "https://www.dispatch.com/story/business/2022/06/28/", title: "New Albany rezones for AWS", type: "news" }] },
  { datacenterSlug: "aws-us-east-2-new-albany", kind: "environmental", issuingBody: "Ohio EPA", issuedDate: "2023-02-17", status: "granted", sources: [{ url: "https://epa.ohio.gov/divisions-and-offices/air-pollution-control/permitting/permits-issued", title: "Ohio EPA air permits", type: "permit" }] },
  { datacenterSlug: "microsoft-quincy-columbia", kind: "zoning", issuingBody: "Grant County Planning", issuedDate: "2021-09-14", status: "granted", sources: [{ url: "https://www.columbiabasinherald.com/news/", title: "Grant County clears Microsoft Quincy expansion", type: "news" }] },
  { datacenterSlug: "microsoft-quincy-columbia", kind: "water", issuingBody: "Washington Dept of Ecology", appliedDate: "2022-08-12", issuedDate: "2023-05-18", status: "granted", sources: [{ url: "https://ecology.wa.gov/water-shorelines/water-supply/water-rights", title: "WA Ecology water rights", type: "permit" }] },
  { datacenterSlug: "microsoft-quincy-columbia", kind: "environmental", issuingBody: "Washington Dept of Ecology - Air Quality", issuedDate: "2022-12-05", status: "granted", sources: [{ url: "https://ecology.wa.gov/regulations-permits/permits-certifications/air-quality-permits", title: "WA Ecology air quality permits", type: "permit" }] },
  { datacenterSlug: "stargate-abilene", kind: "zoning", issuingBody: "Taylor County / City of Abilene", appliedDate: "2024-08-05", issuedDate: "2024-09-23", status: "granted", sources: [{ url: "https://www.abilenetx.gov/government/agendas-minutes", title: "Abilene City Council minutes", type: "filing" }] },
  { datacenterSlug: "stargate-abilene", kind: "environmental", issuingBody: "Texas Commission on Environmental Quality (TCEQ)", appliedDate: "2024-10-30", issuedDate: "2025-01-21", status: "granted", sources: [{ url: "https://www.tceq.texas.gov/permitting/air", title: "TCEQ air permit search", type: "permit" }] },
  { datacenterSlug: "stargate-abilene", kind: "grid-interconnect", issuingBody: "ERCOT", appliedDate: "2024-07-12", status: "pending", sources: [{ url: "https://www.ercot.com/gridinfo/resource", title: "ERCOT generation interconnection queue", type: "filing" }] },
  { datacenterSlug: "stargate-abilene", kind: "building", issuingBody: "City of Abilene Building Inspection", issuedDate: "2024-10-08", status: "granted", sources: [{ url: "https://www.bigcountryhomepage.com/news/local-news/", title: "Abilene issues first Stargate building permits", type: "news" }] },
  { datacenterSlug: "xai-colossus-memphis", kind: "environmental", issuingBody: "Shelby County Health Department / TDEC", appliedDate: "2024-11-21", status: "pending", sources: [{ url: "https://www.selctn.org/our-work/clean-air/xai-memphis-gas-turbines", title: "SELC: xAI installed gas turbines without permits", type: "other" }, { url: "https://apnews.com/article/xai-memphis-musk-air-pollution-permit-2025", title: "AP: xAI seeks permit retroactively", type: "news" }] },
  { datacenterSlug: "xai-colossus-memphis", kind: "environmental", issuingBody: "Shelby County Health Department - Pollution Control", appliedDate: "2025-01-08", issuedDate: "2025-07-02", status: "granted", sources: [{ url: "https://www.commercialappeal.com/story/news/local/2025/07/03/", title: "Shelby County approves xAI air permit", type: "news" }] },
  { datacenterSlug: "xai-colossus-memphis", kind: "zoning", issuingBody: "Memphis & Shelby County OPD", issuedDate: "2024-06-05", status: "granted", sources: [{ url: "https://www.memphis.gov/", title: "Memphis OPD minutes", type: "filing" }] },
  { datacenterSlug: "xai-colossus-memphis", kind: "grid-interconnect", issuingBody: "TVA / MLGW", appliedDate: "2024-05-01", issuedDate: "2024-08-15", status: "granted", sources: [{ url: "https://dailymemphian.com/article/", title: "MLGW board OKs 150 MW for xAI in 100 days", type: "news" }] },
  { datacenterSlug: "xai-colossus-memphis", kind: "water", issuingBody: "MLGW / Sand Aquifer permit", appliedDate: "2025-02-19", status: "pending", sources: [{ url: "https://www.commercialappeal.com/story/news/2025/02/20/", title: "xAI Memphis aquifer water permit", type: "news" }] },
  { datacenterSlug: "meta-clonee", kind: "zoning", issuingBody: "An Bord Pleanála (SID)", appliedDate: "2017-08-10", issuedDate: "2018-03-22", status: "granted", sources: [{ url: "https://www.pleanala.ie/", title: "An Bord Pleanála Facebook Clonee", type: "filing" }] },
  { datacenterSlug: "meta-clonee", kind: "zoning", issuingBody: "An Bord Pleanála", appliedDate: "2021-04-30", issuedDate: "2022-02-11", status: "granted", sources: [{ url: "https://www.pleanala.ie/", title: "ABP Meta Clonee Phase 4", type: "filing" }] },
  { datacenterSlug: "google-eemshaven", kind: "environmental", issuingBody: "Province of Groningen", issuedDate: "2014-09-18", status: "granted", sources: [{ url: "https://www.provinciegroningen.nl/loket/vergunningen/", title: "Province of Groningen environmental permit", type: "permit" }] },
  { datacenterSlug: "google-eemshaven", kind: "zoning", issuingBody: "Gemeente Eemsdelta", appliedDate: "2022-06-01", issuedDate: "2023-04-05", status: "granted", sources: [{ url: "https://www.rtvnoord.nl/nieuws/", title: "Eemsdelta clears Google expansion", type: "news" }] },
  { datacenterSlug: "meta-zeewolde", kind: "zoning", issuingBody: "Gemeente Zeewolde", appliedDate: "2021-09-01", issuedDate: "2021-12-16", status: "granted", sources: [{ url: "https://www.nrc.nl/nieuws/2021/12/16/", title: "Zeewolde council approves rezoning", type: "news" }] },
  { datacenterSlug: "meta-zeewolde", kind: "zoning", issuingBody: "Eerste Kamer / Rijksvastgoedbedrijf", appliedDate: "2021-12-20", status: "withdrawn", sources: [{ url: "https://www.reuters.com/world/europe/dutch-senate-blocks-meta-data-centre-zeewolde-2022-03-15/", title: "Dutch Senate blocks Meta Zeewolde land sale", type: "news" }, { url: "https://www.nrc.nl/nieuws/2022/04/14/", title: "Meta withdraws Zeewolde application", type: "news" }] },
  { datacenterSlug: "meta-lulea", kind: "environmental", issuingBody: "Norrbotten County Administrative Board", issuedDate: "2012-04-26", status: "granted", sources: [{ url: "https://www.lansstyrelsen.se/norrbotten/", title: "Länsstyrelsen Norrbotten — Facebook Luleå permit", type: "permit" }] },
  { datacenterSlug: "coreweave-plano", kind: "zoning", issuingBody: "City of Plano P&Z Commission", issuedDate: "2023-10-02", status: "granted", sources: [{ url: "https://www.plano.gov/AgendaCenter", title: "Plano P&Z minutes", type: "filing" }] },
  { datacenterSlug: "coreweave-plano", kind: "building", issuingBody: "City of Plano Building Inspection", issuedDate: "2024-01-22", status: "granted", sources: [{ url: "https://www.plano.gov/200/Building-Inspections", title: "Plano building permit portal", type: "permit" }] },
  { datacenterSlug: "microsoft-san-antonio", kind: "zoning", issuingBody: "City of San Antonio Zoning Commission", issuedDate: "2023-05-18", status: "granted", sources: [{ url: "https://www.sanantonio.gov/DSD/AgendasMinutes", title: "San Antonio Zoning Commission agenda", type: "filing" }] },
  { datacenterSlug: "microsoft-san-antonio", kind: "water", issuingBody: "San Antonio Water System (SAWS)", issuedDate: "2023-09-25", status: "granted", sources: [{ url: "https://www.expressnews.com/news/local/", title: "SAWS signs water service agreement", type: "news" }] },
  { datacenterSlug: "aws-us-west-2-boardman", kind: "zoning", issuingBody: "Morrow County Planning Commission", issuedDate: "2020-11-12", status: "granted", sources: [{ url: "https://www.eastoregonian.com/news/local/", title: "Morrow County clears expanded AWS site", type: "news" }] },
  { datacenterSlug: "aws-us-west-2-boardman", kind: "water", issuingBody: "Oregon Water Resources Department", appliedDate: "2021-06-10", issuedDate: "2022-08-30", status: "granted", sources: [{ url: "https://www.oregon.gov/owrd/programs/wr/permits/", title: "OWRD water rights database", type: "permit" }] },
  { datacenterSlug: "aws-us-west-2-boardman", kind: "environmental", issuingBody: "Oregon DEQ", issuedDate: "2021-04-08", status: "granted", sources: [{ url: "https://www.oregon.gov/deq/aq/Pages/Air-Permits.aspx", title: "Oregon DEQ air permits", type: "permit" }] },
  { datacenterSlug: "apple-maiden-nc", kind: "zoning", issuingBody: "Catawba County Board of Commissioners", issuedDate: "2009-06-01", status: "granted", sources: [{ url: "https://www.charlotteobserver.com/news/business/", title: "Catawba County approves Apple iDataCenter", type: "news" }] },
  { datacenterSlug: "apple-maiden-nc", kind: "environmental", issuingBody: "NC DEQ - Division of Air Quality", issuedDate: "2010-04-19", status: "granted", sources: [{ url: "https://deq.nc.gov/about/divisions/air-quality/permitting", title: "NC DAQ permit database", type: "permit" }] },
];
