import type { DatacenterSource } from "@/server/db/schema";

export type SeedSubsidy = {
  datacenterSlug: string;
  recipientBrandSlug?: string;
  kind:
    | "tax-abatement"
    | "grant"
    | "infrastructure"
    | "ppa-discount"
    | "land"
    | "training"
    | "other";
  awardedBy: string;
  jurisdiction: string;
  amountUsd?: number;
  announcedDate?: string;
  effectiveDate?: string;
  termYears?: number;
  claimedJobs?: number;
  claimedCapexUsd?: number;
  sources: DatacenterSource[];
};

export const SUBSIDIES: SeedSubsidy[] = [
  { datacenterSlug: "microsoft-mt-pleasant", recipientBrandSlug: "microsoft", kind: "tax-abatement", awardedBy: "Village of Mount Pleasant / Racine County (TID 5)", jurisdiction: "US-WI", amountUsd: 764_000_000, announcedDate: "2023-05-04", termYears: 30, claimedJobs: 2300, claimedCapexUsd: 3_300_000_000, sources: [{ url: "https://www.reuters.com/technology/microsoft-invest-33-billion-wisconsin-ai-data-center-2024-05-08/", title: "Microsoft to invest $3.3 billion in Wisconsin AI hub on former Foxconn site", type: "news" }, { url: "https://wedc.org/programs-and-resources/electronics-and-information-technology-manufacturing-zone/", title: "WEDC EITM Zone (Act 58)", type: "filing" }] },
  { datacenterSlug: "microsoft-mt-pleasant", recipientBrandSlug: "microsoft", kind: "infrastructure", awardedBy: "State of Wisconsin (WEDC) / Village of Mount Pleasant", jurisdiction: "US-WI", amountUsd: 50_000_000, announcedDate: "2024-05-08", claimedJobs: 2000, claimedCapexUsd: 3_300_000_000, sources: [{ url: "https://content.govdelivery.com/accounts/WIGOV/bulletins/39966ac", title: "Gov. Evers — Microsoft AI investment", type: "pr" }] },
  { datacenterSlug: "microsoft-quincy-columbia", recipientBrandSlug: "microsoft", kind: "tax-abatement", awardedBy: "Washington — Rural County Sales/Use Tax Exemption (RCW 82.08.986)", jurisdiction: "US-WA", amountUsd: 320_000_000, announcedDate: "2010-04-01", termYears: 15, sources: [{ url: "https://dor.wa.gov/sites/default/files/2022-02/DataCenterTaxIncentiveReport.pdf", title: "WA DOR — Data Center Sales/Use Tax Incentive Report", type: "filing" }, { url: "https://www.seattletimes.com/business/microsoft/", title: "Microsoft's Quincy data centers tap rural WA tax break", type: "news" }] },
  { datacenterSlug: "microsoft-san-antonio", recipientBrandSlug: "microsoft", kind: "tax-abatement", awardedBy: "City of San Antonio / Bexar County (Chapter 312)", jurisdiction: "US-TX", amountUsd: 27_500_000, announcedDate: "2007-12-01", termYears: 10, claimedJobs: 75, claimedCapexUsd: 550_000_000, sources: [{ url: "https://subsidytracker.goodjobsfirst.org/parent/microsoft", title: "Good Jobs First — Microsoft San Antonio", type: "filing" }] },
  { datacenterSlug: "meta-hyperion-richland", recipientBrandSlug: "meta", kind: "tax-abatement", awardedBy: "Louisiana ITEP — Richland Parish", jurisdiction: "US-LA", amountUsd: 1_400_000_000, announcedDate: "2024-12-04", termYears: 10, claimedJobs: 500, claimedCapexUsd: 10_000_000_000, sources: [{ url: "https://www.reuters.com/technology/meta-build-10-billion-ai-data-center-louisiana-2024-12-04/", title: "Meta to build $10 billion AI data center in Louisiana", type: "news" }, { url: "https://www.opportunitylouisiana.gov/business-incentives/industrial-tax-exemption", title: "Louisiana ITEP", type: "filing" }] },
  { datacenterSlug: "meta-altoona", recipientBrandSlug: "meta", kind: "grant", awardedBy: "Iowa Economic Development Authority (HQJ + ITC)", jurisdiction: "US-IA", amountUsd: 18_000_000, announcedDate: "2013-04-23", termYears: 10, claimedJobs: 31, claimedCapexUsd: 300_000_000, sources: [{ url: "https://www.iowaeda.com/news/", title: "IEDA approves incentives for Facebook Altoona", type: "pr" }] },
  { datacenterSlug: "meta-altoona", recipientBrandSlug: "meta", kind: "tax-abatement", awardedBy: "City of Altoona / Polk County", jurisdiction: "US-IA", amountUsd: 200_000_000, announcedDate: "2013-04-23", termYears: 20, claimedCapexUsd: 1_500_000_000, sources: [{ url: "https://www.desmoinesregister.com/", title: "Altoona Facebook data center tax breaks total $200M", type: "news" }] },
  { datacenterSlug: "meta-eagle-mountain", recipientBrandSlug: "meta", kind: "tax-abatement", awardedBy: "Utah County / Eagle Mountain (PILT)", jurisdiction: "US-UT", amountUsd: 150_000_000, announcedDate: "2018-05-09", termYears: 20, claimedJobs: 100, claimedCapexUsd: 750_000_000, sources: [{ url: "https://www.sltrib.com/news/business/2018/05/09/", title: "Facebook confirms Eagle Mountain after $150M tax break", type: "news" }] },
  { datacenterSlug: "meta-newton-county", recipientBrandSlug: "meta", kind: "tax-abatement", awardedBy: "Newton County IDA (bond-lease)", jurisdiction: "US-GA", amountUsd: 150_000_000, announcedDate: "2018-03-08", termYears: 20, claimedJobs: 100, claimedCapexUsd: 750_000_000, sources: [{ url: "https://www.bizjournals.com/atlanta/news/2018/03/08/", title: "Facebook to build $750M data center in Newton County", type: "news" }] },
  { datacenterSlug: "meta-sarpy-county", recipientBrandSlug: "meta", kind: "tax-abatement", awardedBy: "Nebraska — ImagiNE Act", jurisdiction: "US-NE", amountUsd: 230_000_000, announcedDate: "2018-04-19", termYears: 15, claimedJobs: 100, claimedCapexUsd: 1_500_000_000, sources: [{ url: "https://omaha.com/business/local/", title: "Nebraska awards Facebook $230M for Papillion data center", type: "news" }, { url: "https://opportunity.nebraska.gov/program/imagine-nebraska-act/", title: "ImagiNE Act", type: "filing" }] },
  { datacenterSlug: "google-the-dalles", recipientBrandSlug: "google", kind: "tax-abatement", awardedBy: "City of The Dalles / Wasco County (Long-Term Rural Enterprise Zone)", jurisdiction: "US-OR", amountUsd: 260_000_000, announcedDate: "2005-02-10", termYears: 15, claimedCapexUsd: 1_200_000_000, sources: [{ url: "https://www.oregonlive.com/silicon-forest/2022/12/", title: "Google's water use and tax breaks in The Dalles", type: "news" }] },
  { datacenterSlug: "google-council-bluffs", recipientBrandSlug: "google", kind: "grant", awardedBy: "Iowa Economic Development Authority", jurisdiction: "US-IA", amountUsd: 25_700_000, announcedDate: "2007-06-19", termYears: 10, claimedJobs: 200, claimedCapexUsd: 600_000_000, sources: [{ url: "https://subsidytracker.goodjobsfirst.org/parent/alphabet", title: "Good Jobs First — Alphabet records", type: "filing" }] },
  { datacenterSlug: "google-council-bluffs", recipientBrandSlug: "google", kind: "tax-abatement", awardedBy: "City of Council Bluffs / Pottawattamie County", jurisdiction: "US-IA", amountUsd: 110_000_000, announcedDate: "2007-06-19", termYears: 20, claimedCapexUsd: 5_000_000_000, sources: [{ url: "https://www.nonpareilonline.com/", title: "Council Bluffs Google tax rebate", type: "news" }] },
  { datacenterSlug: "google-mayes-county", recipientBrandSlug: "google", kind: "tax-abatement", awardedBy: "Oklahoma — 5-Year Manufacturing Ad Valorem Exemption + Quality Jobs Act", jurisdiction: "US-OK", amountUsd: 78_000_000, announcedDate: "2007-08-31", termYears: 5, claimedJobs: 100, claimedCapexUsd: 700_000_000, sources: [{ url: "https://www.tulsaworld.com/business/", title: "Google Pryor data center tax incentives", type: "news" }] },
  { datacenterSlug: "google-lenoir", recipientBrandSlug: "google", kind: "grant", awardedBy: "North Carolina Job Development Investment Grant (JDIG)", jurisdiction: "US-NC", amountUsd: 4_700_000, announcedDate: "2007-01-19", termYears: 11, claimedJobs: 210, claimedCapexUsd: 600_000_000, sources: [{ url: "https://www.commerce.nc.gov/", title: "NC Commerce JDIG — Google Lenoir award", type: "pr" }] },
  { datacenterSlug: "google-lenoir", recipientBrandSlug: "google", kind: "tax-abatement", awardedBy: "Caldwell County / City of Lenoir", jurisdiction: "US-NC", amountUsd: 165_000_000, announcedDate: "2007-01-19", termYears: 30, claimedCapexUsd: 600_000_000, sources: [{ url: "https://www.newsobserver.com/news/business/", title: "Lenoir NC offered Google up to $260M in tax breaks", type: "news" }] },
  { datacenterSlug: "google-berkeley-county", recipientBrandSlug: "google", kind: "tax-abatement", awardedBy: "Berkeley County, SC (FILOT)", jurisdiction: "US-SC", amountUsd: 67_000_000, announcedDate: "2007-04-02", termYears: 30, claimedJobs: 200, claimedCapexUsd: 600_000_000, sources: [{ url: "https://www.postandcourier.com/business/", title: "Berkeley County FILOT for Google", type: "news" }] },
  { datacenterSlug: "aws-northern-virginia-pjm", recipientBrandSlug: "aws", kind: "tax-abatement", awardedBy: "Virginia — Data Center Sales & Use Tax Exemption (Va. Code 58.1-609.3(18))", jurisdiction: "US-VA", amountUsd: 929_000_000, announcedDate: "2010-07-01", termYears: 25, claimedCapexUsd: 35_000_000_000, sources: [{ url: "https://jlarc.virginia.gov/pdfs/reports/Rpt576.pdf", title: "JLARC — Data Centers in Virginia (2024)", type: "filing" }] },
  { datacenterSlug: "aws-us-east-2-new-albany", recipientBrandSlug: "aws", kind: "tax-abatement", awardedBy: "JobsOhio / Ohio DoT — Data Center Sales Tax Exemption", jurisdiction: "US-OH", amountUsd: 314_000_000, announcedDate: "2015-09-30", termYears: 15, claimedJobs: 1000, claimedCapexUsd: 1_100_000_000, sources: [{ url: "https://development.ohio.gov/business/state-incentives/data-center-tax-incentive", title: "Ohio Data Center Sales Tax Exemption", type: "filing" }] },
  { datacenterSlug: "aws-us-east-2-new-albany", recipientBrandSlug: "aws", kind: "grant", awardedBy: "JobsOhio + State of Ohio — 2024 expansion", jurisdiction: "US-OH", amountUsd: 67_000_000, announcedDate: "2024-06-04", termYears: 15, claimedJobs: 230, claimedCapexUsd: 7_800_000_000, sources: [{ url: "https://www.reuters.com/technology/amazon-invest-78-billion-ohio-data-center-2024-06-04/", title: "Amazon to invest $7.8B more in Ohio", type: "news" }] },
  { datacenterSlug: "aws-us-west-2-boardman", recipientBrandSlug: "aws", kind: "tax-abatement", awardedBy: "Morrow County / Port of Morrow — Long-Term Rural Enterprise Zone", jurisdiction: "US-OR", amountUsd: 225_000_000, announcedDate: "2011-11-15", termYears: 15, claimedJobs: 134, claimedCapexUsd: 4_500_000_000, sources: [{ url: "https://www.oregonlive.com/silicon-forest/2022/06/", title: "Amazon's Oregon tax breaks top $225M", type: "news" }] },
  { datacenterSlug: "apple-maiden-nc", recipientBrandSlug: "apple", kind: "tax-abatement", awardedBy: "North Carolina + Catawba County (HB1762 'Apple bill')", jurisdiction: "US-NC", amountUsd: 311_000_000, announcedDate: "2009-06-04", termYears: 30, claimedJobs: 50, claimedCapexUsd: 1_000_000_000, sources: [{ url: "https://www.washingtonpost.com/business/economy/apples-tax-breaks-north-carolina/2012/04/29/", title: "Apple's tax breaks in NC top $300M", type: "news" }] },
  { datacenterSlug: "stargate-abilene", recipientBrandSlug: "openai", kind: "tax-abatement", awardedBy: "Abilene ISD / Taylor County (Chapter 403 — JETI)", jurisdiction: "US-TX", amountUsd: 290_000_000, announcedDate: "2024-09-04", termYears: 10, claimedJobs: 350, claimedCapexUsd: 25_000_000_000, sources: [{ url: "https://comptroller.texas.gov/economy/local/ch403/", title: "Texas Comptroller — JETI reports", type: "filing" }, { url: "https://www.bigcountryhomepage.com/news/", title: "Abilene ISD approves Crusoe JETI application", type: "news" }] },
  { datacenterSlug: "xai-colossus-memphis", recipientBrandSlug: "xai", kind: "tax-abatement", awardedBy: "Memphis-Shelby County EDGE — PILOT", jurisdiction: "US-TN", amountUsd: 80_000_000, announcedDate: "2024-07-22", termYears: 15, claimedJobs: 300, claimedCapexUsd: 12_000_000_000, sources: [{ url: "https://www.commercialappeal.com/story/news/local/2024/07/22/", title: "EDGE board approves xAI PILOT", type: "news" }] },
  { datacenterSlug: "coreweave-plano", recipientBrandSlug: "coreweave", kind: "tax-abatement", awardedBy: "Plano ISD / Collin County (JETI)", jurisdiction: "US-TX", amountUsd: 18_000_000, announcedDate: "2024-11-12", termYears: 10, claimedJobs: 50, claimedCapexUsd: 1_600_000_000, sources: [{ url: "https://comptroller.texas.gov/economy/local/ch403/", title: "Texas JETI applications", type: "filing" }] },
  { datacenterSlug: "meta-clonee", recipientBrandSlug: "meta", kind: "grant", awardedBy: "IDA Ireland", jurisdiction: "IE", amountUsd: 12_000_000, announcedDate: "2016-01-21", termYears: 10, claimedJobs: 200, claimedCapexUsd: 220_000_000, sources: [{ url: "https://www.idaireland.com/", title: "IDA Ireland — Facebook Clonee", type: "pr" }] },
  { datacenterSlug: "google-eemshaven", recipientBrandSlug: "google", kind: "infrastructure", awardedBy: "Province of Groningen / Groningen Seaports", jurisdiction: "NL", amountUsd: 95_000_000, announcedDate: "2014-09-23", termYears: 25, claimedJobs: 150, claimedCapexUsd: 600_000_000, sources: [{ url: "https://www.rtvnoord.nl/", title: "Google announces Eemshaven investment", type: "news" }] },
  { datacenterSlug: "google-hamina", recipientBrandSlug: "google", kind: "infrastructure", awardedBy: "City of Hamina / Finnish State", jurisdiction: "FI", amountUsd: 50_000_000, announcedDate: "2009-02-04", termYears: 20, claimedJobs: 90, claimedCapexUsd: 200_000_000, sources: [{ url: "https://yle.fi/a/3-5710213", title: "Google buys Hamina mill", type: "news" }] },
  { datacenterSlug: "google-saint-ghislain", recipientBrandSlug: "google", kind: "grant", awardedBy: "Région Wallonne", jurisdiction: "BE", amountUsd: 8_500_000, announcedDate: "2007-04-26", termYears: 10, claimedJobs: 120, claimedCapexUsd: 250_000_000, sources: [{ url: "https://www.wallonia.be/en/news/", title: "Wallonia — Google Saint-Ghislain", type: "pr" }] },
  { datacenterSlug: "meta-lulea", recipientBrandSlug: "meta", kind: "infrastructure", awardedBy: "Norrbotten Region / Luleå Kommun / Vattenfall", jurisdiction: "SE", amountUsd: 30_000_000, announcedDate: "2011-10-27", termYears: 10, claimedJobs: 150, claimedCapexUsd: 760_000_000, sources: [{ url: "https://www.businesssweden.com/", title: "Business Sweden — Node Pole / Luleå", type: "operator" }] },
  { datacenterSlug: "google-fredericia", recipientBrandSlug: "google", kind: "land", awardedBy: "Fredericia Kommune", jurisdiction: "DK", amountUsd: 21_000_000, announcedDate: "2018-11-20", claimedJobs: 150, claimedCapexUsd: 700_000_000, sources: [{ url: "https://www.dr.dk/nyheder/regionale/trekanten/", title: "Google køber industrigrund i Fredericia", type: "news" }] },
  { datacenterSlug: "atnorth-ice02-keflavik", recipientBrandSlug: "atnorth", kind: "tax-abatement", awardedBy: "Iceland Investment Incentive (Act 99/2010)", jurisdiction: "IS", amountUsd: 9_000_000, announcedDate: "2018-04-01", termYears: 10, claimedJobs: 60, claimedCapexUsd: 90_000_000, sources: [{ url: "https://www.invest.is/incentives/", title: "Invest in Iceland — incentives", type: "filing" }] },
  { datacenterSlug: "naver-sejong-gak", recipientBrandSlug: "naver", kind: "land", awardedBy: "Sejong Special Self-Governing City", jurisdiction: "KR", amountUsd: 35_000_000, announcedDate: "2019-10-24", termYears: 50, claimedJobs: 1000, claimedCapexUsd: 540_000_000, sources: [{ url: "https://en.yna.co.kr/view/AEN20191024009000320", title: "Naver to build second data center in Sejong", type: "news" }] },
  { datacenterSlug: "ytl-yondr-johor-kulai", recipientBrandSlug: "ytl", kind: "tax-abatement", awardedBy: "MIDA — Digital Ecosystem Acceleration (DESAC)", jurisdiction: "MY", amountUsd: 250_000_000, announcedDate: "2023-12-08", termYears: 10, claimedJobs: 300, claimedCapexUsd: 1_500_000_000, sources: [{ url: "https://www.theedgemalaysia.com/", title: "YTL gets MIDA approval for Kulai AI data centre park", type: "news" }] },
  { datacenterSlug: "bridge-data-centres-mr1-johor", recipientBrandSlug: "bridge-data-centres", kind: "tax-abatement", awardedBy: "Iskandar Regional Development Authority + MIDA", jurisdiction: "MY", amountUsd: 70_000_000, announcedDate: "2022-06-15", termYears: 10, claimedJobs: 150, claimedCapexUsd: 400_000_000, sources: [{ url: "https://www.thestar.com.my/business/business-news/2022/06/", title: "Bridge Data Centres breaks ground in Johor", type: "news" }] },
  { datacenterSlug: "yotta-shakti-hyderabad", recipientBrandSlug: "yotta", kind: "grant", awardedBy: "Telangana — IT/ITeS Policy + Data Centre Policy 2023", jurisdiction: "IN", amountUsd: 120_000_000, announcedDate: "2023-08-04", termYears: 10, claimedJobs: 1000, claimedCapexUsd: 1_800_000_000, sources: [{ url: "https://www.thehindu.com/news/national/telangana/", title: "Telangana signs MoU with Yotta", type: "news" }] },
  { datacenterSlug: "reliance-jio-jamnagar-ai", recipientBrandSlug: "reliance-jio", kind: "land", awardedBy: "Government of Gujarat — SEZ + power tariff", jurisdiction: "IN", amountUsd: 600_000_000, announcedDate: "2024-02-22", termYears: 25, claimedJobs: 2000, claimedCapexUsd: 20_000_000_000, sources: [{ url: "https://www.reuters.com/world/india/", title: "Reliance + NVIDIA AI data centre in Jamnagar", type: "news" }] },
  { datacenterSlug: "humain-saudi-riyadh", recipientBrandSlug: "humain", kind: "other", awardedBy: "PIF — sovereign capitalization", jurisdiction: "SA", amountUsd: 10_000_000_000, announcedDate: "2025-05-12", claimedJobs: 1500, claimedCapexUsd: 10_000_000_000, sources: [{ url: "https://www.reuters.com/world/middle-east/", title: "Saudi PIF launches HUMAIN", type: "news" }] },
  { datacenterSlug: "g42-stargate-uae-abu-dhabi", recipientBrandSlug: "g42", kind: "other", awardedBy: "Government of Abu Dhabi / Mubadala", jurisdiction: "AE", amountUsd: 5_000_000_000, announcedDate: "2025-05-15", claimedJobs: 1000, claimedCapexUsd: 25_000_000_000, sources: [{ url: "https://www.reuters.com/technology/", title: "OpenAI + G42 announce Stargate UAE", type: "news" }] },
  { datacenterSlug: "meta-zeewolde", recipientBrandSlug: "meta", kind: "land", awardedBy: "Gemeente Zeewolde / Province of Flevoland", jurisdiction: "NL", amountUsd: 50_000_000, announcedDate: "2021-12-16", claimedJobs: 410, claimedCapexUsd: 1_000_000_000, sources: [{ url: "https://nos.nl/artikel/2415327-meta-datacenter-zeewolde", title: "Meta Zeewolde cancelled after Senate motion", type: "news" }] },
];
