import type { CollectionConfig } from "payload";

export const Challenges: CollectionConfig = {
  slug: "challenges",
  admin: {
    useAsTitle: "title",
    defaultColumns: ["title", "type", "status", "difficulty", "startsAt"],
    description:
      "Unified challenges: platform-action, repo-based, or mixed. Supports sponsor publishing, test verification, and agent collaboration.",
  },
  fields: [
    { name: "title", type: "text", required: true },
    {
      name: "slug",
      type: "text",
      required: true,
      unique: true,
      admin: { position: "sidebar" },
    },
    { name: "description", type: "richText", required: true },
    {
      name: "type",
      type: "select",
      required: true,
      options: [
        { label: "Weekly", value: "weekly" },
        { label: "Monthly", value: "monthly" },
        { label: "Open-Ended", value: "open-ended" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "draft",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Active", value: "active" },
        { label: "Completed", value: "completed" },
        { label: "Archived", value: "archived" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "difficulty",
      type: "select",
      required: true,
      defaultValue: "beginner",
      options: [
        { label: "Beginner", value: "beginner" },
        { label: "Intermediate", value: "intermediate" },
        { label: "Advanced", value: "advanced" },
        { label: "Expert", value: "expert" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "startsAt",
      type: "date",
      admin: {
        position: "sidebar",
        description: "Optional for open-ended challenges.",
      },
    },
    {
      name: "endsAt",
      type: "date",
      admin: {
        position: "sidebar",
        description: "Optional for open-ended challenges.",
      },
    },
    {
      name: "publishedBy",
      type: "select",
      required: true,
      defaultValue: "member",
      options: [
        { label: "Member", value: "member" },
        { label: "Sponsor", value: "sponsor" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "generatedBy",
      type: "select",
      defaultValue: "human",
      options: [
        { label: "Human", value: "human" },
        { label: "AI", value: "ai" },
      ],
      admin: {
        position: "sidebar",
        description:
          "Whether this challenge was generated by AI or created by a human.",
      },
    },
    {
      name: "creatorId",
      type: "text",
      required: true,
      admin: {
        position: "sidebar",
        description: "User ID or Sponsor ID of the challenge creator.",
      },
    },
    {
      name: "repo",
      type: "group",
      admin: {
        description: "GitHub repo configuration for repo-based challenges.",
      },
      fields: [
        {
          name: "templateUrl",
          type: "text",
          admin: {
            description:
              "GitHub template repo URL (e.g., https://github.com/org/repo).",
          },
        },
        {
          name: "configFile",
          type: "checkbox",
          defaultValue: false,
          admin: {
            description:
              "Whether .aitchallenge.yml is expected in participant repos.",
          },
        },
        {
          name: "testCommand",
          type: "text",
          admin: {
            description:
              'Shell command to run tests (e.g., "npm test", "pytest").',
          },
        },
        {
          name: "colabUrl",
          type: "text",
          admin: {
            description:
              "Google Colab notebook URL for cloud-based development.",
          },
        },
      ],
    },
    {
      name: "objectives",
      type: "array",
      // Optional at the collection level: a hackathon challenge carries an empty
      // objectives list and decomposes its work via cellTemplate instead (ADR-0032).
      // The "single-actor challenge needs >=1 objective" rule lives in the
      // challenges.create input schema, the path where that context is known.
      maxRows: 10,
      fields: [
        {
          name: "description",
          type: "text",
          required: true,
        },
        {
          name: "verification",
          type: "select",
          required: true,
          defaultValue: "self-report",
          options: [
            { label: "Platform Action", value: "platform-action" },
            { label: "Test", value: "test" },
            { label: "Self-Report", value: "self-report" },
            { label: "Peer Review", value: "peer-review" },
          ],
        },
        {
          name: "action",
          type: "select",
          options: [
            { label: "Reply to thread", value: "thread.reply" },
            { label: "Create thread", value: "thread.create" },
            { label: "Share knowledge", value: "knowledge.share" },
            { label: "Submit idea", value: "idea.submitted" },
            { label: "Vote on idea", value: "idea.voted" },
          ],
          admin: {
            description: "Only for platform-action verification.",
            condition: (_, siblingData) =>
              siblingData?.verification === "platform-action",
          },
        },
        {
          name: "testPattern",
          type: "text",
          admin: {
            description:
              "Regex matching test names/files for test verification.",
            condition: (_, siblingData) => siblingData?.verification === "test",
          },
        },
        {
          name: "targetCount",
          type: "number",
          required: true,
          min: 1,
          defaultValue: 1,
          admin: {
            description:
              "How many times this must be completed. For tests, usually 1.",
          },
        },
        {
          name: "filter",
          type: "json",
          admin: {
            description:
              'Optional scope filter for platform-action, e.g. { "category": "question" }.',
          },
        },
      ],
    },
    {
      name: "rewards",
      type: "group",
      fields: [
        {
          name: "xpReward",
          type: "number",
          required: true,
          min: 0,
          defaultValue: 0,
          admin: { description: "XP awarded on completion." },
        },
        {
          name: "badgeReward",
          type: "text",
          admin: {
            description: "Badge slug to award on completion (optional).",
          },
        },
        {
          name: "sponsorReward",
          type: "text",
          admin: {
            description:
              "Sponsor-provided reward description (prizes, interviews, licenses).",
          },
        },
      ],
    },
    {
      name: "cellTemplate",
      type: "array",
      admin: {
        description:
          "Hackathon work-cell decomposition. Each entry becomes one pending cell in every team's competitive grid when rosters lock (ADR-0029/0023). Leave empty for non-hackathon challenges.",
      },
      fields: [
        { name: "description", type: "text", required: true },
        { name: "taskType", type: "text", required: true },
        {
          name: "verificationMode",
          type: "select",
          required: true,
          defaultValue: "self-report",
          options: [
            { label: "Platform Action", value: "platform-action" },
            { label: "Test", value: "test" },
            { label: "Self-Report", value: "self-report" },
            { label: "Peer Review", value: "peer-review" },
            { label: "Consensus", value: "consensus" },
          ],
        },
        {
          name: "deadlineMinutes",
          type: "number",
          required: true,
          min: 1,
          defaultValue: 60,
        },
      ],
    },
    {
      name: "teamConfig",
      type: "group",
      admin: {
        description:
          "Hackathon team-size bounds (ADR-0029). Only meaningful for a challenge bound to a hackathon event; ignored otherwise.",
      },
      fields: [
        {
          // Optional so non-hackathon challenges need not carry team config;
          // the work-grid/team code falls back to sensible defaults (min 1, max 5).
          name: "minTeamSize",
          type: "number",
          min: 1,
          defaultValue: 1,
        },
        {
          name: "maxTeamSize",
          type: "number",
          min: 1,
          defaultValue: 5,
        },
      ],
    },
    {
      name: "maxParticipants",
      type: "number",
      defaultValue: 0,
      admin: {
        position: "sidebar",
        description: "0 = unlimited.",
      },
    },
    {
      name: "tags",
      type: "json",
      admin: {
        description:
          'Array of tags for discovery, e.g. ["mcp", "typescript", "automation"].',
      },
    },
    {
      name: "signalSource",
      type: "group",
      admin: {
        description:
          "For AI-generated challenges: what triggered this challenge.",
        condition: (data) => data?.generatedBy === "ai",
      },
      fields: [
        {
          name: "type",
          type: "select",
          options: [
            { label: "Community Thread", value: "community-thread" },
            { label: "Member Request", value: "member-request" },
            { label: "External Signal", value: "external" },
            { label: "Insight Gap", value: "insight-gap" },
          ],
        },
        {
          name: "reference",
          type: "text",
          admin: {
            description: "Thread ID, URL, or description of the signal source.",
          },
        },
        {
          name: "summary",
          type: "textarea",
          admin: {
            description: "AI summary of why this challenge was generated.",
          },
        },
      ],
    },
    {
      name: "rankingMode",
      type: "select",
      defaultValue: "speed",
      options: [
        { label: "Speed", value: "speed" },
        { label: "Thoroughness", value: "thoroughness" },
        { label: "Collaboration", value: "collaboration" },
      ],
      admin: {
        position: "sidebar",
        description: "How the leaderboard is sorted.",
      },
    },
    {
      name: "judgingOpenedAt",
      type: "date",
      admin: {
        position: "sidebar",
        readOnly: true,
        description: "Set when an organizer opens judging; gates judge ranking.",
      },
    },
    {
      name: "collaborationModel",
      type: "select",
      defaultValue: "solo-ai",
      options: [
        { label: "Solo + AI", value: "solo-ai" },
        { label: "Relay", value: "relay" },
        { label: "Swarm", value: "swarm" },
        { label: "Adversarial", value: "adversarial" },
        { label: "Blind", value: "blind" },
        { label: "Escalation", value: "escalation" },
      ],
      admin: {
        position: "sidebar",
        description: "How humans and AIs collaborate in this challenge.",
      },
    },
    {
      name: "proposedBy",
      type: "text",
      admin: {
        position: "sidebar",
        description: "User ID if community-proposed.",
      },
    },
    { name: "image", type: "upload", relationTo: "media" },
    {
      name: "communityId",
      type: "text",
      index: true,
      admin: { position: "sidebar" },
    },
  ],
  timestamps: true,
};
