import type { PgTable } from "drizzle-orm/pg-core";

import {
  brands,
  datacenters,
  datacenterSuppliers,
  datacenterStatusHistory,
  datacenterFindings,
  energyDeals,
  ownershipEdges,
  permits,
  subsidies,
} from "@/server/db/schema";

export const ENTITY_TYPES = [
  "datacenter",
  "brand",
  "subsidy",
  "permit",
  "energy_deal",
  "ownership_edge",
  "datacenter_supplier",
  "datacenter_status_history",
  "datacenter_finding",
] as const;

export type EntityType = (typeof ENTITY_TYPES)[number];

export interface EntityConfig {
  table: PgTable;
  pkColumn: "id";
  factualFields: Set<string>;
  adminOnlyFields: Set<string>;
  editableFields: Set<string>;
}

export const ENTITY_CONFIG: Record<EntityType, EntityConfig> = {
  datacenter: {
    table: datacenters,
    pkColumn: "id",
    factualFields: new Set([
      "capacityMw",
      "capacityMwPlanned",
      "squareFootage",
      "rackCount",
      "primaryPowerSource",
      "coolingType",
      "operatorId",
      "utilityId",
      "lat",
      "lng",
      "puePledged",
      "waterDrawMgd",
      "waterDrawCubicM",
      "wuePledged",
      "announcedDate",
      "groundbreakDate",
      "onlineDate",
      "fullCapacityDate",
      "capexUsd",
      "status",
      "country",
      "region",
      "city",
      "address",
      "gpus",
    ]),
    adminOnlyFields: new Set(["verified", "slug"]),
    editableFields: new Set([
      "name",
      "slug",
      "operatorId",
      "utilityId",
      "status",
      "aiDedicated",
      "lat",
      "lng",
      "address",
      "city",
      "region",
      "country",
      "capacityMw",
      "capacityMwPlanned",
      "squareFootage",
      "rackCount",
      "gpus",
      "primaryPowerSource",
      "coolingType",
      "puePledged",
      "waterDrawMgd",
      "waterDrawCubicM",
      "wuePledged",
      "announcedDate",
      "groundbreakDate",
      "onlineDate",
      "fullCapacityDate",
      "capexUsd",
      "description",
      "sources",
      "verified",
    ]),
  },
  brand: {
    table: brands,
    pkColumn: "id",
    factualFields: new Set([
      "canonicalName",
      "website",
      "jurisdiction",
      "jurisdictionRegion",
      "entityType",
      "ultimateBeneficialOwner",
      "commitmentRenewablePct",
      "commitmentTargetYear",
      "commitmentSourceUrl",
      "aliases",
      "categoryIds",
    ]),
    adminOnlyFields: new Set(["verified", "slug"]),
    editableFields: new Set([
      "canonicalName",
      "slug",
      "aliases",
      "website",
      "categoryIds",
      "commitmentRenewablePct",
      "commitmentTargetYear",
      "commitmentSourceUrl",
      "commitmentNotes",
      "jurisdiction",
      "jurisdictionRegion",
      "entityType",
      "ultimateBeneficialOwner",
      "verified",
    ]),
  },
  subsidy: {
    table: subsidies,
    pkColumn: "id",
    factualFields: new Set([
      "datacenterId",
      "recipientBrandId",
      "kind",
      "awardedBy",
      "jurisdiction",
      "amountUsd",
      "announcedDate",
      "effectiveDate",
      "termYears",
      "claimedJobs",
      "claimedCapexUsd",
    ]),
    adminOnlyFields: new Set(["verified"]),
    editableFields: new Set([
      "datacenterId",
      "recipientBrandId",
      "kind",
      "awardedBy",
      "jurisdiction",
      "amountUsd",
      "announcedDate",
      "effectiveDate",
      "termYears",
      "claimedJobs",
      "claimedCapexUsd",
      "sources",
      "verified",
    ]),
  },
  permit: {
    table: permits,
    pkColumn: "id",
    factualFields: new Set([
      "datacenterId",
      "kind",
      "issuingBody",
      "appliedDate",
      "issuedDate",
      "status",
    ]),
    adminOnlyFields: new Set(["verified"]),
    editableFields: new Set([
      "datacenterId",
      "kind",
      "issuingBody",
      "appliedDate",
      "issuedDate",
      "status",
      "sources",
      "verified",
    ]),
  },
  energy_deal: {
    table: energyDeals,
    pkColumn: "id",
    factualFields: new Set([
      "title",
      "datacenterId",
      "buyerId",
      "counterpartyId",
      "type",
      "energyType",
      "mw",
      "termYears",
      "signedDate",
      "startDate",
      "valueUsd",
    ]),
    adminOnlyFields: new Set(["verified"]),
    editableFields: new Set([
      "title",
      "datacenterId",
      "buyerId",
      "counterpartyId",
      "type",
      "energyType",
      "mw",
      "termYears",
      "signedDate",
      "startDate",
      "valueUsd",
      "sources",
      "verified",
    ]),
  },
  ownership_edge: {
    table: ownershipEdges,
    pkColumn: "id",
    factualFields: new Set([
      "parentBrandId",
      "childBrandId",
      "ownershipPct",
      "effectiveFrom",
      "effectiveTo",
      "sourceUrl",
    ]),
    adminOnlyFields: new Set(["verified"]),
    editableFields: new Set([
      "parentBrandId",
      "childBrandId",
      "ownershipPct",
      "effectiveFrom",
      "effectiveTo",
      "sourceUrl",
      "notes",
      "verified",
    ]),
  },
  datacenter_supplier: {
    table: datacenterSuppliers,
    pkColumn: "id",
    factualFields: new Set([
      "datacenterId",
      "supplierId",
      "category",
      "role",
      "contractValueUsd",
    ]),
    adminOnlyFields: new Set(["verified"]),
    editableFields: new Set([
      "datacenterId",
      "supplierId",
      "category",
      "role",
      "contractValueUsd",
      "isLocal",
      "sources",
      "verified",
    ]),
  },
  datacenter_status_history: {
    table: datacenterStatusHistory,
    pkColumn: "id",
    factualFields: new Set([
      "datacenterId",
      "status",
      "effectiveDate",
      "sourceUrl",
    ]),
    adminOnlyFields: new Set([]),
    editableFields: new Set([
      "datacenterId",
      "status",
      "effectiveDate",
      "sourceUrl",
      "notes",
    ]),
  },
  datacenter_finding: {
    table: datacenterFindings,
    pkColumn: "id",
    factualFields: new Set(["claim", "evidenceUrls", "datacenterId"]),
    adminOnlyFields: new Set(["status"]),
    // userId is create-only provenance. Update-finding procs in Phase B will not pass it.
    editableFields: new Set([
      "datacenterId",
      "userId",
      "title",
      "body",
      "claim",
      "evidenceUrls",
      "status",
    ]),
  },
};
