import type { AwesomeSeed } from "./awesome-ai-oss";

/**
 * Chunk 4/6 curated seeds. `addedOn` is the live GitHub `created_at` date
 * (UTC, fetched 2026-09-14) — not a popularity or star signal.
 */
export const AWESOME_AI_OSS_SEEDS_CHUNK_4: readonly AwesomeSeed[] = [
  {
    id: "curated-plandex",
    name: "Plandex",
    href: "https://github.com/plandex-ai/plandex",
    category: "frameworks",
    addedOn: "2023-10-24",
    blurb: {
      en: "AI coding agent for large projects in the terminal",
      nl: "AI-codeeragent voor grote projecten in de terminal",
    },
  },
  {
    id: "curated-dzhng-deep-research",
    name: "Open Deep Research",
    href: "https://github.com/dzhng/deep-research",
    category: "frameworks",
    addedOn: "2025-02-04",
    blurb: {
      en: "AI agent that conducts iterative web research",
      nl: "AI-agent die iteratief webonderzoek uitvoert",
    },
  },
  {
    id: "curated-deer-flow",
    name: "DeerFlow",
    href: "https://github.com/bytedance/deer-flow",
    category: "frameworks",
    addedOn: "2025-05-07",
    blurb: {
      en: "ByteDance deep research / agent workflow framework",
      nl: "ByteDance deep-research- / agent-workflowframework",
    },
  },
  {
    id: "curated-rag-anything",
    name: "RAG-Anything",
    href: "https://github.com/HKUDS/RAG-Anything",
    category: "rag",
    addedOn: "2025-06-06",
    blurb: {
      en: "All-in-one multimodal RAG for text, images, tables, and equations",
      nl: "Alles-in-één multimodale RAG voor tekst, beelden, tabellen en formules",
    },
  },
  {
    id: "curated-kotaemon",
    name: "Kotaemon",
    href: "https://github.com/cinnamon/kotaemon",
    category: "rag",
    addedOn: "2024-03-25",
    blurb: {
      en: "Clean open-source RAG UI for chatting with your documents",
      nl: "Schone open-source RAG-UI om te chatten met je documenten",
    },
  },
  {
    id: "curated-flagembedding",
    name: "FlagEmbedding",
    href: "https://github.com/FlagOpen/FlagEmbedding",
    category: "rag",
    addedOn: "2023-08-02",
    blurb: {
      en: "BGE embedding and retrieval toolkit for RAG systems",
      nl: "BGE-embedding- en retrieval-toolkit voor RAG-systemen",
    },
  },
  {
    id: "curated-colbert",
    name: "ColBERT",
    href: "https://github.com/stanford-futuredata/ColBERT",
    category: "rag",
    addedOn: "2020-05-25",
    blurb: {
      en: "Late-interaction retrieval toolkit for high-quality RAG",
      nl: "Late-interaction retrieval-toolkit voor hoogwaardige RAG",
    },
  },
  {
    id: "curated-vespa",
    name: "Vespa",
    href: "https://github.com/vespa-engine/vespa",
    category: "rag",
    addedOn: "2016-06-03",
    blurb: {
      en: "Big data serving engine with native vector search",
      nl: "Big-data-serving-engine met native vectorzoeken",
    },
  },
  {
    id: "curated-pathway",
    name: "Pathway",
    href: "https://github.com/pathwaycom/pathway",
    category: "rag",
    addedOn: "2022-11-27",
    blurb: {
      en: "Realtime data processing framework for live RAG pipelines",
      nl: "Realtime dataverwerkingsframework voor live RAG-pipelines",
    },
  },
  {
    id: "curated-falkordb",
    name: "FalkorDB",
    href: "https://github.com/falkordb/falkordb",
    category: "rag",
    addedOn: "2023-07-20",
    blurb: {
      en: "Graph database optimized for GraphRAG workloads",
      nl: "Grafendatabase geoptimaliseerd voor GraphRAG-workloads",
    },
  },
  {
    id: "curated-pgai",
    name: "pgai",
    href: "https://github.com/timescale/pgai",
    category: "rag",
    addedOn: "2024-05-16",
    blurb: {
      en: "PostgreSQL extension tooling for AI and RAG workflows",
      nl: "PostgreSQL-extensietooling voor AI- en RAG-workflows",
    },
  },
  {
    id: "curated-supermemory",
    name: "Supermemory",
    href: "https://github.com/supermemoryai/supermemory",
    category: "rag",
    addedOn: "2024-02-27",
    blurb: {
      en: "Personal infinite memory API designed for AI apps",
      nl: "Persoonlijke oneindige-geheugen-API voor AI-apps",
    },
  },
  {
    id: "curated-flowise",
    name: "Flowise",
    href: "https://github.com/flowiseai/flowise",
    category: "agent-uis",
    addedOn: "2023-03-31",
    blurb: {
      en: "Drag-and-drop UI to build LLM flows and agents",
      nl: "Drag-and-drop-UI om LLM-flows en agents te bouwen",
    },
  },
  {
    id: "curated-chainlit",
    name: "Chainlit",
    href: "https://github.com/Chainlit/chainlit",
    category: "agent-uis",
    addedOn: "2023-03-14",
    blurb: {
      en: "Python framework to build conversational AI UIs quickly",
      nl: "Python-framework om snel conversationele AI-UI’s te bouwen",
    },
  },
  {
    id: "curated-cline",
    name: "Cline",
    href: "https://github.com/cline/cline",
    category: "agent-uis",
    addedOn: "2024-07-06",
    blurb: {
      en: "Autonomous coding agent extension for VS Code",
      nl: "Autonome codeeragent-extensie voor VS Code",
    },
  },
  {
    id: "curated-roo-code",
    name: "Roo Code",
    href: "https://github.com/RooCodeInc/Roo-Code",
    category: "agent-uis",
    addedOn: "2024-10-31",
    blurb: {
      en: "AI-powered autonomous coding agent for VS Code",
      nl: "AI-gedreven autonome codeeragent voor VS Code",
    },
  },
  {
    id: "curated-tabby",
    name: "Tabby",
    href: "https://github.com/TabbyML/tabby",
    category: "agent-uis",
    addedOn: "2023-03-16",
    blurb: {
      en: "Self-hosted open-source AI coding assistant",
      nl: "Zelf-gehoste open-source AI-codeerassistent",
    },
  },
  {
    id: "curated-copilotkit",
    name: "CopilotKit",
    href: "https://github.com/copilotkit/copilotkit",
    category: "agent-uis",
    addedOn: "2023-06-19",
    blurb: {
      en: "React UI primitives for in-app AI copilots",
      nl: "React-UI-primitives voor in-app AI-copilots",
    },
  },
  {
    id: "curated-assistant-ui",
    name: "assistant-ui",
    href: "https://github.com/assistant-ui/assistant-ui",
    category: "agent-uis",
    addedOn: "2023-11-22",
    blurb: {
      en: "React components for building AI chat interfaces",
      nl: "React-componenten voor AI-chatinterfaces",
    },
  },
  {
    id: "curated-void",
    name: "Void",
    href: "https://github.com/voideditor/void",
    category: "agent-uis",
    addedOn: "2024-09-11",
    blurb: {
      en: "Open-source Cursor-like AI code editor",
      nl: "Open-source Cursor-achtige AI-code-editor",
    },
  },
  {
    id: "curated-gpt4all",
    name: "GPT4All",
    href: "https://github.com/nomic-ai/gpt4all",
    category: "agent-uis",
    addedOn: "2023-03-27",
    blurb: {
      en: "Local chatbot ecosystem for running LLMs offline",
      nl: "Lokaal chatbot-ecosysteem om LLM’s offline te draaien",
    },
  },
  {
    id: "curated-sillytavern",
    name: "SillyTavern",
    href: "https://github.com/SillyTavern/SillyTavern",
    category: "agent-uis",
    addedOn: "2023-02-09",
    blurb: {
      en: "Local LLM frontend for character chat and extensions",
      nl: "Lokale LLM-frontend voor karakterchat en extensies",
    },
  },
  {
    id: "curated-skyvern",
    name: "Skyvern",
    href: "https://github.com/Skyvern-AI/skyvern",
    category: "agent-tools",
    addedOn: "2024-02-28",
    blurb: {
      en: "Browser automation with LLMs and computer vision",
      nl: "Browserautomatisering met LLM’s en computer vision",
    },
  },
  {
    id: "curated-stagehand",
    name: "Stagehand",
    href: "https://github.com/browserbase/stagehand",
    category: "agent-tools",
    addedOn: "2024-03-24",
    blurb: {
      en: "Browser automation framework for AI agents from Browserbase",
      nl: "Browserautomatiseringsframework voor AI-agents van Browserbase",
    },
  },
  {
    id: "curated-crawlee",
    name: "Crawlee",
    href: "https://github.com/apify/crawlee",
    category: "agent-tools",
    addedOn: "2016-08-26",
    blurb: {
      en: "Web scraping and browser automation library for Node.js",
      nl: "Webscraping- en browserautomatiseringslibrary voor Node.js",
    },
  },
  {
    id: "curated-e2b",
    name: "E2B",
    href: "https://github.com/e2b-dev/E2B",
    category: "agent-tools",
    addedOn: "2023-03-04",
    blurb: {
      en: "Secure cloud sandboxes for AI agents and code execution",
      nl: "Veilige cloudsandboxes voor AI-agents en code-uitvoering",
    },
  },
  {
    id: "curated-composio",
    name: "Composio",
    href: "https://github.com/ComposioHQ/composio",
    category: "agent-tools",
    addedOn: "2024-02-23",
    blurb: {
      en: "Toolset connecting agents to hundreds of external apps",
      nl: "Toolset die agents verbindt met honderden externe apps",
    },
  },
  {
    id: "curated-guardrails",
    name: "Guardrails",
    href: "https://github.com/guardrails-ai/guardrails",
    category: "agent-tools",
    addedOn: "2023-01-29",
    blurb: {
      en: "Add structure and validation guards around LLM inputs/outputs",
      nl: "Voeg structuur- en validatieguards toe rond LLM-invoer/uitvoer",
    },
  },
  {
    id: "curated-agentops",
    name: "AgentOps",
    href: "https://github.com/AgentOps-AI/agentops",
    category: "agent-tools",
    addedOn: "2023-08-15",
    blurb: {
      en: "Observability and testing toolkit for AI agents",
      nl: "Observability- en testtoolkit voor AI-agents",
    },
  },
  {
    id: "curated-trafilatura",
    name: "Trafilatura",
    href: "https://github.com/adbar/trafilatura",
    category: "agent-tools",
    addedOn: "2019-04-08",
    blurb: {
      en: "Web scraping library focused on main-text extraction for LLMs",
      nl: "Webscraping-library gericht op hoofdtekstextractie voor LLMs",
    },
  },
  {
    id: "curated-microsoft-playwright-mcp",
    name: "Playwright MCP",
    href: "https://github.com/microsoft/playwright-mcp",
    category: "agent-tools",
    addedOn: "2025-03-21",
    blurb: {
      en: "MCP server exposing Playwright browser automation to agents",
      nl: "MCP-server die Playwright-browserautomatisering aan agents blootstelt",
    },
  },
  {
    id: "curated-daytona",
    name: "Daytona",
    href: "https://github.com/daytonaio/daytona",
    category: "agent-tools",
    addedOn: "2024-02-06",
    blurb: {
      en: "Secure elastic infrastructure for running AI-generated code",
      nl: "Veilige elastische infrastructuur om AI-gegenereerde code te draaien",
    },
  },
  {
    id: "curated-openlit",
    name: "OpenLIT",
    href: "https://github.com/openlit/openlit",
    category: "agent-tools",
    addedOn: "2024-01-23",
    blurb: {
      en: "OpenTelemetry-native GenAI and agent observability",
      nl: "OpenTelemetry-native GenAI- en agent-observability",
    },
  },
  {
    id: "curated-llm-guard",
    name: "LLM Guard",
    href: "https://github.com/ProtectAI/llm-guard",
    category: "agent-tools",
    addedOn: "2023-07-27",
    blurb: {
      en: "Security toolkit for scanning and guarding LLM interactions",
      nl: "Security-toolkit voor het scannen en bewaken van LLM-interacties",
    },
  },
  {
    id: "curated-llama-cpp",
    name: "llama.cpp",
    href: "https://github.com/ggml-org/llama.cpp",
    category: "models",
    addedOn: "2023-03-10",
    blurb: {
      en: "C++ inference engine for running LLMs locally",
      nl: "C++-inference-engine om LLM’s lokaal te draaien",
    },
  },
  {
    id: "curated-whisper-cpp",
    name: "whisper.cpp",
    href: "https://github.com/ggml-org/whisper.cpp",
    category: "models",
    addedOn: "2022-09-25",
    blurb: {
      en: "C++ port of OpenAI Whisper for local speech-to-text",
      nl: "C++-port van OpenAI Whisper voor lokale speech-to-text",
    },
  },
  {
    id: "curated-mlc-llm",
    name: "MLC LLM",
    href: "https://github.com/mlc-ai/mlc-llm",
    category: "models",
    addedOn: "2023-04-29",
    blurb: {
      en: "Universal LLM deployment on phones GPUs and browsers",
      nl: "Universele LLM-deployment op telefoons, GPU’s en browsers",
    },
  },
  {
    id: "curated-tgi",
    name: "TGI",
    href: "https://github.com/huggingface/text-generation-inference",
    category: "models",
    addedOn: "2022-10-08",
    blurb: {
      en: "Hugging Face Text Generation Inference server",
      nl: "Hugging Face Text Generation Inference-server",
    },
  },
  {
    id: "curated-tensorrt-llm",
    name: "TensorRT-LLM",
    href: "https://github.com/NVIDIA/TensorRT-LLM",
    category: "models",
    addedOn: "2023-08-16",
    blurb: {
      en: "NVIDIA optimized LLM inference with TensorRT",
      nl: "NVIDIA-geoptimaliseerde LLM-inference met TensorRT",
    },
  },
  {
    id: "curated-sglang",
    name: "SGLang",
    href: "https://github.com/sgl-project/sglang",
    category: "models",
    addedOn: "2024-01-08",
    blurb: {
      en: "Fast serving framework for large language and vision models",
      nl: "Snel serving-framework voor grote taal- en visiemodellen",
    },
  },
  {
    id: "curated-paddlenlp",
    name: "PaddleNLP",
    href: "https://github.com/PaddlePaddle/PaddleNLP",
    category: "models",
    addedOn: "2021-02-05",
    blurb: {
      en: "Industrial NLP and LLM toolkit from PaddlePaddle",
      nl: "Industriële NLP- en LLM-toolkit van PaddlePaddle",
    },
  },
  {
    id: "curated-axolotl",
    name: "Axolotl",
    href: "https://github.com/axolotl-ai-cloud/axolotl",
    category: "models",
    addedOn: "2023-04-14",
    blurb: {
      en: "Tooling to fine-tune many open LLMs",
      nl: "Tooling om veel open LLM’s te fine-tunen",
    },
  },
  {
    id: "curated-unsloth",
    name: "Unsloth",
    href: "https://github.com/unslothai/unsloth",
    category: "models",
    addedOn: "2023-11-29",
    blurb: {
      en: "Faster fine-tuning for LLMs with lower memory",
      nl: "Snellere fine-tuning voor LLM’s met minder geheugen",
    },
  },
  {
    id: "curated-peft",
    name: "PEFT",
    href: "https://github.com/huggingface/peft",
    category: "models",
    addedOn: "2022-11-25",
    blurb: {
      en: "Parameter-efficient fine-tuning methods for Transformers",
      nl: "Parameter-efficiënte fine-tuningmethoden voor Transformers",
    },
  },
  {
    id: "curated-trl",
    name: "TRL",
    href: "https://github.com/huggingface/trl",
    category: "models",
    addedOn: "2020-03-27",
    blurb: {
      en: "Transformer Reinforcement Learning library for alignment",
      nl: "Transformer Reinforcement Learning-library voor alignment",
    },
  },
  {
    id: "curated-accelerate",
    name: "Accelerate",
    href: "https://github.com/huggingface/accelerate",
    category: "models",
    addedOn: "2020-10-30",
    blurb: {
      en: "Training and inference helpers for multi-GPU and TPU",
      nl: "Training- en inference-helpers voor multi-GPU en TPU",
    },
  },
  {
    id: "curated-diffusers",
    name: "Diffusers",
    href: "https://github.com/huggingface/diffusers",
    category: "models",
    addedOn: "2022-05-30",
    blurb: {
      en: "State-of-the-art diffusion model pipelines",
      nl: "State-of-the-art diffusion-modelpipelines",
    },
  },
  {
    id: "curated-tokenizers",
    name: "Tokenizers",
    href: "https://github.com/huggingface/tokenizers",
    category: "models",
    addedOn: "2019-11-01",
    blurb: {
      en: "Fast Rust-backed tokenizers used across HF models",
      nl: "Snelle Rust-backed tokenizers gebruikt in HF-modellen",
    },
  },
  {
    id: "curated-gpt-neox",
    name: "GPT-NeoX",
    href: "https://github.com/EleutherAI/gpt-neox",
    category: "models",
    addedOn: "2020-12-22",
    blurb: {
      en: "Large-scale autoregressive language model training codebase",
      nl: "Grootschalige autoregressieve taalmodel-trainingscodebase",
    },
  },
  {
    id: "curated-deepspeed",
    name: "DeepSpeed",
    href: "https://github.com/deepspeedai/DeepSpeed",
    category: "models",
    addedOn: "2020-01-23",
    blurb: {
      en: "Deep learning optimization library for training at scale",
      nl: "Deep-learning-optimalisatiebibliotheek voor training op schaal",
    },
  },
] as const;
