import type { AwesomeSeed } from "./awesome-ai-oss";

/**
 * Chunk 3/6 curated seeds. `addedOn` is the live GitHub `created_at` date
 * (UTC, fetched 2026-09-14) — not a popularity or star signal.
 */
export const AWESOME_AI_OSS_SEEDS_CHUNK_3: readonly AwesomeSeed[] = [
  {
    id: "curated-sqlite-vec",
    name: "sqlite-vec",
    href: "https://github.com/asg017/sqlite-vec",
    category: "rag-memory",
    addedOn: "2024-04-20",
    blurb: {
      en: "Vector search extension for SQLite",
      nl: "Vectorzoek-extensie voor SQLite",
    },
  },
  {
    id: "curated-unstructured",
    name: "Unstructured",
    href: "https://github.com/Unstructured-IO/unstructured",
    category: "rag-memory",
    addedOn: "2022-09-26",
    blurb: {
      en: "ETL that turns unstructured documents into LLM-ready data",
      nl: "ETL die ongestructureerde documenten omzet naar LLM-klare data",
    },
  },
  {
    id: "curated-docling",
    name: "Docling",
    href: "https://github.com/docling-project/docling",
    category: "rag-memory",
    addedOn: "2024-07-09",
    blurb: {
      en: "Document conversion toolkit for PDFs and office files",
      nl: "Documentconversie-toolkit voor PDF’s en Office-bestanden",
    },
  },
  {
    id: "curated-markitdown",
    name: "MarkItDown",
    href: "https://github.com/microsoft/markitdown",
    category: "rag-memory",
    addedOn: "2024-11-13",
    blurb: {
      en: "Converts files and office documents to Markdown for LLM pipelines",
      nl: "Zet bestanden en Office-documenten om naar Markdown voor LLM-pipelines",
    },
  },
  {
    id: "curated-mineru",
    name: "MinerU",
    href: "https://github.com/opendatalab/MinerU",
    category: "rag-memory",
    addedOn: "2024-02-29",
    blurb: {
      en: "Parses complex PDFs/Office docs into LLM-ready Markdown/JSON",
      nl: "Zet complexe PDF’s/Office-docs om naar LLM-klare Markdown/JSON",
    },
  },
  {
    id: "curated-sentence-transformers",
    name: "sentence-transformers",
    href: "https://github.com/huggingface/sentence-transformers",
    category: "rag-memory",
    addedOn: "2019-07-24",
    blurb: {
      en: "Embeddings, retrieval, and reranking for semantic search and RAG",
      nl: "Embeddings, retrieval en reranking voor semantisch zoeken en RAG",
    },
  },
  {
    id: "curated-llamaindex",
    name: "LlamaIndex",
    href: "https://github.com/run-llama/llama_index",
    category: "rag-memory",
    addedOn: "2022-11-02",
    blurb: {
      en: "Data framework for connecting LLMs to private data and building RAG",
      nl: "Dataframework om LLM’s aan privédata te koppelen en RAG te bouwen",
    },
  },
  {
    id: "curated-anythingllm",
    name: "AnythingLLM",
    href: "https://github.com/Mintplex-Labs/anything-llm",
    category: "agent-uis",
    addedOn: "2023-06-04",
    blurb: {
      en: "Self-hosted AI workspace with RAG, agents, and chat",
      nl: "Zelf-gehoste AI-werkplek met RAG, agents en chat",
    },
  },
  {
    id: "curated-khoj",
    name: "Khoj",
    href: "https://github.com/khoj-ai/khoj",
    category: "agent-uis",
    addedOn: "2021-08-16",
    blurb: {
      en: "Self-hostable second brain: answers from the web or your docs",
      nl: "Zelf-hostbaar tweede brein: antwoorden van het web of je documenten",
    },
  },
  {
    id: "curated-librechat",
    name: "LibreChat",
    href: "https://github.com/danny-avila/LibreChat",
    category: "agent-uis",
    addedOn: "2023-02-12",
    blurb: {
      en: "Self-hosted multi-provider AI chat UI with agents, RAG, and tools",
      nl: "Zelf-gehoste multi-provider AI-chat-UI met agents, RAG en tools",
    },
  },
  {
    id: "curated-dify",
    name: "Dify",
    href: "https://github.com/langgenius/dify",
    category: "agent-uis",
    addedOn: "2023-04-12",
    blurb: {
      en: "Open-source LLM app platform with visual agent/RAG workflows",
      nl: "Open-source LLM-appplatform met visuele agent/RAG-workflows",
    },
  },
  {
    id: "curated-open-webui",
    name: "Open WebUI",
    href: "https://github.com/open-webui/open-webui",
    category: "agent-uis",
    addedOn: "2023-10-06",
    blurb: {
      en: "Self-hosted ChatGPT-style UI for Ollama and OpenAI-compatible APIs",
      nl: "Zelf-gehoste ChatGPT-achtige UI voor Ollama en OpenAI-compatibele API’s",
    },
  },
  {
    id: "curated-continue",
    name: "Continue",
    href: "https://github.com/continuedev/continue",
    category: "agent-uis",
    addedOn: "2023-05-24",
    blurb: {
      en: "Open-source AI coding assistant for VS Code and JetBrains",
      nl: "Open-source AI-codeerassistent voor VS Code en JetBrains",
    },
  },
  {
    id: "curated-gpt-researcher",
    name: "GPT Researcher",
    href: "https://github.com/assafelovic/gpt-researcher",
    category: "agent-tools",
    addedOn: "2023-05-12",
    blurb: {
      en: "Autonomous agent that researches a topic and writes a sourced report",
      nl: "Autonome agent die een onderwerp onderzoekt en een bronnenrapport schrijft",
    },
  },
  {
    id: "curated-firecrawl",
    name: "Firecrawl",
    href: "https://github.com/firecrawl/firecrawl",
    category: "agent-tools",
    addedOn: "2024-04-15",
    blurb: {
      en: "Crawler/API that turns websites into LLM-ready markdown",
      nl: "Crawler/API die websites omzet naar LLM-klare markdown",
    },
  },
  {
    id: "curated-browser-use",
    name: "browser-use",
    href: "https://github.com/browser-use/browser-use",
    category: "agent-tools",
    addedOn: "2024-10-31",
    blurb: {
      en: "Library that lets AI agents operate a real browser",
      nl: "Library waarmee AI-agents een echte browser bedienen",
    },
  },
  {
    id: "curated-searxng",
    name: "SearXNG",
    href: "https://github.com/searxng/searxng",
    category: "agent-tools",
    addedOn: "2021-04-12",
    blurb: {
      en: "Self-hosted metasearch for private agentic search",
      nl: "Zelf-gehoste metasearch voor privé agentic zoeken",
    },
  },
  {
    id: "curated-jina-reader",
    name: "jina-reader",
    href: "https://github.com/jina-ai/reader",
    category: "agent-tools",
    addedOn: "2024-04-10",
    blurb: {
      en: "Converts any URL into LLM-friendly text",
      nl: "Zet elke URL om naar LLM-vriendelijke tekst",
    },
  },
  {
    id: "curated-open-deep-research",
    name: "open_deep_research",
    href: "https://github.com/langchain-ai/open_deep_research",
    category: "agent-tools",
    addedOn: "2024-11-20",
    blurb: {
      en: "Open implementation of iterative deep-research agents",
      nl: "Open implementatie van iteratieve deep-research-agents",
    },
  },
  {
    id: "curated-storm",
    name: "STORM",
    href: "https://github.com/stanford-oval/storm",
    category: "agent-tools",
    addedOn: "2024-03-24",
    blurb: {
      en: "LLM knowledge-curation system that researches and writes articles",
      nl: "LLM-kenniscuratiesysteem dat onderzoek doet en artikelen schrijft",
    },
  },
  {
    id: "curated-crawl4ai",
    name: "Crawl4AI",
    href: "https://github.com/unclecode/crawl4ai",
    category: "agent-tools",
    addedOn: "2024-05-09",
    blurb: {
      en: "LLM-friendly web crawler and scraper designed for AI agents and RAG",
      nl: "LLM-vriendelijke webcrawler en scraper voor AI-agents en RAG",
    },
  },
  {
    id: "curated-langfuse",
    name: "Langfuse",
    href: "https://github.com/langfuse/langfuse",
    category: "eval-observability",
    addedOn: "2023-05-18",
    blurb: {
      en: "Open-source tracing, prompt management, and evals",
      nl: "Open-source tracing, promptbeheer en evals",
    },
  },
  {
    id: "curated-promptfoo",
    name: "Promptfoo",
    href: "https://github.com/promptfoo/promptfoo",
    category: "eval-observability",
    addedOn: "2023-04-28",
    blurb: {
      en: "Eval and red-teaming toolkit for prompts, agents, and RAG",
      nl: "Eval- en red-teaming-toolkit voor prompts, agents en RAG",
    },
  },
  {
    id: "curated-ragas",
    name: "Ragas",
    href: "https://github.com/vibrantlabsai/ragas",
    category: "eval-observability",
    addedOn: "2023-05-08",
    blurb: {
      en: "Evaluation framework for RAG pipelines",
      nl: "Evaluatieframework voor RAG-pipelines",
    },
  },
  {
    id: "curated-deepeval",
    name: "DeepEval",
    href: "https://github.com/confident-ai/deepeval",
    category: "eval-observability",
    addedOn: "2023-08-10",
    blurb: {
      en: "LLM evaluation framework with RAG and agent metrics",
      nl: "LLM-evaluatieframework met RAG- en agentmetrics",
    },
  },
  {
    id: "curated-giskard",
    name: "Giskard",
    href: "https://github.com/Giskard-AI/giskard-oss",
    category: "eval-observability",
    addedOn: "2022-03-06",
    blurb: {
      en: "Open-source evaluation and testing library for LLM agents",
      nl: "Open-source evaluatie- en testbibliotheek voor LLM-agents",
    },
  },
  {
    id: "curated-trulens",
    name: "TruLens",
    href: "https://github.com/truera/trulens",
    category: "eval-observability",
    addedOn: "2020-11-02",
    blurb: {
      en: "Evaluation and tracking for LLM apps including RAG-triad metrics",
      nl: "Evaluatie en tracking voor LLM-apps, inclusief RAG-triad-metrics",
    },
  },
  {
    id: "curated-phoenix",
    name: "Phoenix",
    href: "https://github.com/Arize-ai/phoenix",
    category: "eval-observability",
    addedOn: "2022-11-09",
    blurb: {
      en: "Arize open-source AI observability and evaluation",
      nl: "Arize open-source AI-observability en -evaluatie",
    },
  },
  {
    id: "curated-helicone",
    name: "Helicone",
    href: "https://github.com/Helicone/helicone",
    category: "eval-observability",
    addedOn: "2023-01-31",
    blurb: {
      en: "Open-source LLM observability, gateway, and prompt management",
      nl: "Open-source LLM-observability, gateway en promptbeheer",
    },
  },
  {
    id: "curated-litellm",
    name: "LiteLLM",
    href: "https://github.com/BerriAI/litellm",
    category: "eval-observability",
    addedOn: "2023-07-27",
    blurb: {
      en: "Unified SDK/proxy to call 100+ LLM APIs in OpenAI format",
      nl: "Geünificeerde SDK/proxy om 100+ LLM-API’s in OpenAI-formaat aan te roepen",
    },
  },
  {
    id: "curated-portkey-gateway",
    name: "Portkey Gateway",
    href: "https://github.com/Portkey-AI/gateway",
    category: "eval-observability",
    addedOn: "2023-08-23",
    blurb: {
      en: "Open-source AI gateway for routing, fallbacks, guardrails",
      nl: "Open-source AI-gateway voor routing, fallbacks en guardrails",
    },
  },
  {
    id: "curated-ragchecker",
    name: "RAGChecker",
    href: "https://github.com/amazon-science/RAGChecker",
    category: "eval-observability",
    addedOn: "2024-06-24",
    blurb: {
      en: "Fine-grained diagnosis and evaluation for RAG systems",
      nl: "Fijnmazige diagnose en evaluatie voor RAG-systemen",
    },
  },
  {
    id: "curated-langchain",
    name: "LangChain",
    href: "https://github.com/langchain-ai/langchain",
    category: "frameworks",
    addedOn: "2022-10-17",
    blurb: {
      en: "Composable framework for LLM apps, tools, memory, and agents",
      nl: "Composeerbaar framework voor LLM-apps, tools, geheugen en agents",
    },
  },
  {
    id: "curated-autogen",
    name: "AutoGen",
    href: "https://github.com/microsoft/autogen",
    category: "frameworks",
    addedOn: "2023-08-18",
    blurb: {
      en: "Multi-agent conversation framework from Microsoft Research",
      nl: "Multi-agent-conversatieframework van Microsoft Research",
    },
  },
  {
    id: "curated-crewai",
    name: "CrewAI",
    href: "https://github.com/crewAIInc/crewAI",
    category: "frameworks",
    addedOn: "2023-10-27",
    blurb: {
      en: "Role-playing multi-agent orchestration framework",
      nl: "Role-playing multi-agent-orchestratieframework",
    },
  },
  {
    id: "curated-semantic-kernel",
    name: "Semantic Kernel",
    href: "https://github.com/microsoft/semantic-kernel",
    category: "frameworks",
    addedOn: "2023-02-27",
    blurb: {
      en: "Enterprise SDK for AI agents and orchestration (.NET/Python/Java)",
      nl: "Enterprise-SDK voor AI-agents en orchestratie (.NET/Python/Java)",
    },
  },
  {
    id: "curated-aider",
    name: "Aider",
    href: "https://github.com/Aider-AI/aider",
    category: "frameworks",
    addedOn: "2023-05-09",
    blurb: {
      en: "AI pair programming in the terminal that edits local git repos",
      nl: "AI-pair-programming in de terminal die lokale git-repo’s bewerkt",
    },
  },
  {
    id: "curated-smolagents",
    name: "Smolagents",
    href: "https://github.com/huggingface/smolagents",
    category: "frameworks",
    addedOn: "2024-12-05",
    blurb: {
      en: "Barebones Hugging Face library for code-writing and tool-calling agents",
      nl: "Kale Hugging Face-library voor code-schrijvende en tool-calling agents",
    },
  },
  {
    id: "curated-deepagents",
    name: "Deep Agents",
    href: "https://github.com/langchain-ai/deepagents",
    category: "frameworks",
    addedOn: "2025-07-27",
    blurb: {
      en: "Batteries-included agent harness built on LangChain",
      nl: "Agent-harness met batterijen inbegrepen, gebouwd op LangChain",
    },
  },
  {
    id: "curated-ag2",
    name: "AG2",
    href: "https://github.com/ag2ai/ag2",
    category: "frameworks",
    addedOn: "2024-11-11",
    blurb: {
      en: "Open-source AgentOS multi-agent framework (AutoGen lineage)",
      nl: "Open-source AgentOS multi-agent-framework (AutoGen-lijn)",
    },
  },
  {
    id: "curated-camel",
    name: "CAMEL",
    href: "https://github.com/camel-ai/camel",
    category: "frameworks",
    addedOn: "2023-03-17",
    blurb: {
      en: "Communicative multi-agent framework for role-playing agents",
      nl: "Communicatief multi-agent-framework voor role-playing agents",
    },
  },
  {
    id: "curated-mastra",
    name: "Mastra",
    href: "https://github.com/mastra-ai/mastra",
    category: "frameworks",
    addedOn: "2024-08-06",
    blurb: {
      en: "TypeScript agent framework with workflows, memory, and tools",
      nl: "TypeScript-agentframework met workflows, geheugen en tools",
    },
  },
  {
    id: "curated-eliza",
    name: "Eliza",
    href: "https://github.com/elizaOS/eliza",
    category: "frameworks",
    addedOn: "2024-07-09",
    blurb: {
      en: "Multi-agent framework for autonomous character agents",
      nl: "Multi-agent-framework voor autonome karakteragents",
    },
  },
  {
    id: "curated-n8n",
    name: "n8n",
    href: "https://github.com/n8n-io/n8n",
    category: "frameworks",
    addedOn: "2019-06-22",
    blurb: {
      en: "Fair-code workflow automation platform with AI agent nodes",
      nl: "Fair-code workflow-automatisering met AI-agentnodes",
    },
  },
  {
    id: "curated-griptape",
    name: "Griptape",
    href: "https://github.com/griptape-ai/griptape",
    category: "frameworks",
    addedOn: "2023-01-14",
    blurb: {
      en: "Python framework for building AI agents and secure workflows",
      nl: "Python-framework voor AI-agents en veilige workflows",
    },
  },
  {
    id: "curated-google-adk",
    name: "Google ADK",
    href: "https://github.com/google/adk-python",
    category: "frameworks",
    addedOn: "2025-04-01",
    blurb: {
      en: "Agent Development Kit for building multi-agent systems",
      nl: "Agent Development Kit voor het bouwen van multi-agent-systemen",
    },
  },
  {
    id: "curated-autogpt",
    name: "AutoGPT",
    href: "https://github.com/Significant-Gravitas/AutoGPT",
    category: "frameworks",
    addedOn: "2023-03-16",
    blurb: {
      en: "Autonomous AI agent platform for goal-driven task execution",
      nl: "Autonoom AI-agentplatform voor doelgedreven taakuitvoering",
    },
  },
  {
    id: "curated-openmanus",
    name: "OpenManus",
    href: "https://github.com/FoundationAgents/OpenManus",
    category: "frameworks",
    addedOn: "2025-03-06",
    blurb: {
      en: "Open-source general AI agent inspired by Manus",
      nl: "Open-source algemene AI-agent, geïnspireerd door Manus",
    },
  },
  {
    id: "curated-vercel-ai-sdk",
    name: "Vercel AI SDK",
    href: "https://github.com/vercel/ai",
    category: "frameworks",
    addedOn: "2023-05-23",
    blurb: {
      en: "TypeScript toolkit for building AI apps and streaming UIs",
      nl: "TypeScript-toolkit voor AI-apps en streaming-UI’s",
    },
  },
  {
    id: "curated-taskweaver",
    name: "TaskWeaver",
    href: "https://github.com/microsoft/TaskWeaver",
    category: "frameworks",
    addedOn: "2023-09-11",
    blurb: {
      en: "Code-first agent framework for data analytics tasks",
      nl: "Code-first agentframework voor data-analysetaken",
    },
  },
] as const;
