import type { AwesomeSeed } from "./awesome-ai-oss";

/**
 * Curated chunk 2/6 (50 live GitHub repos). `addedOn` is the frozen GitHub
 * created date — not a popularity signal. Adds RAG & memory.
 */
export const AWESOME_AI_OSS_SEEDS_CHUNK_2 = [
  {
    id: "curated-notion-mcp-server",
    name: "makenotion/notion-mcp-server",
    href: "https://github.com/makenotion/notion-mcp-server",
    category: "runtimes",
    addedOn: "2025-03-10",
    blurb: {
      en: "Official Notion MCP server",
      nl: "Officiële Notion-MCP-server",
    },
  },
  {
    id: "curated-devhub-cms-mcp",
    name: "devhub/devhub-cms-mcp",
    href: "https://github.com/devhub/devhub-cms-mcp",
    category: "runtimes",
    addedOn: "2025-03-17",
    blurb: {
      en: "DevHub CMS MCP server",
      nl: "DevHub CMS MCP-server",
    },
  },
  {
    id: "curated-heroku-mcp-server",
    name: "heroku/heroku-mcp-server",
    href: "https://github.com/heroku/heroku-mcp-server",
    category: "runtimes",
    addedOn: "2025-03-26",
    blurb: {
      en: "Official Heroku MCP server",
      nl: "Officiële Heroku-MCP-server",
    },
  },
  {
    id: "curated-baidu-maps-mcp",
    name: "baidu-maps/mcp",
    href: "https://github.com/baidu-maps/mcp",
    category: "runtimes",
    addedOn: "2025-03-20",
    blurb: {
      en: "Baidu Maps MCP server",
      nl: "Baidu Maps MCP-server",
    },
  },
  {
    id: "curated-solana-dev-mcp",
    name: "solana-foundation/solana-dev-mcp",
    href: "https://github.com/solana-foundation/solana-dev-mcp",
    category: "runtimes",
    addedOn: "2025-03-09",
    blurb: {
      en: "Solana developer MCP server",
      nl: "Solana-developer-MCP-server",
    },
  },
  {
    id: "curated-onchain-mcp",
    name: "bankless/onchain-mcp",
    href: "https://github.com/bankless/onchain-mcp",
    category: "runtimes",
    addedOn: "2025-03-10",
    blurb: {
      en: "Bankless onchain MCP server",
      nl: "Bankless onchain-MCP-server",
    },
  },
  {
    id: "curated-opik-mcp",
    name: "comet-ml/opik-mcp",
    href: "https://github.com/comet-ml/opik-mcp",
    category: "runtimes",
    addedOn: "2025-03-11",
    blurb: {
      en: "Opik MCP server for LLM observability",
      nl: "Opik-MCP-server voor LLM-observability",
    },
  },
  {
    id: "curated-dynatrace-mcp",
    name: "dynatrace-oss/dynatrace-mcp",
    href: "https://github.com/dynatrace-oss/dynatrace-mcp",
    category: "runtimes",
    addedOn: "2025-04-23",
    blurb: {
      en: "Dynatrace MCP server",
      nl: "Dynatrace-MCP-server",
    },
  },
  {
    id: "curated-mcp-grafana",
    name: "grafana/mcp-grafana",
    href: "https://github.com/grafana/mcp-grafana",
    category: "runtimes",
    addedOn: "2024-12-24",
    blurb: {
      en: "Official Grafana MCP server",
      nl: "Officiële Grafana-MCP-server",
    },
  },
  {
    id: "curated-terraform-mcp-server",
    name: "hashicorp/terraform-mcp-server",
    href: "https://github.com/hashicorp/terraform-mcp-server",
    category: "runtimes",
    addedOn: "2025-04-19",
    blurb: {
      en: "Official HashiCorp Terraform MCP server",
      nl: "Officiële HashiCorp Terraform-MCP-server",
    },
  },
  {
    id: "curated-trivy-mcp",
    name: "aquasecurity/trivy-mcp",
    href: "https://github.com/aquasecurity/trivy-mcp",
    category: "runtimes",
    addedOn: "2025-04-24",
    blurb: {
      en: "Trivy MCP server for security scanning",
      nl: "Trivy-MCP-server voor security-scanning",
    },
  },
  {
    id: "curated-hf-mcp-server",
    name: "huggingface/hf-mcp-server",
    href: "https://github.com/huggingface/hf-mcp-server",
    category: "runtimes",
    addedOn: "2025-05-06",
    blurb: {
      en: "Hugging Face Hub MCP server",
      nl: "Hugging Face Hub MCP-server",
    },
  },
  {
    id: "curated-smithery-cli",
    name: "smithery-ai/cli",
    href: "https://github.com/smithery-ai/cli",
    category: "runtimes",
    addedOn: "2024-12-22",
    blurb: {
      en: "Smithery CLI to discover and run MCP servers",
      nl: "Smithery-CLI om MCP-servers te vinden en te draaien",
    },
  },
  {
    id: "curated-template-mcp-server",
    name: "mcpdotdirect/template-mcp-server",
    href: "https://github.com/mcpdotdirect/template-mcp-server",
    category: "protocols",
    addedOn: "2025-03-10",
    blurb: {
      en: "Template for building custom MCP servers",
      nl: "Template voor eigen MCP-servers",
    },
  },
  {
    id: "curated-atlas-mcp-server",
    name: "cyanheads/atlas-mcp-server",
    href: "https://github.com/cyanheads/atlas-mcp-server",
    category: "runtimes",
    addedOn: "2024-12-16",
    blurb: {
      en: "ATLAS knowledge-graph MCP memory server",
      nl: "ATLAS knowledge-graph MCP-geheugenserver",
    },
  },
  {
    id: "curated-mcp-memory-service",
    name: "doobidoo/mcp-memory-service",
    href: "https://github.com/doobidoo/mcp-memory-service",
    category: "runtimes",
    addedOn: "2024-12-26",
    blurb: {
      en: "Semantic memory MCP service with embeddings",
      nl: "Semantische-geheugen-MCP-service met embeddings",
    },
  },
  {
    id: "curated-mcp-miro",
    name: "evalstate/mcp-miro",
    href: "https://github.com/evalstate/mcp-miro",
    category: "runtimes",
    addedOn: "2024-11-28",
    blurb: {
      en: "Miro board MCP server",
      nl: "Miro-board-MCP-server",
    },
  },
  {
    id: "curated-blender-mcp",
    name: "ahujasid/blender-mcp",
    href: "https://github.com/ahujasid/blender-mcp",
    category: "runtimes",
    addedOn: "2025-03-07",
    blurb: {
      en: "Blender MCP server for 3D scene control",
      nl: "Blender-MCP-server voor 3D-scènebesturing",
    },
  },
  {
    id: "curated-mcp-obsidian",
    name: "MarkusPfundstein/mcp-obsidian",
    href: "https://github.com/MarkusPfundstein/mcp-obsidian",
    category: "runtimes",
    addedOn: "2024-11-29",
    blurb: {
      en: "MCP server for Obsidian notes",
      nl: "MCP-server voor Obsidian-notities",
    },
  },
  {
    id: "curated-mcp-server-openai",
    name: "pierrebrunelle/mcp-server-openai",
    href: "https://github.com/pierrebrunelle/mcp-server-openai",
    category: "runtimes",
    addedOn: "2024-11-28",
    blurb: {
      en: "Bridge OpenAI APIs through MCP",
      nl: "Brug van OpenAI-API’s via MCP",
    },
  },
  {
    id: "curated-agno",
    name: "Agno",
    href: "https://github.com/agno-agi/agno",
    category: "frameworks",
    addedOn: "2022-05-04",
    blurb: {
      en: "Python framework to build, run, and manage multi-agent platforms (formerly Phidata)",
      nl: "Python-framework om multi-agent-platforms te bouwen, draaien en beheren (voorheen Phidata)",
    },
  },
  {
    id: "curated-pydantic-ai",
    name: "PydanticAI",
    href: "https://github.com/pydantic/pydantic-ai",
    category: "frameworks",
    addedOn: "2024-06-21",
    blurb: {
      en: "Type-safe Python agent framework from the Pydantic team",
      nl: "Typeveilig Python-agentframework van het Pydantic-team",
    },
  },
  {
    id: "curated-instructor",
    name: "Instructor",
    href: "https://github.com/567-labs/instructor",
    category: "frameworks",
    addedOn: "2023-06-14",
    blurb: {
      en: "Structured LLM outputs via Pydantic validation",
      nl: "Gestructureerde LLM-output via Pydantic-validatie",
    },
  },
  {
    id: "curated-outlines",
    name: "Outlines",
    href: "https://github.com/dottxt-ai/outlines",
    category: "frameworks",
    addedOn: "2023-03-17",
    blurb: {
      en: "Structured generation and constrained decoding for LLMs",
      nl: "Gestructureerde generatie en constrained decoding voor LLMs",
    },
  },
  {
    id: "curated-dspy",
    name: "DSPy",
    href: "https://github.com/stanfordnlp/dspy",
    category: "frameworks",
    addedOn: "2023-01-09",
    blurb: {
      en: "Framework for programming—not prompting—language-model pipelines",
      nl: "Framework om taalmodel-pipelines te programmeren, niet te prompten",
    },
  },
  {
    id: "curated-guidance",
    name: "Guidance",
    href: "https://github.com/guidance-ai/guidance",
    category: "frameworks",
    addedOn: "2022-11-10",
    blurb: {
      en: "Guidance language for controlling large language model generation",
      nl: "Guidance-taal voor het sturen van LLM-generatie",
    },
  },
  {
    id: "curated-babyagi",
    name: "BabyAGI",
    href: "https://github.com/yoheinakajima/babyagi",
    category: "frameworks",
    addedOn: "2023-04-03",
    blurb: {
      en: "Historical task-driven autonomous agent loop",
      nl: "Historische taakgedreven autonome agent-loop",
    },
  },
  {
    id: "curated-metagpt",
    name: "MetaGPT",
    href: "https://github.com/FoundationAgents/MetaGPT",
    category: "frameworks",
    addedOn: "2023-06-30",
    blurb: {
      en: "Multi-agent framework that simulates a software company",
      nl: "Multi-agent-framework dat een softwarebedrijf simuleert",
    },
  },
  {
    id: "curated-chatdev",
    name: "ChatDev",
    href: "https://github.com/OpenBMB/ChatDev",
    category: "frameworks",
    addedOn: "2023-08-28",
    blurb: {
      en: "Communicative multi-agent framework for collaborative software development",
      nl: "Communicatief multi-agent-framework voor collaboratieve softwareontwikkeling",
    },
  },
  {
    id: "curated-openhands",
    name: "OpenHands",
    href: "https://github.com/OpenHands/OpenHands",
    category: "frameworks",
    addedOn: "2024-03-13",
    blurb: {
      en: "Open software-engineering agent platform (formerly OpenDevin / All-Hands-AI)",
      nl: "Open software-engineering-agentplatform (voorheen OpenDevin / All-Hands-AI)",
    },
  },
  {
    id: "curated-swe-agent",
    name: "SWE-agent",
    href: "https://github.com/SWE-agent/SWE-agent",
    category: "frameworks",
    addedOn: "2024-04-02",
    blurb: {
      en: "Agent that uses a computer interface to automatically fix GitHub issues",
      nl: "Agent die via een computerinterface automatisch GitHub-issues fixt",
    },
  },
  {
    id: "curated-superagent",
    name: "Superagent",
    href: "https://github.com/superagent-ai/superagent",
    category: "frameworks",
    addedOn: "2023-05-10",
    blurb: {
      en: "Guardrails runtime for AI apps against prompt injection and data leaks",
      nl: "Guardrails-runtime voor AI-apps tegen prompt injection en datalekken",
    },
  },
  {
    id: "curated-haystack",
    name: "Haystack",
    href: "https://github.com/deepset-ai/haystack",
    category: "rag",
    addedOn: "2019-11-14",
    blurb: {
      en: "Open-source orchestration framework for production RAG and LLM applications",
      nl: "Open-source orchestratieframework voor productie-RAG en LLM-apps",
    },
  },
  {
    id: "curated-txtai",
    name: "txtai",
    href: "https://github.com/neuml/txtai",
    category: "rag",
    addedOn: "2020-08-09",
    blurb: {
      en: "All-in-one embeddings, semantic search, and RAG workflow framework",
      nl: "All-in-one embeddings, semantisch zoeken en RAG-workflowframework",
    },
  },
  {
    id: "curated-private-gpt",
    name: "PrivateGPT",
    href: "https://github.com/zylon-ai/private-gpt",
    category: "rag",
    addedOn: "2023-05-02",
    blurb: {
      en: "Private local RAG API over documents and local models",
      nl: "Privé lokale RAG-API over documenten en lokale modellen",
    },
  },
  {
    id: "curated-quivr",
    name: "Quivr",
    href: "https://github.com/The-Vibe-Company/quivr",
    category: "rag",
    addedOn: "2023-05-12",
    blurb: {
      en: "Opinionated RAG platform for integrating GenAI into applications",
      nl: "Opinionated RAG-platform om GenAI in apps te integreren",
    },
  },
  {
    id: "curated-ragflow",
    name: "RAGFlow",
    href: "https://github.com/infiniflow/ragflow",
    category: "rag",
    addedOn: "2023-12-12",
    blurb: {
      en: "Open-source RAG engine with deep document understanding",
      nl: "Open-source RAG-engine met diep documentbegrip",
    },
  },
  {
    id: "curated-lightrag",
    name: "LightRAG",
    href: "https://github.com/HKUDS/LightRAG",
    category: "rag",
    addedOn: "2024-10-02",
    blurb: {
      en: "Simple, fast graph-based retrieval-augmented generation",
      nl: "Eenvoudige, snelle graafgebaseerde retrieval-augmented generation",
    },
  },
  {
    id: "curated-graphrag",
    name: "GraphRAG",
    href: "https://github.com/microsoft/graphrag",
    category: "rag",
    addedOn: "2024-03-27",
    blurb: {
      en: "Modular graph-based RAG for extracting structured knowledge from text",
      nl: "Modulaire graafgebaseerde RAG om gestructureerde kennis uit tekst te halen",
    },
  },
  {
    id: "curated-mem0",
    name: "mem0",
    href: "https://github.com/mem0ai/mem0",
    category: "rag",
    addedOn: "2023-06-20",
    blurb: {
      en: "Drop-in memory layer for AI agents and apps",
      nl: "Drop-in geheugenlaag voor AI-agents en apps",
    },
  },
  {
    id: "curated-graphiti",
    name: "Graphiti",
    href: "https://github.com/getzep/graphiti",
    category: "rag",
    addedOn: "2024-08-08",
    blurb: {
      en: "Real-time temporal knowledge graphs for agent memory",
      nl: "Realtime temporele knowledge graphs voor agentgeheugen",
    },
  },
  {
    id: "curated-letta",
    name: "Letta",
    href: "https://github.com/letta-ai/letta",
    category: "rag",
    addedOn: "2023-10-11",
    blurb: {
      en: "Stateful agent runtime with long-term memory (formerly MemGPT)",
      nl: "Stateful agent-runtime met langetermijngeheugen (voorheen MemGPT)",
    },
  },
  {
    id: "curated-cognee",
    name: "cognee",
    href: "https://github.com/topoteretes/cognee",
    category: "rag",
    addedOn: "2023-08-16",
    blurb: {
      en: "Open-source AI memory platform that builds knowledge graphs for agents",
      nl: "Open-source AI-geheugenplatform dat knowledge graphs voor agents bouwt",
    },
  },
  {
    id: "curated-qdrant",
    name: "Qdrant",
    href: "https://github.com/qdrant/qdrant",
    category: "rag",
    addedOn: "2020-05-30",
    blurb: {
      en: "Open-source vector database and similarity search engine",
      nl: "Open-source vectordatabase en similarity-search-engine",
    },
  },
  {
    id: "curated-milvus",
    name: "Milvus",
    href: "https://github.com/milvus-io/milvus",
    category: "rag",
    addedOn: "2019-09-16",
    blurb: {
      en: "Cloud-native open-source vector database for ANN search",
      nl: "Cloud-native open-source vectordatabase voor ANN-search",
    },
  },
  {
    id: "curated-weaviate",
    name: "Weaviate",
    href: "https://github.com/weaviate/weaviate",
    category: "rag",
    addedOn: "2016-03-30",
    blurb: {
      en: "Open-source vector database with hybrid search",
      nl: "Open-source vectordatabase met hybride search",
    },
  },
  {
    id: "curated-chroma",
    name: "Chroma",
    href: "https://github.com/chroma-core/chroma",
    category: "rag",
    addedOn: "2022-10-05",
    blurb: {
      en: "Open-source embedding database for AI apps",
      nl: "Open-source embedding-database voor AI-apps",
    },
  },
  {
    id: "curated-lancedb",
    name: "LanceDB",
    href: "https://github.com/lancedb/lancedb",
    category: "rag",
    addedOn: "2023-02-28",
    blurb: {
      en: "Embedded multimodal retrieval database built on Lance",
      nl: "Embedded multimodale retrieval-database op Lance",
    },
  },
  {
    id: "curated-pgvector",
    name: "pgvector",
    href: "https://github.com/pgvector/pgvector",
    category: "rag",
    addedOn: "2021-04-20",
    blurb: {
      en: "Vector similarity search for Postgres",
      nl: "Vector-similarity-search voor Postgres",
    },
  },
  {
    id: "curated-faiss",
    name: "Faiss",
    href: "https://github.com/facebookresearch/faiss",
    category: "rag",
    addedOn: "2017-02-07",
    blurb: {
      en: "Efficient similarity search and clustering of dense vectors",
      nl: "Efficiënte similarity-search en clustering van dichte vectoren",
    },
  },
] as const satisfies readonly AwesomeSeed[];
