import type { AwesomeSeed } from "./awesome-ai-oss";

/**
 * Curated chunk 1/6 (50 live GitHub repos). `addedOn` is the frozen GitHub
 * created date — not a popularity signal. English blurbs are verbatim.
 */
export const AWESOME_AI_OSS_SEEDS_CHUNK_1 = [
  {
    id: "curated-mcp-specification",
    name: "MCP Specification",
    href: "https://github.com/modelcontextprotocol/specification",
    category: "protocols",
    addedOn: "2024-09-24",
    blurb: {
      en: "Official MCP specification and protocol docs",
      nl: "Officiële MCP-specificatie en protocoldocumentatie",
    },
  },
  {
    id: "curated-mcp-inspector",
    name: "MCP Inspector",
    href: "https://github.com/modelcontextprotocol/inspector",
    category: "runtimes",
    addedOn: "2024-10-03",
    blurb: {
      en: "Visual debugger/inspector for MCP servers",
      nl: "Visuele debugger/inspector voor MCP-servers",
    },
  },
  {
    id: "curated-mcp-create-python-server",
    name: "modelcontextprotocol/create-python-server",
    href: "https://github.com/modelcontextprotocol/create-python-server",
    category: "protocols",
    addedOn: "2024-11-18",
    blurb: {
      en: "Cookiecutter to scaffold a Python MCP server",
      nl: "Cookiecutter om een Python-MCP-server te maken",
    },
  },
  {
    id: "curated-mcp-create-typescript-server",
    name: "modelcontextprotocol/create-typescript-server",
    href: "https://github.com/modelcontextprotocol/create-typescript-server",
    category: "protocols",
    addedOn: "2024-11-18",
    blurb: {
      en: "Scaffold for TypeScript MCP servers",
      nl: "Scaffold voor TypeScript-MCP-servers",
    },
  },
  {
    id: "curated-mcp-csharp-sdk",
    name: "modelcontextprotocol/csharp-sdk",
    href: "https://github.com/modelcontextprotocol/csharp-sdk",
    category: "protocols",
    addedOn: "2025-03-10",
    blurb: {
      en: "Official C# SDK for Model Context Protocol",
      nl: "Officiële C#-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-java-sdk",
    name: "modelcontextprotocol/java-sdk",
    href: "https://github.com/modelcontextprotocol/java-sdk",
    category: "protocols",
    addedOn: "2025-01-20",
    blurb: {
      en: "Official Java SDK for Model Context Protocol",
      nl: "Officiële Java-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-kotlin-sdk",
    name: "modelcontextprotocol/kotlin-sdk",
    href: "https://github.com/modelcontextprotocol/kotlin-sdk",
    category: "protocols",
    addedOn: "2024-12-16",
    blurb: {
      en: "Official Kotlin SDK for Model Context Protocol",
      nl: "Officiële Kotlin-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-go-sdk",
    name: "modelcontextprotocol/go-sdk",
    href: "https://github.com/modelcontextprotocol/go-sdk",
    category: "protocols",
    addedOn: "2025-04-23",
    blurb: {
      en: "Official Go SDK for Model Context Protocol",
      nl: "Officiële Go-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-ruby-sdk",
    name: "modelcontextprotocol/ruby-sdk",
    href: "https://github.com/modelcontextprotocol/ruby-sdk",
    category: "protocols",
    addedOn: "2025-02-27",
    blurb: {
      en: "Official Ruby SDK for Model Context Protocol",
      nl: "Officiële Ruby-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-rust-sdk",
    name: "modelcontextprotocol/rust-sdk",
    href: "https://github.com/modelcontextprotocol/rust-sdk",
    category: "protocols",
    addedOn: "2025-02-18",
    blurb: {
      en: "Official Rust SDK for Model Context Protocol",
      nl: "Officiële Rust-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-swift-sdk",
    name: "modelcontextprotocol/swift-sdk",
    href: "https://github.com/modelcontextprotocol/swift-sdk",
    category: "protocols",
    addedOn: "2025-02-05",
    blurb: {
      en: "Official Swift SDK for Model Context Protocol",
      nl: "Officiële Swift-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-php-sdk",
    name: "modelcontextprotocol/php-sdk",
    href: "https://github.com/modelcontextprotocol/php-sdk",
    category: "protocols",
    addedOn: "2025-07-15",
    blurb: {
      en: "Official PHP SDK for Model Context Protocol",
      nl: "Officiële PHP-SDK voor Model Context Protocol",
    },
  },
  {
    id: "curated-mcp-go",
    name: "mcp-go",
    href: "https://github.com/mark3labs/mcp-go",
    category: "protocols",
    addedOn: "2024-11-27",
    blurb: {
      en: "Go SDK and helpers for building MCP servers/clients",
      nl: "Go-SDK en helpers voor MCP-servers/clients",
    },
  },
  {
    id: "curated-punkpeye-fastmcp",
    name: "punkpeye/fastmcp",
    href: "https://github.com/punkpeye/fastmcp",
    category: "runtimes",
    addedOn: "2024-12-27",
    blurb: {
      en: "TypeScript framework for building MCP servers fast",
      nl: "TypeScript-framework om snel MCP-servers te bouwen",
    },
  },
  {
    id: "curated-github-mcp-server",
    name: "GitHub MCP Server",
    href: "https://github.com/github/github-mcp-server",
    category: "runtimes",
    addedOn: "2025-03-04",
    blurb: {
      en: "Official GitHub MCP server for repo and issue tools",
      nl: "Officiële GitHub-MCP-server voor repo- en issue-tools",
    },
  },
  {
    id: "curated-mcp-server-cloudflare",
    name: "cloudflare/mcp-server-cloudflare",
    href: "https://github.com/cloudflare/mcp-server-cloudflare",
    category: "runtimes",
    addedOn: "2024-11-27",
    blurb: {
      en: "Cloudflare MCP servers for Workers and platform APIs",
      nl: "Cloudflare-MCP-servers voor Workers en platform-API’s",
    },
  },
  {
    id: "curated-mcp-server-neon",
    name: "neondatabase/mcp-server-neon",
    href: "https://github.com/neondatabase/mcp-server-neon",
    category: "runtimes",
    addedOn: "2024-11-29",
    blurb: {
      en: "Official Neon Postgres MCP server",
      nl: "Officiële Neon Postgres MCP-server",
    },
  },
  {
    id: "curated-stripe-agent-toolkit",
    name: "stripe/agent-toolkit",
    href: "https://github.com/stripe/agent-toolkit",
    category: "runtimes",
    addedOn: "2024-11-11",
    blurb: {
      en: "Stripe agent toolkit with MCP server support",
      nl: "Stripe agent-toolkit met MCP-serverondersteuning",
    },
  },
  {
    id: "curated-sentry-mcp",
    name: "getsentry/sentry-mcp",
    href: "https://github.com/getsentry/sentry-mcp",
    category: "runtimes",
    addedOn: "2025-03-29",
    blurb: {
      en: "Sentry MCP server for error and issue context",
      nl: "Sentry-MCP-server voor error- en issue-context",
    },
  },
  {
    id: "curated-mcp-server-browserbase",
    name: "browserbase/mcp-server-browserbase",
    href: "https://github.com/browserbase/mcp-server-browserbase",
    category: "runtimes",
    addedOn: "2024-12-05",
    blurb: {
      en: "Browserbase MCP server for cloud browsers",
      nl: "Browserbase-MCP-server voor cloudbrowsers",
    },
  },
  {
    id: "curated-microsoft-mcp",
    name: "microsoft/mcp",
    href: "https://github.com/microsoft/mcp",
    category: "runtimes",
    addedOn: "2025-04-09",
    blurb: {
      en: "Microsoft MCP servers and tooling monorepo",
      nl: "Microsoft MCP-servers en tooling-monorepo",
    },
  },
  {
    id: "curated-anthropic-quickstarts",
    name: "anthropics/anthropic-quickstarts",
    href: "https://github.com/anthropics/anthropic-quickstarts",
    category: "runtimes",
    addedOn: "2024-08-29",
    blurb: {
      en: "Anthropic quickstarts including computer-use patterns",
      nl: "Anthropic-quickstarts inclusief computer-use-patronen",
    },
  },
  {
    id: "curated-langchain-mcp-adapters",
    name: "langchain-ai/langchain-mcp-adapters",
    href: "https://github.com/langchain-ai/langchain-mcp-adapters",
    category: "protocols",
    addedOn: "2025-02-07",
    blurb: {
      en: "Adapters to use MCP tools inside LangChain agents",
      nl: "Adapters om MCP-tools in LangChain-agents te gebruiken",
    },
  },
  {
    id: "curated-mcp-use",
    name: "mcp-use/mcp-use",
    href: "https://github.com/mcp-use/mcp-use",
    category: "runtimes",
    addedOn: "2025-03-28",
    blurb: {
      en: "SDK to connect any LLM to MCP servers and build agents",
      nl: "SDK om een LLM te verbinden met MCP-servers en agents te bouwen",
    },
  },
  {
    id: "curated-mcp-remote",
    name: "geelen/mcp-remote",
    href: "https://github.com/geelen/mcp-remote",
    category: "runtimes",
    addedOn: "2025-03-20",
    blurb: {
      en: "Remote/proxy bridge for MCP over HTTP",
      nl: "Remote/proxy-brug voor MCP over HTTP",
    },
  },
  {
    id: "curated-mcp-proxy",
    name: "sparfenyuk/mcp-proxy",
    href: "https://github.com/sparfenyuk/mcp-proxy",
    category: "runtimes",
    addedOn: "2024-12-26",
    blurb: {
      en: "Proxy that bridges MCP stdio and SSE transports",
      nl: "Proxy die MCP-stdio- en SSE-transports verbindt",
    },
  },
  {
    id: "curated-mcpo",
    name: "mcpo",
    href: "https://github.com/open-webui/mcpo",
    category: "runtimes",
    addedOn: "2025-03-30",
    blurb: {
      en: "Expose MCP tools as OpenAPI/HTTP for any client",
      nl: "MCP-tools als OpenAPI/HTTP voor elke client",
    },
  },
  {
    id: "curated-mcp-cli",
    name: "wong2/mcp-cli",
    href: "https://github.com/wong2/mcp-cli",
    category: "runtimes",
    addedOn: "2024-12-05",
    blurb: {
      en: "CLI client for interacting with MCP servers",
      nl: "CLI-client voor MCP-servers",
    },
  },
  {
    id: "curated-awslabs-mcp",
    name: "awslabs/mcp",
    href: "https://github.com/awslabs/mcp",
    category: "runtimes",
    addedOn: "2025-03-21",
    blurb: {
      en: "AWS Labs MCP servers for AWS services",
      nl: "AWS Labs MCP-servers voor AWS-services",
    },
  },
  {
    id: "curated-mcp-atlassian",
    name: "sooperset/mcp-atlassian",
    href: "https://github.com/sooperset/mcp-atlassian",
    category: "runtimes",
    addedOn: "2024-12-03",
    blurb: {
      en: "MCP server for Jira and Confluence",
      nl: "MCP-server voor Jira en Confluence",
    },
  },
  {
    id: "curated-mcp-gdrive",
    name: "isaacphi/mcp-gdrive",
    href: "https://github.com/isaacphi/mcp-gdrive",
    category: "runtimes",
    addedOn: "2024-12-13",
    blurb: {
      en: "Google Drive MCP server for docs and files",
      nl: "Google Drive MCP-server voor docs en bestanden",
    },
  },
  {
    id: "curated-mcp-server-atlassian-jira",
    name: "aashari/mcp-server-atlassian-jira",
    href: "https://github.com/aashari/mcp-server-atlassian-jira",
    category: "runtimes",
    addedOn: "2025-03-23",
    blurb: {
      en: "Atlassian Jira MCP server",
      nl: "Atlassian Jira MCP-server",
    },
  },
  {
    id: "curated-jetbrains-mcp-proxy",
    name: "JetBrains/mcpProxy",
    href: "https://github.com/JetBrains/mcpProxy",
    category: "runtimes",
    addedOn: "2024-12-09",
    blurb: {
      en: "JetBrains IDE MCP proxy for coding agents",
      nl: "JetBrains IDE MCP-proxy voor coding-agents",
    },
  },
  {
    id: "curated-serena",
    name: "oraios/serena",
    href: "https://github.com/oraios/serena",
    category: "runtimes",
    addedOn: "2025-03-23",
    blurb: {
      en: "Coding-agent toolkit with MCP-based code intelligence",
      nl: "Coding-agent-toolkit met MCP-gebaseerde code-intelligence",
    },
  },
  {
    id: "curated-mcp-playwright",
    name: "executeautomation/mcp-playwright",
    href: "https://github.com/executeautomation/mcp-playwright",
    category: "runtimes",
    addedOn: "2024-12-03",
    blurb: {
      en: "Playwright MCP server for browser automation",
      nl: "Playwright-MCP-server voor browserautomatisering",
    },
  },
  {
    id: "curated-context7",
    name: "Context7",
    href: "https://github.com/upstash/context7",
    category: "runtimes",
    addedOn: "2025-03-26",
    blurb: {
      en: "Context7 MCP server for up-to-date library docs",
      nl: "Context7-MCP-server voor actuele library-docs",
    },
  },
  {
    id: "curated-mcp-server-qdrant",
    name: "qdrant/mcp-server-qdrant",
    href: "https://github.com/qdrant/mcp-server-qdrant",
    category: "runtimes",
    addedOn: "2024-12-02",
    blurb: {
      en: "Official Qdrant MCP server for vector search",
      nl: "Officiële Qdrant-MCP-server voor vector search",
    },
  },
  {
    id: "curated-chroma-mcp",
    name: "chroma-core/chroma-mcp",
    href: "https://github.com/chroma-core/chroma-mcp",
    category: "runtimes",
    addedOn: "2025-02-11",
    blurb: {
      en: "Chroma MCP server for embeddings and collections",
      nl: "Chroma-MCP-server voor embeddings en collections",
    },
  },
  {
    id: "curated-prisma-mcp",
    name: "prisma/mcp",
    href: "https://github.com/prisma/mcp",
    category: "runtimes",
    addedOn: "2025-06-20",
    blurb: {
      en: "Prisma MCP server for database workflows",
      nl: "Prisma-MCP-server voor database-workflows",
    },
  },
  {
    id: "curated-mongodb-mcp-server",
    name: "mongodb-js/mongodb-mcp-server",
    href: "https://github.com/mongodb-js/mongodb-mcp-server",
    category: "runtimes",
    addedOn: "2025-04-04",
    blurb: {
      en: "Official MongoDB MCP server",
      nl: "Officiële MongoDB-MCP-server",
    },
  },
  {
    id: "curated-mcp-redis",
    name: "redis/mcp-redis",
    href: "https://github.com/redis/mcp-redis",
    category: "runtimes",
    addedOn: "2025-04-02",
    blurb: {
      en: "Official Redis MCP server",
      nl: "Officiële Redis-MCP-server",
    },
  },
  {
    id: "curated-mcp-server-elasticsearch",
    name: "elastic/mcp-server-elasticsearch",
    href: "https://github.com/elastic/mcp-server-elasticsearch",
    category: "runtimes",
    addedOn: "2025-03-24",
    blurb: {
      en: "Elasticsearch MCP server",
      nl: "Elasticsearch-MCP-server",
    },
  },
  {
    id: "curated-perplexity-mcp",
    name: "ppl-ai/modelcontextprotocol",
    href: "https://github.com/ppl-ai/modelcontextprotocol",
    category: "runtimes",
    addedOn: "2025-03-10",
    blurb: {
      en: "Perplexity MCP server for web search answers",
      nl: "Perplexity-MCP-server voor websearch-antwoorden",
    },
  },
  {
    id: "curated-exa-mcp-server",
    name: "exa-labs/exa-mcp-server",
    href: "https://github.com/exa-labs/exa-mcp-server",
    category: "runtimes",
    addedOn: "2024-11-27",
    blurb: {
      en: "Exa MCP server for neural web search",
      nl: "Exa-MCP-server voor neurale websearch",
    },
  },
  {
    id: "curated-actors-mcp-server",
    name: "apify/actors-mcp-server",
    href: "https://github.com/apify/actors-mcp-server",
    category: "runtimes",
    addedOn: "2025-01-02",
    blurb: {
      en: "Apify Actors MCP server for web scraping actors",
      nl: "Apify Actors MCP-server voor webscraping-actors",
    },
  },
  {
    id: "curated-firecrawl-mcp-server",
    name: "firecrawl/firecrawl-mcp-server",
    href: "https://github.com/firecrawl/firecrawl-mcp-server",
    category: "runtimes",
    addedOn: "2024-12-06",
    blurb: {
      en: "Firecrawl MCP server for crawl-to-markdown",
      nl: "Firecrawl-MCP-server voor crawl-to-markdown",
    },
  },
  {
    id: "curated-mcp-handler",
    name: "vercel/mcp-handler",
    href: "https://github.com/vercel/mcp-handler",
    category: "protocols",
    addedOn: "2025-05-09",
    blurb: {
      en: "Helpers to host MCP servers on Vercel",
      nl: "Helpers om MCP-servers op Vercel te hosten",
    },
  },
  {
    id: "curated-cloudflare-agents",
    name: "cloudflare/agents",
    href: "https://github.com/cloudflare/agents",
    category: "protocols",
    addedOn: "2025-01-29",
    blurb: {
      en: "Cloudflare Agents SDK with MCP support",
      nl: "Cloudflare Agents SDK met MCP-ondersteuning",
    },
  },
  {
    id: "curated-jsonresume-mcp",
    name: "jsonresume/mcp",
    href: "https://github.com/jsonresume/mcp",
    category: "runtimes",
    addedOn: "2025-03-04",
    blurb: {
      en: "JSON Resume MCP server",
      nl: "JSON Resume MCP-server",
    },
  },
  {
    id: "curated-mcp-containers",
    name: "metorial/mcp-containers",
    href: "https://github.com/metorial/mcp-containers",
    category: "runtimes",
    addedOn: "2025-04-14",
    blurb: {
      en: "Containerized MCP servers collection",
      nl: "Collectie gecontaineriseerde MCP-servers",
    },
  },
] as const satisfies readonly AwesomeSeed[];
