import type { AwesomeSeed } from "./awesome-ai-oss";

/**
 * Chunk 5/6 curated seeds. `addedOn` is the live GitHub `created_at` date
 * (UTC, fetched 2026-09-14) — not a popularity or star signal.
 */
export const AWESOME_AI_OSS_SEEDS_CHUNK_5: readonly AwesomeSeed[] = [
  {
    id: "curated-litgpt",
    name: "LitGPT",
    href: "https://github.com/Lightning-AI/litgpt",
    category: "models",
    addedOn: "2023-05-04",
    blurb: {
      en: "Hackable GPT training and inference with Lightning",
      nl: "Hackbare GPT-training en -inference met Lightning",
    },
  },
  {
    id: "curated-nanogpt",
    name: "nanoGPT",
    href: "https://github.com/karpathy/nanoGPT",
    category: "models",
    addedOn: "2022-12-28",
    blurb: {
      en: "Minimal reproducible GPT training codebase",
      nl: "Minimale reproduceerbare GPT-trainingscodebase",
    },
  },
  {
    id: "curated-minicpm-o",
    name: "MiniCPM-V",
    href: "https://github.com/OpenBMB/MiniCPM-V",
    category: "models",
    addedOn: "2024-01-29",
    blurb: {
      en: "OpenBMB MiniCPM vision-language and omni model family",
      nl: "OpenBMB MiniCPM vision-language- en omni-modelfamilie",
    },
  },
  {
    id: "curated-llama-cpp-python",
    name: "llama-cpp-python",
    href: "https://github.com/abetlen/llama-cpp-python",
    category: "models",
    addedOn: "2023-03-23",
    blurb: {
      en: "Python bindings for llama.cpp",
      nl: "Python-bindings voor llama.cpp",
    },
  },
  {
    id: "curated-llamafile",
    name: "llamafile",
    href: "https://github.com/mozilla-ai/llamafile",
    category: "models",
    addedOn: "2023-09-10",
    blurb: {
      en: "Distribute and run LLMs as a single-file executable",
      nl: "Verspreid en draai LLM’s als één uitvoerbaar bestand",
    },
  },
  {
    id: "curated-localai",
    name: "LocalAI",
    href: "https://github.com/mudler/LocalAI",
    category: "models",
    addedOn: "2023-03-18",
    blurb: {
      en: "Self-hosted OpenAI-compatible local AI REST API",
      nl: "Zelf-gehoste OpenAI-compatibele lokale AI-REST-API",
    },
  },
  {
    id: "curated-text-generation-webui",
    name: "text-generation-webui",
    href: "https://github.com/oobabooga/textgen",
    category: "models",
    addedOn: "2022-12-21",
    blurb: {
      en: "Gradio web UI for running large language models",
      nl: "Gradio-web-UI voor het draaien van grote taalmodellen",
    },
  },
  {
    id: "curated-koboldcpp",
    name: "KoboldCpp",
    href: "https://github.com/LostRuins/koboldcpp",
    category: "models",
    addedOn: "2023-03-16",
    blurb: {
      en: "llama.cpp-based AI inference with Kobold-style API",
      nl: "llama.cpp-gebaseerde AI-inference met Kobold-stijl-API",
    },
  },
  {
    id: "curated-tabbyapi",
    name: "tabbyAPI",
    href: "https://github.com/theroyallab/tabbyAPI",
    category: "models",
    addedOn: "2023-11-10",
    blurb: {
      en: "OpenAI-compatible API server for local Exllama models",
      nl: "OpenAI-compatibele API-server voor lokale Exllama-modellen",
    },
  },
  {
    id: "curated-exllamav2",
    name: "ExLlamaV2",
    href: "https://github.com/turboderp-org/exllamav2",
    category: "models",
    addedOn: "2023-08-30",
    blurb: {
      en: "Fast inference library for local LLMs on consumer GPUs",
      nl: "Snelle inference-library voor lokale LLM’s op consumenten-GPU’s",
    },
  },
  {
    id: "curated-lm-evaluation-harness",
    name: "lm-evaluation-harness",
    href: "https://github.com/EleutherAI/lm-evaluation-harness",
    category: "eval-observability",
    addedOn: "2020-08-28",
    blurb: {
      en: "Standardized few-shot evaluation harness for language models",
      nl: "Gestandaardiseerde few-shot-evaluatieharness voor taalmodellen",
    },
  },
  {
    id: "curated-opencompass",
    name: "OpenCompass",
    href: "https://github.com/open-compass/opencompass",
    category: "eval-observability",
    addedOn: "2023-06-15",
    blurb: {
      en: "LLM evaluation platform with many benchmarks",
      nl: "LLM-evaluatieplatform met veel benchmarks",
    },
  },
  {
    id: "curated-helm",
    name: "HELM",
    href: "https://github.com/stanford-crfm/helm",
    category: "eval-observability",
    addedOn: "2021-11-29",
    blurb: {
      en: "Holistic Evaluation of Language Models from Stanford CRFM",
      nl: "Holistische evaluatie van taalmodellen van Stanford CRFM",
    },
  },
  {
    id: "curated-inspect-ai",
    name: "Inspect AI",
    href: "https://github.com/UKGovernmentBEIS/inspect_ai",
    category: "eval-observability",
    addedOn: "2023-11-14",
    blurb: {
      en: "Framework for large language model evaluations",
      nl: "Framework voor evaluaties van grote taalmodellen",
    },
  },
  {
    id: "curated-openai-evals",
    name: "OpenAI Evals",
    href: "https://github.com/openai/evals",
    category: "eval-observability",
    addedOn: "2023-01-23",
    blurb: {
      en: "Framework for evaluating LLMs and systems built with them",
      nl: "Framework voor het evalueren van LLM’s en systemen die ermee zijn gebouwd",
    },
  },
  {
    id: "curated-olmo",
    name: "OLMo",
    href: "https://github.com/allenai/OLMo",
    category: "models",
    addedOn: "2023-02-20",
    blurb: {
      en: "Open language model and training stack from AI2",
      nl: "Open taalmodel en trainingsstack van AI2",
    },
  },
  {
    id: "curated-dolma",
    name: "DOLMA",
    href: "https://github.com/allenai/dolma",
    category: "models",
    addedOn: "2023-06-20",
    blurb: {
      en: "Open dataset of 3T tokens for language model pretraining",
      nl: "Open dataset van 3T tokens voor taalmodel-pretraining",
    },
  },
  {
    id: "curated-llama",
    name: "Llama",
    href: "https://github.com/meta-llama/llama",
    category: "models",
    addedOn: "2023-02-14",
    blurb: {
      en: "Meta Llama model weights and inference code (check access)",
      nl: "Meta Llama-modelgewichten en inference-code (controleer toegang)",
    },
  },
  {
    id: "curated-gemma",
    name: "Gemma",
    href: "https://github.com/google-deepmind/gemma",
    category: "models",
    addedOn: "2024-02-20",
    blurb: {
      en: "Gemma open models from Google DeepMind",
      nl: "Gemma open modellen van Google DeepMind",
    },
  },
  {
    id: "curated-mistral-inference",
    name: "mistral-inference",
    href: "https://github.com/mistralai/mistral-inference",
    category: "models",
    addedOn: "2023-09-27",
    blurb: {
      en: "Reference inference for Mistral open models",
      nl: "Referentie-inference voor Mistral open modellen",
    },
  },
  {
    id: "curated-mistral-common",
    name: "mistral-common",
    href: "https://github.com/mistralai/mistral-common",
    category: "models",
    addedOn: "2024-04-15",
    blurb: {
      en: "Shared tokenization and tools for Mistral models",
      nl: "Gedeelde tokenisatie en tools voor Mistral-modellen",
    },
  },
  {
    id: "curated-qwen25",
    name: "Qwen3",
    href: "https://github.com/QwenLM/Qwen3",
    category: "models",
    addedOn: "2024-02-05",
    blurb: {
      en: "Qwen3 open LLM family from Alibaba",
      nl: "Qwen3 open LLM-familie van Alibaba",
    },
  },
  {
    id: "curated-qwen",
    name: "Qwen",
    href: "https://github.com/QwenLM/Qwen",
    category: "models",
    addedOn: "2023-08-03",
    blurb: {
      en: "Qwen large language model series",
      nl: "Qwen grote-taalmodelserie",
    },
  },
  {
    id: "curated-chatglm3",
    name: "ChatGLM3",
    href: "https://github.com/zai-org/ChatGLM3",
    category: "models",
    addedOn: "2023-10-26",
    blurb: {
      en: "Open bilingual chat model series from THUDM",
      nl: "Open tweetalige chatmodelserie van THUDM",
    },
  },
  {
    id: "curated-internlm",
    name: "InternLM",
    href: "https://github.com/InternLM/InternLM",
    category: "models",
    addedOn: "2023-07-06",
    blurb: {
      en: "InternLM open bilingual foundation models",
      nl: "InternLM open tweetalige foundation-modellen",
    },
  },
  {
    id: "curated-yi",
    name: "Yi",
    href: "https://github.com/01-ai/Yi",
    category: "models",
    addedOn: "2023-11-03",
    blurb: {
      en: "Yi open bilingual large language models",
      nl: "Yi open tweetalige grote taalmodellen",
    },
  },
  {
    id: "curated-llm-foundry",
    name: "LLM Foundry",
    href: "https://github.com/mosaicml/llm-foundry",
    category: "models",
    addedOn: "2023-04-28",
    blurb: {
      en: "Training and fine-tuning code for LLMs with Composer",
      nl: "Trainings- en fine-tuningcode voor LLM’s met Composer",
    },
  },
  {
    id: "curated-dolly",
    name: "Dolly",
    href: "https://github.com/databrickslabs/dolly",
    category: "models",
    addedOn: "2023-03-24",
    blurb: {
      en: "Databricks instruction-following LLM and dataset",
      nl: "Databricks instruction-following LLM en dataset",
    },
  },
  {
    id: "curated-fastchat",
    name: "FastChat",
    href: "https://github.com/lm-sys/FastChat",
    category: "models",
    addedOn: "2023-03-19",
    blurb: {
      en: "Training serving and evaluation platform for chatbots",
      nl: "Trainings-, serving- en evaluatieplatform voor chatbots",
    },
  },
  {
    id: "curated-web-llm",
    name: "WebLLM",
    href: "https://github.com/mlc-ai/web-llm",
    category: "models",
    addedOn: "2023-04-13",
    blurb: {
      en: "In-browser LLM inference via WebGPU",
      nl: "In-browser LLM-inference via WebGPU",
    },
  },
  {
    id: "curated-mlx",
    name: "MLX",
    href: "https://github.com/ml-explore/mlx",
    category: "models",
    addedOn: "2023-11-28",
    blurb: {
      en: "Array framework for machine learning on Apple silicon",
      nl: "Array-framework voor machine learning op Apple silicon",
    },
  },
  {
    id: "curated-mlx-examples",
    name: "MLX Examples",
    href: "https://github.com/ml-explore/mlx-examples",
    category: "models",
    addedOn: "2023-11-28",
    blurb: {
      en: "Example models and apps built with MLX",
      nl: "Voorbeeldmodellen en apps gebouwd met MLX",
    },
  },
  {
    id: "curated-candle",
    name: "Candle",
    href: "https://github.com/huggingface/candle",
    category: "models",
    addedOn: "2023-06-19",
    blurb: {
      en: "Minimalist ML framework for Rust",
      nl: "Minimalistisch ML-framework voor Rust",
    },
  },
  {
    id: "curated-torchtune",
    name: "torchtune",
    href: "https://github.com/meta-pytorch/torchtune",
    category: "models",
    addedOn: "2023-10-20",
    blurb: {
      en: "PyTorch-native library for LLM fine-tuning",
      nl: "PyTorch-native library voor LLM-fine-tuning",
    },
  },
  {
    id: "curated-torchtitan",
    name: "TorchTitan",
    href: "https://github.com/pytorch/torchtitan",
    category: "models",
    addedOn: "2023-12-13",
    blurb: {
      en: "PyTorch native large-scale LLM training framework",
      nl: "PyTorch-native grootschalig LLM-trainingsframework",
    },
  },
  {
    id: "curated-nemo",
    name: "NeMo",
    href: "https://github.com/NVIDIA-NeMo/Speech",
    category: "models",
    addedOn: "2019-08-05",
    blurb: {
      en: "NVIDIA toolkit for conversational AI and LLM training",
      nl: "NVIDIA-toolkit voor conversationele AI en LLM-training",
    },
  },
  {
    id: "curated-openvino",
    name: "OpenVINO",
    href: "https://github.com/openvinotoolkit/openvino",
    category: "models",
    addedOn: "2018-10-15",
    blurb: {
      en: "Toolkit for optimizing and deploying AI inference",
      nl: "Toolkit voor het optimaliseren en deployen van AI-inference",
    },
  },
  {
    id: "curated-intel-extension-for-transformers",
    name: "Intel Extension for Transformers",
    href: "https://github.com/intel/intel-extension-for-transformers",
    category: "models",
    addedOn: "2022-11-11",
    blurb: {
      en: "Optimized Transformers inference and fine-tuning on Intel",
      nl: "Geoptimaliseerde Transformers-inference en fine-tuning op Intel",
    },
  },
  {
    id: "curated-starcoder2",
    name: "StarCoder2",
    href: "https://github.com/bigcode-project/starcoder2",
    category: "models",
    addedOn: "2023-12-08",
    blurb: {
      en: "Open code LLM family from BigCode",
      nl: "Open code-LLM-familie van BigCode",
    },
  },
  {
    id: "curated-codegen",
    name: "CodeGen",
    href: "https://github.com/salesforce/CodeGen",
    category: "models",
    addedOn: "2022-03-28",
    blurb: {
      en: "Open code generation models from Salesforce",
      nl: "Open codegeneratiemodellen van Salesforce",
    },
  },
  {
    id: "curated-stablelm",
    name: "StableLM",
    href: "https://github.com/Stability-AI/StableLM",
    category: "models",
    addedOn: "2023-04-19",
    blurb: {
      en: "Stability AI language model family",
      nl: "Stability AI-taalmodelfamilie",
    },
  },
  {
    id: "curated-redpajama-data",
    name: "RedPajama-Data",
    href: "https://github.com/togethercomputer/RedPajama-Data",
    category: "models",
    addedOn: "2023-04-14",
    blurb: {
      en: "Open dataset reproducing LLaMA training data recipe",
      nl: "Open dataset die het LLaMA-trainingsdatarecept reproduceert",
    },
  },
  {
    id: "curated-internvl",
    name: "InternVL",
    href: "https://github.com/OpenGVLab/InternVL",
    category: "models",
    addedOn: "2023-11-22",
    blurb: {
      en: "Open multimodal vision-language models",
      nl: "Open multimodale vision-language-modellen",
    },
  },
  {
    id: "curated-llava",
    name: "LLaVA",
    href: "https://github.com/haotian-liu/LLaVA",
    category: "models",
    addedOn: "2023-04-17",
    blurb: {
      en: "Large Language and Vision Assistant multimodal models",
      nl: "Large Language and Vision Assistant multimodale modellen",
    },
  },
  {
    id: "curated-whisper",
    name: "Whisper",
    href: "https://github.com/openai/whisper",
    category: "models",
    addedOn: "2022-09-16",
    blurb: {
      en: "Robust speech recognition models from OpenAI",
      nl: "Robuuste spraakherkenningsmodellen van OpenAI",
    },
  },
  {
    id: "curated-coqui-tts",
    name: "Coqui TTS",
    href: "https://github.com/coqui-ai/TTS",
    category: "models",
    addedOn: "2020-05-20",
    blurb: {
      en: "Deep learning toolkit for Text-to-Speech",
      nl: "Deep-learning-toolkit voor Text-to-Speech",
    },
  },
  {
    id: "curated-rvc",
    name: "RVC",
    href: "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    category: "models",
    addedOn: "2023-03-27",
    blurb: {
      en: "Voice conversion toolkit with a WebUI",
      nl: "Voice-conversion-toolkit met een WebUI",
    },
  },
  {
    id: "curated-stable-diffusion-webui",
    name: "Stable Diffusion WebUI",
    href: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    category: "models",
    addedOn: "2022-08-22",
    blurb: {
      en: "Popular WebUI for Stable Diffusion image generation",
      nl: "Populaire WebUI voor Stable Diffusion-beeldgeneratie",
    },
  },
  {
    id: "curated-comfyui",
    name: "ComfyUI",
    href: "https://github.com/Comfy-Org/ComfyUI",
    category: "models",
    addedOn: "2023-01-17",
    blurb: {
      en: "Node-based UI for diffusion and generative workflows",
      nl: "Node-gebaseerde UI voor diffusion- en generatieve workflows",
    },
  },
  {
    id: "curated-invokeai",
    name: "InvokeAI",
    href: "https://github.com/invoke-ai/InvokeAI",
    category: "models",
    addedOn: "2022-08-17",
    blurb: {
      en: "Creative engine for Stable Diffusion workflows",
      nl: "Creatieve engine voor Stable Diffusion-workflows",
    },
  },
];
