/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    speakers: Speaker;
    articles: Article;
    'forum-threads': ForumThread;
    'forum-replies': ForumReply;
    'community-ideas': CommunityIdea;
    'idea-votes': IdeaVote;
    'launchpad-projects': LaunchpadProject;
    comments: Comment;
    challenges: Challenge;
    pages: Page;
    media: Media;
    sponsors: Sponsor;
    'sponsor-applications': SponsorApplication;
    jobs: Job;
    'rules-acceptance': RulesAcceptance;
    'community-rules': CommunityRule;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'forum-threads': ForumThreadsSelect<false> | ForumThreadsSelect<true>;
    'forum-replies': ForumRepliesSelect<false> | ForumRepliesSelect<true>;
    'community-ideas': CommunityIdeasSelect<false> | CommunityIdeasSelect<true>;
    'idea-votes': IdeaVotesSelect<false> | IdeaVotesSelect<true>;
    'launchpad-projects': LaunchpadProjectsSelect<false> | LaunchpadProjectsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'sponsor-applications': SponsorApplicationsSelect<false> | SponsorApplicationsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'rules-acceptance': RulesAcceptanceSelect<false> | RulesAcceptanceSelect<true>;
    'community-rules': CommunityRulesSelect<false> | CommunityRulesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'nl';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'workshop' | 'hackathon' | 'deep_dive' | 'meetup';
  date: string;
  startTime?: string | null;
  endTime?: string | null;
  location: string;
  maxAttendees?: number | null;
  /**
   * Price in EUR cents (e.g. 1500 = €15.00). Leave empty for free events.
   */
  price?: number | null;
  image?: (number | null) | Media;
  speakers?: (number | Speaker)[] | null;
  status: 'draft' | 'published' | 'cancelled' | 'completed';
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  bio?: string | null;
  company?: string | null;
  photo?: (number | null) | Media;
  linkedinUrl?: string | null;
  githubUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'article' | 'tutorial' | 'talk_recording';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  mediaUrl?: string | null;
  authorId?: string | null;
  authorName?: string | null;
  authorType?: ('admin' | 'member') | null;
  reviewStatus?: ('pending_review' | 'approved' | 'rejected' | 'changes_requested') | null;
  reviewNote?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Community discussion threads. Pin important threads, lock spam, delete abuse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-threads".
 */
export interface ForumThread {
  id: number;
  title: string;
  /**
   * Auto-generated from title + timestamp. Do not edit manually.
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'question' | 'showcase' | 'job';
  /**
   * Better Auth user ID (UUID).
   */
  authorId: string;
  authorName?: string | null;
  authorRole?: ('admin' | 'moderator' | 'contributor' | 'member') | null;
  /**
   * Pinned threads appear at the top.
   */
  isPinned?: boolean | null;
  /**
   * Locked threads cannot receive new replies.
   */
  isLocked?: boolean | null;
  viewCount?: number | null;
  replyCount?: number | null;
  lastActivityAt?: string | null;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Replies to forum threads. Delete spam or abusive replies here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-replies".
 */
export interface ForumReply {
  id: number;
  thread: number | ForumThread;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Better Auth user ID (UUID).
   */
  authorId: string;
  authorName?: string | null;
  authorType?: ('member' | 'agent') | null;
  authorRole?: ('admin' | 'moderator' | 'contributor' | 'member') | null;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community feature requests and proposals. Change status as ideas are implemented or declined.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-ideas".
 */
export interface CommunityIdea {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Better Auth user ID (UUID).
   */
  authorId: string;
  authorName?: string | null;
  status: 'open' | 'implemented' | 'rejected';
  voteCount?: number | null;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks which users have voted for which ideas. One vote per user per idea (enforced by hook).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idea-votes".
 */
export interface IdeaVote {
  id: number;
  idea: number | CommunityIdea;
  /**
   * Better Auth user ID (UUID).
   */
  voterId: string;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entrepreneur projects shared on Launchpad for community feedback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "launchpad-projects".
 */
export interface LaunchpadProject {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title on creation.
   */
  slug: string;
  pitch: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  stage: 'idea' | 'prototype' | 'mvp' | 'launched';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  /**
   * Better Auth user ID (UUID).
   */
  authorId: string;
  authorName?: string | null;
  status: 'draft' | 'published' | 'archived';
  voteCount?: number | null;
  commentCount?: number | null;
  updateCount?: number | null;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  articleId: number;
  parentId?: number | null;
  content: string;
  authorId: string;
  authorName?: string | null;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Unified challenges: platform-action, repo-based, or mixed. Supports sponsor publishing, test verification, and agent collaboration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: number;
  title: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'weekly' | 'monthly' | 'open-ended';
  status: 'draft' | 'active' | 'completed' | 'archived';
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  /**
   * Optional for open-ended challenges.
   */
  startsAt?: string | null;
  /**
   * Optional for open-ended challenges.
   */
  endsAt?: string | null;
  publishedBy: 'member' | 'sponsor';
  /**
   * Whether this challenge was generated by AI or created by a human.
   */
  generatedBy?: ('human' | 'ai') | null;
  /**
   * User ID or Sponsor ID of the challenge creator.
   */
  creatorId: string;
  /**
   * GitHub repo configuration for repo-based challenges.
   */
  repo?: {
    /**
     * GitHub template repo URL (e.g., https://github.com/org/repo).
     */
    templateUrl?: string | null;
    /**
     * Whether .aitchallenge.yml is expected in participant repos.
     */
    configFile?: boolean | null;
    /**
     * Shell command to run tests (e.g., "npm test", "pytest").
     */
    testCommand?: string | null;
    /**
     * Google Colab notebook URL for cloud-based development.
     */
    colabUrl?: string | null;
  };
  objectives: {
    description: string;
    verification: 'platform-action' | 'test' | 'self-report' | 'peer-review';
    /**
     * Only for platform-action verification.
     */
    action?: ('thread.reply' | 'thread.create' | 'knowledge.share' | 'idea.submitted' | 'idea.voted') | null;
    /**
     * Regex matching test names/files for test verification.
     */
    testPattern?: string | null;
    /**
     * How many times this must be completed. For tests, usually 1.
     */
    targetCount: number;
    /**
     * Optional scope filter for platform-action, e.g. { "category": "question" }.
     */
    filter?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  rewards: {
    /**
     * XP awarded on completion.
     */
    xpReward: number;
    /**
     * Badge slug to award on completion (optional).
     */
    badgeReward?: string | null;
    /**
     * Sponsor-provided reward description (prizes, interviews, licenses).
     */
    sponsorReward?: string | null;
  };
  /**
   * 0 = unlimited.
   */
  maxParticipants?: number | null;
  /**
   * Array of tags for discovery, e.g. ["mcp", "typescript", "automation"].
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * For AI-generated challenges: what triggered this challenge.
   */
  signalSource?: {
    type?: ('community-thread' | 'member-request' | 'external' | 'insight-gap') | null;
    /**
     * Thread ID, URL, or description of the signal source.
     */
    reference?: string | null;
    /**
     * AI summary of why this challenge was generated.
     */
    summary?: string | null;
  };
  /**
   * How the leaderboard is sorted.
   */
  rankingMode?: ('speed' | 'thoroughness' | 'collaboration') | null;
  /**
   * How humans and AIs collaborate in this challenge.
   */
  collaborationModel?: ('solo-ai' | 'relay' | 'swarm' | 'adversarial' | 'blind' | 'escalation') | null;
  /**
   * User ID if community-proposed.
   */
  proposedBy?: string | null;
  image?: (number | null) | Media;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  slug: string;
  logo: number | Media;
  website?: string | null;
  tier: 'gold' | 'silver' | 'bronze';
  tagline?: string | null;
  /**
   * Show on homepage sponsor strip
   */
  featured?: boolean | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-applications".
 */
export interface SponsorApplication {
  id: number;
  companyName: string;
  website?: string | null;
  contactName: string;
  contactEmail: string;
  tier: 'gold' | 'silver' | 'bronze';
  message?: string | null;
  status: 'pending' | 'in_review' | 'approved' | 'rejected';
  /**
   * Internal notes (not visible to applicant)
   */
  notes?: string | null;
  appliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  sponsor: number | Sponsor;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  location: string;
  type: 'remote' | 'hybrid' | 'onsite';
  /**
   * External apply link
   */
  url: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'expired';
  postedAt?: string | null;
  expiresAt?: string | null;
  communityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks which users have accepted which version of the community rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules-acceptance".
 */
export interface RulesAcceptance {
  id: number;
  /**
   * Better Auth user ID (UUID).
   */
  userId: string;
  rulesVersion: number;
  /**
   * Drizzle community UUID.
   */
  communityId: string;
  acceptedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-community rules / code of conduct.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-rules".
 */
export interface CommunityRule {
  id: number;
  /**
   * Drizzle community UUID.
   */
  communityId: string;
  /**
   * Increment when rules change to require re-acceptance from users.
   */
  version: number;
  /**
   * When this version of the rules takes effect.
   */
  effectiveDate: string;
  /**
   * Structured rule sections with table-of-contents support.
   */
  sections: {
    title: string;
    /**
     * URL-friendly identifier for anchor links (e.g. 'respect-others').
     */
    slug: string;
    icon?: ('shield' | 'users' | 'flag' | 'scale' | 'brain' | 'gavel') | null;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'forum-threads';
        value: number | ForumThread;
      } | null)
    | ({
        relationTo: 'forum-replies';
        value: number | ForumReply;
      } | null)
    | ({
        relationTo: 'community-ideas';
        value: number | CommunityIdea;
      } | null)
    | ({
        relationTo: 'idea-votes';
        value: number | IdeaVote;
      } | null)
    | ({
        relationTo: 'launchpad-projects';
        value: number | LaunchpadProject;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'challenges';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'sponsor-applications';
        value: number | SponsorApplication;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'rules-acceptance';
        value: number | RulesAcceptance;
      } | null)
    | ({
        relationTo: 'community-rules';
        value: number | CommunityRule;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  maxAttendees?: T;
  price?: T;
  image?: T;
  speakers?: T;
  status?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  company?: T;
  photo?: T;
  linkedinUrl?: T;
  githubUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  type?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  mediaUrl?: T;
  authorId?: T;
  authorName?: T;
  authorType?: T;
  reviewStatus?: T;
  reviewNote?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-threads_select".
 */
export interface ForumThreadsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  category?: T;
  authorId?: T;
  authorName?: T;
  authorRole?: T;
  isPinned?: T;
  isLocked?: T;
  viewCount?: T;
  replyCount?: T;
  lastActivityAt?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-replies_select".
 */
export interface ForumRepliesSelect<T extends boolean = true> {
  thread?: T;
  content?: T;
  authorId?: T;
  authorName?: T;
  authorType?: T;
  authorRole?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-ideas_select".
 */
export interface CommunityIdeasSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  authorId?: T;
  authorName?: T;
  status?: T;
  voteCount?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idea-votes_select".
 */
export interface IdeaVotesSelect<T extends boolean = true> {
  idea?: T;
  voterId?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "launchpad-projects_select".
 */
export interface LaunchpadProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pitch?: T;
  stage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  coverImage?: T;
  authorId?: T;
  authorName?: T;
  status?: T;
  voteCount?: T;
  commentCount?: T;
  updateCount?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  articleId?: T;
  parentId?: T;
  content?: T;
  authorId?: T;
  authorName?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  status?: T;
  difficulty?: T;
  startsAt?: T;
  endsAt?: T;
  publishedBy?: T;
  generatedBy?: T;
  creatorId?: T;
  repo?:
    | T
    | {
        templateUrl?: T;
        configFile?: T;
        testCommand?: T;
        colabUrl?: T;
      };
  objectives?:
    | T
    | {
        description?: T;
        verification?: T;
        action?: T;
        testPattern?: T;
        targetCount?: T;
        filter?: T;
        id?: T;
      };
  rewards?:
    | T
    | {
        xpReward?: T;
        badgeReward?: T;
        sponsorReward?: T;
      };
  maxParticipants?: T;
  tags?: T;
  signalSource?:
    | T
    | {
        type?: T;
        reference?: T;
        summary?: T;
      };
  rankingMode?: T;
  collaborationModel?: T;
  proposedBy?: T;
  image?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  tier?: T;
  tagline?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-applications_select".
 */
export interface SponsorApplicationsSelect<T extends boolean = true> {
  companyName?: T;
  website?: T;
  contactName?: T;
  contactEmail?: T;
  tier?: T;
  message?: T;
  status?: T;
  notes?: T;
  appliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  sponsor?: T;
  description?: T;
  location?: T;
  type?: T;
  url?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  postedAt?: T;
  expiresAt?: T;
  communityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules-acceptance_select".
 */
export interface RulesAcceptanceSelect<T extends boolean = true> {
  userId?: T;
  rulesVersion?: T;
  communityId?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-rules_select".
 */
export interface CommunityRulesSelect<T extends boolean = true> {
  communityId?: T;
  version?: T;
  effectiveDate?: T;
  sections?:
    | T
    | {
        title?: T;
        slug?: T;
        icon?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}