/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  timestamp,
  numeric,
  integer,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["en", "nl"]);
export const enum_events_type = pgEnum("enum_events_type", [
  "workshop",
  "hackathon",
  "deep_dive",
  "meetup",
]);
export const enum_events_status = pgEnum("enum_events_status", [
  "draft",
  "published",
  "cancelled",
  "completed",
]);
export const enum__events_v_version_type = pgEnum(
  "enum__events_v_version_type",
  ["workshop", "hackathon", "deep_dive", "meetup"],
);
export const enum__events_v_version_status = pgEnum(
  "enum__events_v_version_status",
  ["draft", "published", "cancelled", "completed"],
);
export const enum__events_v_published_locale = pgEnum(
  "enum__events_v_published_locale",
  ["en", "nl"],
);
export const enum_articles_type = pgEnum("enum_articles_type", [
  "article",
  "tutorial",
  "talk_recording",
]);
export const enum_articles_author_type = pgEnum("enum_articles_author_type", [
  "admin",
  "member",
]);
export const enum_articles_review_status = pgEnum(
  "enum_articles_review_status",
  ["pending_review", "approved", "rejected", "changes_requested"],
);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "published",
]);
export const enum__articles_v_version_type = pgEnum(
  "enum__articles_v_version_type",
  ["article", "tutorial", "talk_recording"],
);
export const enum__articles_v_version_author_type = pgEnum(
  "enum__articles_v_version_author_type",
  ["admin", "member"],
);
export const enum__articles_v_version_review_status = pgEnum(
  "enum__articles_v_version_review_status",
  ["pending_review", "approved", "rejected", "changes_requested"],
);
export const enum__articles_v_version_status = pgEnum(
  "enum__articles_v_version_status",
  ["draft", "published"],
);
export const enum__articles_v_published_locale = pgEnum(
  "enum__articles_v_published_locale",
  ["en", "nl"],
);
export const enum_forum_threads_category = pgEnum(
  "enum_forum_threads_category",
  ["general", "question", "showcase", "job"],
);
export const enum_forum_threads_author_role = pgEnum(
  "enum_forum_threads_author_role",
  ["admin", "moderator", "contributor", "member"],
);
export const enum_forum_replies_author_role = pgEnum(
  "enum_forum_replies_author_role",
  ["admin", "moderator", "contributor", "member"],
);
export const enum_community_ideas_status = pgEnum(
  "enum_community_ideas_status",
  ["open", "implemented", "rejected"],
);
export const enum_challenges_objectives_verification = pgEnum(
  "enum_challenges_objectives_verification",
  ["platform-action", "test", "self-report", "peer-review"],
);
export const enum_challenges_objectives_action = pgEnum(
  "enum_challenges_objectives_action",
  [
    "thread.reply",
    "thread.create",
    "knowledge.share",
    "idea.submitted",
    "idea.voted",
  ],
);
export const enum_challenges_type = pgEnum("enum_challenges_type", [
  "weekly",
  "monthly",
  "open-ended",
]);
export const enum_challenges_status = pgEnum("enum_challenges_status", [
  "draft",
  "active",
  "completed",
  "archived",
]);
export const enum_challenges_difficulty = pgEnum("enum_challenges_difficulty", [
  "beginner",
  "intermediate",
  "advanced",
  "expert",
]);
export const enum_challenges_published_by = pgEnum(
  "enum_challenges_published_by",
  ["member", "sponsor"],
);
export const enum_challenges_generated_by = pgEnum(
  "enum_challenges_generated_by",
  ["human", "ai"],
);
export const enum_challenges_signal_source_type = pgEnum(
  "enum_challenges_signal_source_type",
  ["community-thread", "member-request", "external", "insight-gap"],
);
export const enum_challenges_ranking_mode = pgEnum(
  "enum_challenges_ranking_mode",
  ["speed", "thoroughness", "collaboration"],
);
export const enum_challenges_collaboration_model = pgEnum(
  "enum_challenges_collaboration_model",
  ["solo-ai", "relay", "swarm", "adversarial", "blind", "escalation"],
);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum__pages_v_published_locale = pgEnum(
  "enum__pages_v_published_locale",
  ["en", "nl"],
);
export const enum_sponsors_tier = pgEnum("enum_sponsors_tier", [
  "gold",
  "silver",
  "bronze",
]);
export const enum_sponsors_status = pgEnum("enum_sponsors_status", [
  "active",
  "inactive",
]);
export const enum_sponsor_applications_tier = pgEnum(
  "enum_sponsor_applications_tier",
  ["gold", "silver", "bronze"],
);
export const enum_sponsor_applications_status = pgEnum(
  "enum_sponsor_applications_status",
  ["pending", "in_review", "approved", "rejected"],
);
export const enum_jobs_type = pgEnum("enum_jobs_type", [
  "remote",
  "hybrid",
  "onsite",
]);
export const enum_jobs_status = pgEnum("enum_jobs_status", [
  "active",
  "expired",
]);
export const enum_users_role = pgEnum("enum_users_role", ["admin", "editor"]);
export const enum_community_rules_sections_icon = pgEnum(
  "enum_community_rules_sections_icon",
  ["shield", "users", "flag", "scale", "brain", "gavel"],
);

export const events = pgTable(
  "events",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    type: enum_events_type("type"),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    startTime: varchar("start_time"),
    endTime: varchar("end_time"),
    location: varchar("location"),
    maxAttendees: numeric("max_attendees", { mode: "number" }),
    price: numeric("price", { mode: "number" }),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    status: enum_events_status("status").default("draft"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_events_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("events_slug_idx").on(columns.slug),
    index("events_image_idx").on(columns.image),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
    index("events__status_idx").on(columns._status),
  ],
);

export const events_locales = pgTable(
  "events_locales",
  {
    title: varchar("title"),
    description: jsonb("description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("events_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events_rels = pgTable(
  "events_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    speakersID: integer("speakers_id"),
  },
  (columns) => [
    index("events_rels_order_idx").on(columns.order),
    index("events_rels_parent_idx").on(columns.parent),
    index("events_rels_path_idx").on(columns.path),
    index("events_rels_speakers_id_idx").on(columns.speakersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [events.id],
      name: "events_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["speakersID"]],
      foreignColumns: [speakers.id],
      name: "events_rels_speakers_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v = pgTable(
  "_events_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => events.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_type: enum__events_v_version_type("version_type"),
    version_date: timestamp("version_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_startTime: varchar("version_start_time"),
    version_endTime: varchar("version_end_time"),
    version_location: varchar("version_location"),
    version_maxAttendees: numeric("version_max_attendees", { mode: "number" }),
    version_price: numeric("version_price", { mode: "number" }),
    version_image: integer("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_status:
      enum__events_v_version_status("version_status").default("draft"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__events_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__events_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_events_v_parent_idx").on(columns.parent),
    index("_events_v_version_version_slug_idx").on(columns.version_slug),
    index("_events_v_version_version_image_idx").on(columns.version_image),
    index("_events_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_events_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_events_v_version_version__status_idx").on(columns.version__status),
    index("_events_v_created_at_idx").on(columns.createdAt),
    index("_events_v_updated_at_idx").on(columns.updatedAt),
    index("_events_v_snapshot_idx").on(columns.snapshot),
    index("_events_v_published_locale_idx").on(columns.publishedLocale),
    index("_events_v_latest_idx").on(columns.latest),
  ],
);

export const _events_v_locales = pgTable(
  "_events_v_locales",
  {
    version_title: varchar("version_title"),
    version_description: jsonb("version_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_events_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v_rels = pgTable(
  "_events_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    speakersID: integer("speakers_id"),
  },
  (columns) => [
    index("_events_v_rels_order_idx").on(columns.order),
    index("_events_v_rels_parent_idx").on(columns.parent),
    index("_events_v_rels_path_idx").on(columns.path),
    index("_events_v_rels_speakers_id_idx").on(columns.speakersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["speakersID"]],
      foreignColumns: [speakers.id],
      name: "_events_v_rels_speakers_fk",
    }).onDelete("cascade"),
  ],
);

export const speakers = pgTable(
  "speakers",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    company: varchar("company"),
    photo: integer("photo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    linkedinUrl: varchar("linkedin_url"),
    githubUrl: varchar("github_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("speakers_photo_idx").on(columns.photo),
    index("speakers_updated_at_idx").on(columns.updatedAt),
    index("speakers_created_at_idx").on(columns.createdAt),
  ],
);

export const speakers_locales = pgTable(
  "speakers_locales",
  {
    bio: varchar("bio"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("speakers_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [speakers.id],
      name: "speakers_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const articles_tags = pgTable(
  "articles_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag"),
  },
  (columns) => [
    index("articles_tags_order_idx").on(columns._order),
    index("articles_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    type: enum_articles_type("type"),
    mediaUrl: varchar("media_url"),
    authorId: varchar("author_id"),
    authorName: varchar("author_name"),
    authorType: enum_articles_author_type("author_type").default("admin"),
    reviewStatus: enum_articles_review_status("review_status"),
    reviewNote: varchar("review_note"),
    status: enum_articles_status("status").default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_articles_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
    index("articles__status_idx").on(columns._status),
  ],
);

export const articles_locales = pgTable(
  "articles_locales",
  {
    title: varchar("title"),
    content: jsonb("content"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("articles_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _articles_v_version_tags = pgTable(
  "_articles_v_version_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    tag: varchar("tag"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_articles_v_version_tags_order_idx").on(columns._order),
    index("_articles_v_version_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_articles_v.id],
      name: "_articles_v_version_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _articles_v = pgTable(
  "_articles_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => articles.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_type: enum__articles_v_version_type("version_type"),
    version_mediaUrl: varchar("version_media_url"),
    version_authorId: varchar("version_author_id"),
    version_authorName: varchar("version_author_name"),
    version_authorType: enum__articles_v_version_author_type(
      "version_author_type",
    ).default("admin"),
    version_reviewStatus: enum__articles_v_version_review_status(
      "version_review_status",
    ),
    version_reviewNote: varchar("version_review_note"),
    version_status:
      enum__articles_v_version_status("version_status").default("draft"),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__articles_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__articles_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_articles_v_parent_idx").on(columns.parent),
    index("_articles_v_version_version_slug_idx").on(columns.version_slug),
    index("_articles_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_articles_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_articles_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_articles_v_created_at_idx").on(columns.createdAt),
    index("_articles_v_updated_at_idx").on(columns.updatedAt),
    index("_articles_v_snapshot_idx").on(columns.snapshot),
    index("_articles_v_published_locale_idx").on(columns.publishedLocale),
    index("_articles_v_latest_idx").on(columns.latest),
  ],
);

export const _articles_v_locales = pgTable(
  "_articles_v_locales",
  {
    version_title: varchar("version_title"),
    version_content: jsonb("version_content"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_articles_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_articles_v.id],
      name: "_articles_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const forum_threads = pgTable(
  "forum_threads",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    content: jsonb("content").notNull(),
    category: enum_forum_threads_category("category")
      .notNull()
      .default("general"),
    authorId: varchar("author_id").notNull(),
    authorName: varchar("author_name"),
    authorRole: enum_forum_threads_author_role("author_role").default("member"),
    isPinned: boolean("is_pinned").default(false),
    isLocked: boolean("is_locked").default(false),
    viewCount: numeric("view_count", { mode: "number" }).default(0),
    replyCount: numeric("reply_count", { mode: "number" }).default(0),
    lastActivityAt: timestamp("last_activity_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("forum_threads_slug_idx").on(columns.slug),
    index("forum_threads_updated_at_idx").on(columns.updatedAt),
    index("forum_threads_created_at_idx").on(columns.createdAt),
  ],
);

export const forum_replies = pgTable(
  "forum_replies",
  {
    id: serial("id").primaryKey(),
    thread: integer("thread_id")
      .notNull()
      .references(() => forum_threads.id, {
        onDelete: "set null",
      }),
    content: jsonb("content").notNull(),
    authorId: varchar("author_id").notNull(),
    authorName: varchar("author_name"),
    authorRole: enum_forum_replies_author_role("author_role").default("member"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("forum_replies_thread_idx").on(columns.thread),
    index("forum_replies_updated_at_idx").on(columns.updatedAt),
    index("forum_replies_created_at_idx").on(columns.createdAt),
  ],
);

export const community_ideas = pgTable(
  "community_ideas",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    authorId: varchar("author_id").notNull(),
    authorName: varchar("author_name"),
    status: enum_community_ideas_status("status").notNull().default("open"),
    voteCount: numeric("vote_count", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("community_ideas_updated_at_idx").on(columns.updatedAt),
    index("community_ideas_created_at_idx").on(columns.createdAt),
  ],
);

export const idea_votes = pgTable(
  "idea_votes",
  {
    id: serial("id").primaryKey(),
    idea: integer("idea_id")
      .notNull()
      .references(() => community_ideas.id, {
        onDelete: "set null",
      }),
    voterId: varchar("voter_id").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("idea_votes_idea_idx").on(columns.idea),
    index("idea_votes_updated_at_idx").on(columns.updatedAt),
    index("idea_votes_created_at_idx").on(columns.createdAt),
  ],
);

export const challenges_objectives = pgTable(
  "challenges_objectives",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    description: varchar("description").notNull(),
    verification: enum_challenges_objectives_verification("verification")
      .notNull()
      .default("self-report"),
    action: enum_challenges_objectives_action("action"),
    testPattern: varchar("test_pattern"),
    targetCount: numeric("target_count", { mode: "number" })
      .notNull()
      .default(1),
    filter: jsonb("filter"),
  },
  (columns) => [
    index("challenges_objectives_order_idx").on(columns._order),
    index("challenges_objectives_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [challenges.id],
      name: "challenges_objectives_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const challenges = pgTable(
  "challenges",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    description: jsonb("description").notNull(),
    type: enum_challenges_type("type").notNull(),
    status: enum_challenges_status("status").notNull().default("draft"),
    difficulty: enum_challenges_difficulty("difficulty")
      .notNull()
      .default("beginner"),
    startsAt: timestamp("starts_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    endsAt: timestamp("ends_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    publishedBy: enum_challenges_published_by("published_by")
      .notNull()
      .default("member"),
    generatedBy: enum_challenges_generated_by("generated_by").default("human"),
    creatorId: varchar("creator_id").notNull(),
    repo_templateUrl: varchar("repo_template_url"),
    repo_configFile: boolean("repo_config_file").default(false),
    repo_testCommand: varchar("repo_test_command"),
    repo_colabUrl: varchar("repo_colab_url"),
    rewards_xpReward: numeric("rewards_xp_reward", { mode: "number" })
      .notNull()
      .default(0),
    rewards_badgeReward: varchar("rewards_badge_reward"),
    rewards_sponsorReward: varchar("rewards_sponsor_reward"),
    maxParticipants: numeric("max_participants", { mode: "number" }).default(0),
    tags: jsonb("tags"),
    signalSource_type: enum_challenges_signal_source_type("signal_source_type"),
    signalSource_reference: varchar("signal_source_reference"),
    signalSource_summary: varchar("signal_source_summary"),
    rankingMode: enum_challenges_ranking_mode("ranking_mode").default("speed"),
    collaborationModel: enum_challenges_collaboration_model(
      "collaboration_model",
    ).default("solo-ai"),
    proposedBy: varchar("proposed_by"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("challenges_slug_idx").on(columns.slug),
    index("challenges_image_idx").on(columns.image),
    index("challenges_updated_at_idx").on(columns.updatedAt),
    index("challenges_created_at_idx").on(columns.createdAt),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const pages_locales = pgTable(
  "pages_locales",
  {
    title: varchar("title"),
    content: jsonb("content"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__pages_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_version_slug_idx").on(columns.version_slug),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_snapshot_idx").on(columns.snapshot),
    index("_pages_v_published_locale_idx").on(columns.publishedLocale),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const _pages_v_locales = pgTable(
  "_pages_v_locales",
  {
    version_title: varchar("version_title"),
    version_content: jsonb("version_content"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_pages_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const sponsors = pgTable(
  "sponsors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    logo: integer("logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    website: varchar("website"),
    tier: enum_sponsors_tier("tier").notNull(),
    featured: boolean("featured").default(false),
    status: enum_sponsors_status("status").notNull().default("active"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("sponsors_slug_idx").on(columns.slug),
    index("sponsors_logo_idx").on(columns.logo),
    index("sponsors_updated_at_idx").on(columns.updatedAt),
    index("sponsors_created_at_idx").on(columns.createdAt),
  ],
);

export const sponsors_locales = pgTable(
  "sponsors_locales",
  {
    tagline: varchar("tagline"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("sponsors_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [sponsors.id],
      name: "sponsors_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const sponsor_applications = pgTable(
  "sponsor_applications",
  {
    id: serial("id").primaryKey(),
    companyName: varchar("company_name").notNull(),
    website: varchar("website"),
    contactName: varchar("contact_name").notNull(),
    contactEmail: varchar("contact_email").notNull(),
    tier: enum_sponsor_applications_tier("tier").notNull(),
    message: varchar("message"),
    status: enum_sponsor_applications_status("status")
      .notNull()
      .default("pending"),
    notes: varchar("notes"),
    appliedAt: timestamp("applied_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("sponsor_applications_updated_at_idx").on(columns.updatedAt),
    index("sponsor_applications_created_at_idx").on(columns.createdAt),
  ],
);

export const jobs_tags = pgTable(
  "jobs_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag").notNull(),
  },
  (columns) => [
    index("jobs_tags_order_idx").on(columns._order),
    index("jobs_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [jobs.id],
      name: "jobs_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const jobs = pgTable(
  "jobs",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    sponsor: integer("sponsor_id")
      .notNull()
      .references(() => sponsors.id, {
        onDelete: "set null",
      }),
    description: jsonb("description").notNull(),
    location: varchar("location").notNull(),
    type: enum_jobs_type("type").notNull(),
    url: varchar("url").notNull(),
    status: enum_jobs_status("status").notNull().default("active"),
    postedAt: timestamp("posted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("jobs_sponsor_idx").on(columns.sponsor),
    index("jobs_updated_at_idx").on(columns.updatedAt),
    index("jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const rules_acceptance = pgTable(
  "rules_acceptance",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").notNull(),
    rulesVersion: numeric("rules_version", { mode: "number" }).notNull(),
    acceptedAt: timestamp("accepted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("rules_acceptance_user_id_idx").on(columns.userId),
    index("rules_acceptance_updated_at_idx").on(columns.updatedAt),
    index("rules_acceptance_created_at_idx").on(columns.createdAt),
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    role: enum_users_role("role").default("editor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    eventsID: integer("events_id"),
    speakersID: integer("speakers_id"),
    articlesID: integer("articles_id"),
    "forum-threadsID": integer("forum_threads_id"),
    "forum-repliesID": integer("forum_replies_id"),
    "community-ideasID": integer("community_ideas_id"),
    "idea-votesID": integer("idea_votes_id"),
    challengesID: integer("challenges_id"),
    pagesID: integer("pages_id"),
    mediaID: integer("media_id"),
    sponsorsID: integer("sponsors_id"),
    "sponsor-applicationsID": integer("sponsor_applications_id"),
    jobsID: integer("jobs_id"),
    "rules-acceptanceID": integer("rules_acceptance_id"),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    index("payload_locked_documents_rels_speakers_id_idx").on(
      columns.speakersID,
    ),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_forum_threads_id_idx").on(
      columns["forum-threadsID"],
    ),
    index("payload_locked_documents_rels_forum_replies_id_idx").on(
      columns["forum-repliesID"],
    ),
    index("payload_locked_documents_rels_community_ideas_id_idx").on(
      columns["community-ideasID"],
    ),
    index("payload_locked_documents_rels_idea_votes_id_idx").on(
      columns["idea-votesID"],
    ),
    index("payload_locked_documents_rels_challenges_id_idx").on(
      columns.challengesID,
    ),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_sponsors_id_idx").on(
      columns.sponsorsID,
    ),
    index("payload_locked_documents_rels_sponsor_applications_id_idx").on(
      columns["sponsor-applicationsID"],
    ),
    index("payload_locked_documents_rels_jobs_id_idx").on(columns.jobsID),
    index("payload_locked_documents_rels_rules_acceptance_id_idx").on(
      columns["rules-acceptanceID"],
    ),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["speakersID"]],
      foreignColumns: [speakers.id],
      name: "payload_locked_documents_rels_speakers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["forum-threadsID"]],
      foreignColumns: [forum_threads.id],
      name: "payload_locked_documents_rels_forum_threads_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["forum-repliesID"]],
      foreignColumns: [forum_replies.id],
      name: "payload_locked_documents_rels_forum_replies_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["community-ideasID"]],
      foreignColumns: [community_ideas.id],
      name: "payload_locked_documents_rels_community_ideas_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["idea-votesID"]],
      foreignColumns: [idea_votes.id],
      name: "payload_locked_documents_rels_idea_votes_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["challengesID"]],
      foreignColumns: [challenges.id],
      name: "payload_locked_documents_rels_challenges_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["sponsorsID"]],
      foreignColumns: [sponsors.id],
      name: "payload_locked_documents_rels_sponsors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["sponsor-applicationsID"]],
      foreignColumns: [sponsor_applications.id],
      name: "payload_locked_documents_rels_sponsor_applications_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["jobsID"]],
      foreignColumns: [jobs.id],
      name: "payload_locked_documents_rels_jobs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["rules-acceptanceID"]],
      foreignColumns: [rules_acceptance.id],
      name: "payload_locked_documents_rels_rules_acceptance_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const community_rules_sections = pgTable(
  "community_rules_sections",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    slug: varchar("slug").notNull(),
    icon: enum_community_rules_sections_icon("icon"),
  },
  (columns) => [
    index("community_rules_sections_order_idx").on(columns._order),
    index("community_rules_sections_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [community_rules.id],
      name: "community_rules_sections_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const community_rules_sections_locales = pgTable(
  "community_rules_sections_locales",
  {
    title: varchar("title").notNull(),
    content: jsonb("content").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("community_rules_sections_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [community_rules_sections.id],
      name: "community_rules_sections_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const community_rules = pgTable("community_rules", {
  id: serial("id").primaryKey(),
  version: numeric("version", { mode: "number" }).notNull().default(1),
  effectiveDate: timestamp("effective_date", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }).notNull(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_events_locales = relations(
  events_locales,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_locales._parentID],
      references: [events.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_events_rels = relations(events_rels, ({ one }) => ({
  parent: one(events, {
    fields: [events_rels.parent],
    references: [events.id],
    relationName: "_rels",
  }),
  speakersID: one(speakers, {
    fields: [events_rels.speakersID],
    references: [speakers.id],
    relationName: "speakers",
  }),
}));
export const relations_events = relations(events, ({ one, many }) => ({
  image: one(media, {
    fields: [events.image],
    references: [media.id],
    relationName: "image",
  }),
  _locales: many(events_locales, {
    relationName: "_locales",
  }),
  _rels: many(events_rels, {
    relationName: "_rels",
  }),
}));
export const relations__events_v_locales = relations(
  _events_v_locales,
  ({ one }) => ({
    _parentID: one(_events_v, {
      fields: [_events_v_locales._parentID],
      references: [_events_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__events_v_rels = relations(
  _events_v_rels,
  ({ one }) => ({
    parent: one(_events_v, {
      fields: [_events_v_rels.parent],
      references: [_events_v.id],
      relationName: "_rels",
    }),
    speakersID: one(speakers, {
      fields: [_events_v_rels.speakersID],
      references: [speakers.id],
      relationName: "speakers",
    }),
  }),
);
export const relations__events_v = relations(_events_v, ({ one, many }) => ({
  parent: one(events, {
    fields: [_events_v.parent],
    references: [events.id],
    relationName: "parent",
  }),
  version_image: one(media, {
    fields: [_events_v.version_image],
    references: [media.id],
    relationName: "version_image",
  }),
  _locales: many(_events_v_locales, {
    relationName: "_locales",
  }),
  _rels: many(_events_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_speakers_locales = relations(
  speakers_locales,
  ({ one }) => ({
    _parentID: one(speakers, {
      fields: [speakers_locales._parentID],
      references: [speakers.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_speakers = relations(speakers, ({ one, many }) => ({
  photo: one(media, {
    fields: [speakers.photo],
    references: [media.id],
    relationName: "photo",
  }),
  _locales: many(speakers_locales, {
    relationName: "_locales",
  }),
}));
export const relations_articles_tags = relations(articles_tags, ({ one }) => ({
  _parentID: one(articles, {
    fields: [articles_tags._parentID],
    references: [articles.id],
    relationName: "tags",
  }),
}));
export const relations_articles_locales = relations(
  articles_locales,
  ({ one }) => ({
    _parentID: one(articles, {
      fields: [articles_locales._parentID],
      references: [articles.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_articles = relations(articles, ({ many }) => ({
  tags: many(articles_tags, {
    relationName: "tags",
  }),
  _locales: many(articles_locales, {
    relationName: "_locales",
  }),
}));
export const relations__articles_v_version_tags = relations(
  _articles_v_version_tags,
  ({ one }) => ({
    _parentID: one(_articles_v, {
      fields: [_articles_v_version_tags._parentID],
      references: [_articles_v.id],
      relationName: "version_tags",
    }),
  }),
);
export const relations__articles_v_locales = relations(
  _articles_v_locales,
  ({ one }) => ({
    _parentID: one(_articles_v, {
      fields: [_articles_v_locales._parentID],
      references: [_articles_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__articles_v = relations(
  _articles_v,
  ({ one, many }) => ({
    parent: one(articles, {
      fields: [_articles_v.parent],
      references: [articles.id],
      relationName: "parent",
    }),
    version_tags: many(_articles_v_version_tags, {
      relationName: "version_tags",
    }),
    _locales: many(_articles_v_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_forum_threads = relations(forum_threads, () => ({}));
export const relations_forum_replies = relations(forum_replies, ({ one }) => ({
  thread: one(forum_threads, {
    fields: [forum_replies.thread],
    references: [forum_threads.id],
    relationName: "thread",
  }),
}));
export const relations_community_ideas = relations(community_ideas, () => ({}));
export const relations_idea_votes = relations(idea_votes, ({ one }) => ({
  idea: one(community_ideas, {
    fields: [idea_votes.idea],
    references: [community_ideas.id],
    relationName: "idea",
  }),
}));
export const relations_challenges_objectives = relations(
  challenges_objectives,
  ({ one }) => ({
    _parentID: one(challenges, {
      fields: [challenges_objectives._parentID],
      references: [challenges.id],
      relationName: "objectives",
    }),
  }),
);
export const relations_challenges = relations(challenges, ({ one, many }) => ({
  objectives: many(challenges_objectives, {
    relationName: "objectives",
  }),
  image: one(media, {
    fields: [challenges.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: "_locales",
  }),
}));
export const relations_pages = relations(pages, ({ many }) => ({
  _locales: many(pages_locales, {
    relationName: "_locales",
  }),
}));
export const relations__pages_v_locales = relations(
  _pages_v_locales,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_locales._parentID],
      references: [_pages_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  _locales: many(_pages_v_locales, {
    relationName: "_locales",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_sponsors_locales = relations(
  sponsors_locales,
  ({ one }) => ({
    _parentID: one(sponsors, {
      fields: [sponsors_locales._parentID],
      references: [sponsors.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_sponsors = relations(sponsors, ({ one, many }) => ({
  logo: one(media, {
    fields: [sponsors.logo],
    references: [media.id],
    relationName: "logo",
  }),
  _locales: many(sponsors_locales, {
    relationName: "_locales",
  }),
}));
export const relations_sponsor_applications = relations(
  sponsor_applications,
  () => ({}),
);
export const relations_jobs_tags = relations(jobs_tags, ({ one }) => ({
  _parentID: one(jobs, {
    fields: [jobs_tags._parentID],
    references: [jobs.id],
    relationName: "tags",
  }),
}));
export const relations_jobs = relations(jobs, ({ one, many }) => ({
  sponsor: one(sponsors, {
    fields: [jobs.sponsor],
    references: [sponsors.id],
    relationName: "sponsor",
  }),
  tags: many(jobs_tags, {
    relationName: "tags",
  }),
}));
export const relations_rules_acceptance = relations(
  rules_acceptance,
  () => ({}),
);
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
    speakersID: one(speakers, {
      fields: [payload_locked_documents_rels.speakersID],
      references: [speakers.id],
      relationName: "speakers",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    "forum-threadsID": one(forum_threads, {
      fields: [payload_locked_documents_rels["forum-threadsID"]],
      references: [forum_threads.id],
      relationName: "forum-threads",
    }),
    "forum-repliesID": one(forum_replies, {
      fields: [payload_locked_documents_rels["forum-repliesID"]],
      references: [forum_replies.id],
      relationName: "forum-replies",
    }),
    "community-ideasID": one(community_ideas, {
      fields: [payload_locked_documents_rels["community-ideasID"]],
      references: [community_ideas.id],
      relationName: "community-ideas",
    }),
    "idea-votesID": one(idea_votes, {
      fields: [payload_locked_documents_rels["idea-votesID"]],
      references: [idea_votes.id],
      relationName: "idea-votes",
    }),
    challengesID: one(challenges, {
      fields: [payload_locked_documents_rels.challengesID],
      references: [challenges.id],
      relationName: "challenges",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    sponsorsID: one(sponsors, {
      fields: [payload_locked_documents_rels.sponsorsID],
      references: [sponsors.id],
      relationName: "sponsors",
    }),
    "sponsor-applicationsID": one(sponsor_applications, {
      fields: [payload_locked_documents_rels["sponsor-applicationsID"]],
      references: [sponsor_applications.id],
      relationName: "sponsor-applications",
    }),
    jobsID: one(jobs, {
      fields: [payload_locked_documents_rels.jobsID],
      references: [jobs.id],
      relationName: "jobs",
    }),
    "rules-acceptanceID": one(rules_acceptance, {
      fields: [payload_locked_documents_rels["rules-acceptanceID"]],
      references: [rules_acceptance.id],
      relationName: "rules-acceptance",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_community_rules_sections_locales = relations(
  community_rules_sections_locales,
  ({ one }) => ({
    _parentID: one(community_rules_sections, {
      fields: [community_rules_sections_locales._parentID],
      references: [community_rules_sections.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_community_rules_sections = relations(
  community_rules_sections,
  ({ one, many }) => ({
    _parentID: one(community_rules, {
      fields: [community_rules_sections._parentID],
      references: [community_rules.id],
      relationName: "sections",
    }),
    _locales: many(community_rules_sections_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_community_rules = relations(
  community_rules,
  ({ many }) => ({
    sections: many(community_rules_sections, {
      relationName: "sections",
    }),
  }),
);

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_events_type: typeof enum_events_type;
  enum_events_status: typeof enum_events_status;
  enum__events_v_version_type: typeof enum__events_v_version_type;
  enum__events_v_version_status: typeof enum__events_v_version_status;
  enum__events_v_published_locale: typeof enum__events_v_published_locale;
  enum_articles_type: typeof enum_articles_type;
  enum_articles_author_type: typeof enum_articles_author_type;
  enum_articles_review_status: typeof enum_articles_review_status;
  enum_articles_status: typeof enum_articles_status;
  enum__articles_v_version_type: typeof enum__articles_v_version_type;
  enum__articles_v_version_author_type: typeof enum__articles_v_version_author_type;
  enum__articles_v_version_review_status: typeof enum__articles_v_version_review_status;
  enum__articles_v_version_status: typeof enum__articles_v_version_status;
  enum__articles_v_published_locale: typeof enum__articles_v_published_locale;
  enum_forum_threads_category: typeof enum_forum_threads_category;
  enum_forum_threads_author_role: typeof enum_forum_threads_author_role;
  enum_forum_replies_author_role: typeof enum_forum_replies_author_role;
  enum_community_ideas_status: typeof enum_community_ideas_status;
  enum_challenges_objectives_verification: typeof enum_challenges_objectives_verification;
  enum_challenges_objectives_action: typeof enum_challenges_objectives_action;
  enum_challenges_type: typeof enum_challenges_type;
  enum_challenges_status: typeof enum_challenges_status;
  enum_challenges_difficulty: typeof enum_challenges_difficulty;
  enum_challenges_published_by: typeof enum_challenges_published_by;
  enum_challenges_generated_by: typeof enum_challenges_generated_by;
  enum_challenges_signal_source_type: typeof enum_challenges_signal_source_type;
  enum_challenges_ranking_mode: typeof enum_challenges_ranking_mode;
  enum_challenges_collaboration_model: typeof enum_challenges_collaboration_model;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum__pages_v_published_locale: typeof enum__pages_v_published_locale;
  enum_sponsors_tier: typeof enum_sponsors_tier;
  enum_sponsors_status: typeof enum_sponsors_status;
  enum_sponsor_applications_tier: typeof enum_sponsor_applications_tier;
  enum_sponsor_applications_status: typeof enum_sponsor_applications_status;
  enum_jobs_type: typeof enum_jobs_type;
  enum_jobs_status: typeof enum_jobs_status;
  enum_users_role: typeof enum_users_role;
  enum_community_rules_sections_icon: typeof enum_community_rules_sections_icon;
  events: typeof events;
  events_locales: typeof events_locales;
  events_rels: typeof events_rels;
  _events_v: typeof _events_v;
  _events_v_locales: typeof _events_v_locales;
  _events_v_rels: typeof _events_v_rels;
  speakers: typeof speakers;
  speakers_locales: typeof speakers_locales;
  articles_tags: typeof articles_tags;
  articles: typeof articles;
  articles_locales: typeof articles_locales;
  _articles_v_version_tags: typeof _articles_v_version_tags;
  _articles_v: typeof _articles_v;
  _articles_v_locales: typeof _articles_v_locales;
  forum_threads: typeof forum_threads;
  forum_replies: typeof forum_replies;
  community_ideas: typeof community_ideas;
  idea_votes: typeof idea_votes;
  challenges_objectives: typeof challenges_objectives;
  challenges: typeof challenges;
  pages: typeof pages;
  pages_locales: typeof pages_locales;
  _pages_v: typeof _pages_v;
  _pages_v_locales: typeof _pages_v_locales;
  media: typeof media;
  sponsors: typeof sponsors;
  sponsors_locales: typeof sponsors_locales;
  sponsor_applications: typeof sponsor_applications;
  jobs_tags: typeof jobs_tags;
  jobs: typeof jobs;
  rules_acceptance: typeof rules_acceptance;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  community_rules_sections: typeof community_rules_sections;
  community_rules_sections_locales: typeof community_rules_sections_locales;
  community_rules: typeof community_rules;
  relations_events_locales: typeof relations_events_locales;
  relations_events_rels: typeof relations_events_rels;
  relations_events: typeof relations_events;
  relations__events_v_locales: typeof relations__events_v_locales;
  relations__events_v_rels: typeof relations__events_v_rels;
  relations__events_v: typeof relations__events_v;
  relations_speakers_locales: typeof relations_speakers_locales;
  relations_speakers: typeof relations_speakers;
  relations_articles_tags: typeof relations_articles_tags;
  relations_articles_locales: typeof relations_articles_locales;
  relations_articles: typeof relations_articles;
  relations__articles_v_version_tags: typeof relations__articles_v_version_tags;
  relations__articles_v_locales: typeof relations__articles_v_locales;
  relations__articles_v: typeof relations__articles_v;
  relations_forum_threads: typeof relations_forum_threads;
  relations_forum_replies: typeof relations_forum_replies;
  relations_community_ideas: typeof relations_community_ideas;
  relations_idea_votes: typeof relations_idea_votes;
  relations_challenges_objectives: typeof relations_challenges_objectives;
  relations_challenges: typeof relations_challenges;
  relations_pages_locales: typeof relations_pages_locales;
  relations_pages: typeof relations_pages;
  relations__pages_v_locales: typeof relations__pages_v_locales;
  relations__pages_v: typeof relations__pages_v;
  relations_media: typeof relations_media;
  relations_sponsors_locales: typeof relations_sponsors_locales;
  relations_sponsors: typeof relations_sponsors;
  relations_sponsor_applications: typeof relations_sponsor_applications;
  relations_jobs_tags: typeof relations_jobs_tags;
  relations_jobs: typeof relations_jobs;
  relations_rules_acceptance: typeof relations_rules_acceptance;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_community_rules_sections_locales: typeof relations_community_rules_sections_locales;
  relations_community_rules_sections: typeof relations_community_rules_sections;
  relations_community_rules: typeof relations_community_rules;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
